#!/usr/bin/env python3
"""Save and apply this checkout's optional disposable-storage configuration."""

import argparse
import json
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import tempfile

MARKER = "# Generated by .cargo/setup-scratch.py; do not edit.\n"
SETTINGS = ".cargo/scratch.local.json"
PROJECTS = ("npm", "e2e/foundry-sample", "e2e/hardhat-sample", "e2e/hardhat3-sample")
PATHS = (
    "target",
    "coverage",
    ".doublcov",
    "fuzz/target",
    "fuzz/logs",
    "fuzz/corpus",
    "npm/abi-typegen/bin",
    "e2e/foundry-sample/out",
    "e2e/foundry-sample/cache",
    "e2e/foundry-sample/src/generated",
    "e2e/hardhat-sample/artifacts",
    "e2e/hardhat-sample/cache",
    "e2e/hardhat-sample/typechain-types",
    "e2e/hardhat-sample/abi-typegen-out",
    "e2e/hardhat3-sample/artifacts",
    "e2e/hardhat3-sample/cache",
    "e2e/hardhat3-sample/abi-typegen-out",
)
PRESERVED = ("fuzz/corpus", ".doublcov")
# pnpm 12 writes links into each project's own node_modules, so these stay real
# directories. The generated pnpm settings move the packages themselves to storage.
NODE_MODULES = (
    "npm/node_modules",
    "npm/hardhat-abi-typegen/node_modules",
    "e2e/foundry-sample/node_modules",
    "e2e/hardhat-sample/node_modules",
    "e2e/hardhat3-sample/node_modules",
)


def check_parents(root, relative):
    """Reject redirected or non-directory ancestors before any filesystem writes."""
    parent = root
    for part in Path(relative).parts[:-1]:
        parent /= part
        if parent.is_symlink():
            raise ValueError(f"Unexpected parent symlink: {parent}")
        if parent.exists() and not parent.is_dir():
            raise ValueError(f"Expected directory: {parent}")


def load_settings(repo):
    """Read a saved choice without following a settings or configuration symlink."""
    check_parents(repo, SETTINGS)
    path = repo / SETTINGS
    if path.is_symlink():
        raise ValueError(f"Unexpected settings symlink: {path}")
    if not path.exists():
        return {}
    settings = json.loads(path.read_text())
    if not isinstance(settings, dict):
        raise ValueError("Saved storage settings must be a JSON object.")
    for key in ("root", "volume"):
        value = settings.get(key)
        if key == "volume" and value is None:
            continue
        if not isinstance(value, str) or not Path(value).is_absolute():
            raise ValueError(f"Saved storage {key} must be an absolute path.")
    return settings


def check_untracked(repo, relatives):
    """Refuse to change tracked files, directories, or tracked ancestor links."""
    tracked = (
        subprocess.check_output(["git", "ls-files", "-z"], cwd=repo)
        .decode()
        .split("\0")
    )
    for relative in relatives:
        check_parents(repo, relative)
        if any(
            p
            and (
                p == relative
                or p.startswith(relative + "/")
                or relative.startswith(p + "/")
            )
            for p in tracked
        ):
            raise ValueError(
                f"Refusing to relocate or overwrite tracked path: {relative}"
            )


def environment(storage):
    """Return process settings derived from one saved storage root."""
    return {
        "CARGO_TARGET_DIR": str(storage / "target"),
        "TMPDIR": str(storage / "tmp"),
        "TMP": str(storage / "tmp"),
        "TEMP": str(storage / "tmp"),
        "SCCACHE_DIR": str(storage / "cache/sccache"),
        "SCCACHE_SERVER_UDS": str(storage / "sccache.sock"),
        "SCCACHE_ERROR_LOG": str(storage / "logs/sccache.log"),
        "npm_config_cache": str(storage / "cache/npm"),
        "pnpm_config_store_dir": str(storage / "cache/pnpm"),
        "pnpm_config_cache_dir": str(storage / "cache/pnpm-metadata"),
        "PYTHONPYCACHEPREFIX": str(storage / "cache/python"),
    }


def virtual_store(storage, project):
    """Return where pnpm keeps a project's installed packages."""
    return storage / project / "node_modules/.pnpm"


def generated_files(storage):
    """Render local tool settings without embedding paths in tracked files."""
    env = environment(storage)
    cargo = (
        "[build]\ntarget-dir = "
        + json.dumps(str(storage / "target"), ensure_ascii=False)
        + "\n\n[env]\n"
    )
    for key, value in env.items():
        if key != "CARGO_TARGET_DIR":
            cargo += f"{key} = {{ value = {json.dumps(value, ensure_ascii=False)}, force = true }}\n"
    make = ""
    shell = ""
    for key, value in env.items():
        escaped = value.replace("$", "$$").replace("#", "\\#")
        make += f"export {key} := {escaped}\n"
        shell += f"export {key}={shlex.quote(value)}\n"
    files = {
        ".cargo/config.toml": cargo,
        ".cargo/scratch.local.mk": make,
        ".cargo/scratch.local.env": shell,
    }
    for project in PROJECTS:
        files[project + "/pnpm-workspace.yaml"] = (
            f"virtualStoreDir: {json.dumps(str(virtual_store(storage, project)), ensure_ascii=False)}\n"
            f"storeDir: {json.dumps(str(storage / 'cache/pnpm'), ensure_ascii=False)}\n"
            f"cacheDir: {json.dumps(str(storage / 'cache/pnpm-metadata'), ensure_ascii=False)}\n"
        )
    return {name: MARKER + content for name, content in files.items()}


def configure(repo, storage=None, volume=None):
    """Apply a saved root or persist a new one after checking for conflicts.

    When switching roots, retain old build caches at the previous location and
    copy the discovered fuzz corpus and coverage history to the new location.
    """
    repo = repo.resolve()
    settings_path = repo / SETTINGS
    previous = load_settings(repo)
    old_root = Path(previous["root"]) if previous else None
    if storage is None:
        if not previous:
            raise ValueError("No saved storage root. Configure once with --root PATH.")
        storage = old_root
        volume = previous.get("volume")
    storage = Path(storage).expanduser().resolve()
    if any(c in str(storage) for c in "\n\r\\"):
        raise ValueError("Storage paths cannot contain newlines or backslashes.")
    if storage.is_relative_to(repo) or repo.is_relative_to(storage):
        raise ValueError("Storage must be outside the checkout, not its ancestor.")
    if (
        old_root
        and storage != old_root
        and (storage.is_relative_to(old_root) or old_root.is_relative_to(storage))
    ):
        raise ValueError("The new and previous storage roots cannot overlap.")
    if volume is not None:
        volume = Path(volume).expanduser().resolve()
        if not os.path.ismount(volume):
            raise ValueError(f"Required volume is not mounted: {volume}")
        if not storage.is_relative_to(volume):
            raise ValueError("Storage must be within the required volume.")
    files = generated_files(storage)
    check_untracked(repo, (*PATHS, *NODE_MODULES, *files, SETTINGS))
    for relative in NODE_MODULES:
        check_parents(repo, relative)
        source = repo / relative
        if source.is_symlink() and source.readlink() not in (
            storage / relative,
            *((old_root / relative,) if old_root else ()),
        ):
            raise ValueError(f"Unexpected symlink: {source}")
    for relative in files:
        path = repo / relative
        if path.is_symlink() or (
            path.exists() and not path.read_text().startswith(MARKER)
        ):
            raise ValueError(f"Refusing to overwrite unrelated configuration: {path}")
    for relative in PATHS:
        source, destination = repo / relative, storage / relative
        check_parents(storage, relative)
        if destination.exists() and not destination.is_dir():
            raise ValueError(f"Refusing to overwrite existing file: {destination}")
        if destination.is_symlink() or not destination.resolve().is_relative_to(
            storage
        ):
            raise ValueError(f"Destination escapes storage: {destination}")
        if source.is_symlink():
            if source.readlink() == destination:
                continue
            if old_root is None or source.readlink() != old_root / relative:
                raise ValueError(f"Unexpected symlink: {source}")
            if destination.exists():
                raise ValueError(f"Refusing to overwrite existing data: {destination}")
        elif source.exists() and (not source.is_dir() or destination.exists()):
            raise ValueError(f"Refusing to overwrite existing data: {source}")

    # Environment-only destinations need the same checks as linked directories.
    for value in environment(storage).values():
        destination = Path(value)
        check_parents(storage, destination.relative_to(storage))
        if destination.is_symlink():
            raise ValueError(f"Unexpected storage symlink: {destination}")
        if (
            destination.name not in ("sccache.sock", "sccache.log")
            and destination.exists()
            and not destination.is_dir()
        ):
            raise ValueError(f"Expected storage directory: {destination}")

    for relative in ("tmp", "cache/sccache", "cache/npm", "cache/pnpm", "logs"):
        (storage / relative).mkdir(parents=True, exist_ok=True)
    for relative in PATHS:
        source, destination = repo / relative, storage / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        if source.is_symlink() and source.readlink() != destination:
            if relative in PRESERVED and source.exists():
                shutil.copytree(source, destination, symlinks=True)
            source.unlink()
        elif source.exists() and not source.is_symlink():
            shutil.move(str(source), str(destination))
        destination.mkdir(parents=True, exist_ok=True)
        if not source.is_symlink():
            source.parent.mkdir(parents=True, exist_ok=True)
            source.symlink_to(destination, target_is_directory=True)
    for relative in NODE_MODULES:
        # Earlier versions linked node_modules into storage. Drop the link; the
        # packages stay in storage and the next pnpm install links them again.
        source = repo / relative
        if source.is_symlink():
            source.unlink()
    for relative, content in files.items():
        path = repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    settings_path.write_text(
        json.dumps(
            {"root": str(storage), "volume": str(volume) if volume else None}, indent=2
        )
        + "\n"
    )
    return environment(storage)


def disable(repo):
    """Remove managed settings and links, preserving external data and local history."""
    repo = repo.resolve()
    previous = load_settings(repo)
    if not previous:
        return
    storage = Path(previous["root"])
    files = generated_files(storage)
    check_untracked(repo, (*PATHS, *NODE_MODULES, *files, SETTINGS))
    for relative, expected in files.items():
        path = repo / relative
        if path.is_symlink() or (path.exists() and path.read_text() != expected):
            raise ValueError(
                f"Refusing to remove modified or unrelated configuration: {path}"
            )
    for relative in PATHS:
        path = repo / relative
        if path.is_symlink() and path.readlink() != storage / relative:
            raise ValueError(f"Unexpected symlink: {path}")
    for relative in NODE_MODULES:
        check_parents(repo, relative)
        path = repo / relative
        if path.is_symlink() and path.readlink() != storage / relative:
            raise ValueError(f"Unexpected symlink: {path}")

    # Finish all potentially expensive copies before changing the active setup.
    # Other build output stays in storage and can be regenerated under defaults.
    with tempfile.TemporaryDirectory(prefix=".scratch-disable-", dir=repo) as temporary:
        staged = Path(temporary)
        for relative in PRESERVED:
            source = repo / relative
            if source.is_symlink() and source.exists():
                shutil.copytree(source, staged / relative, symlinks=True)
        for relative in PATHS:
            path = repo / relative
            if path.is_symlink():
                path.unlink()
            restored = staged / relative
            if restored.exists():
                restored.rename(path)
        for relative in NODE_MODULES:
            # Its links point into storage's virtual store, which pnpm will no
            # longer use. Removing it lets the next pnpm install start clean.
            path = repo / relative
            if path.is_symlink():
                path.unlink()
            elif path.is_dir():
                shutil.rmtree(path)
        for relative in files:
            (repo / relative).unlink(missing_ok=True)
        (repo / SETTINGS).unlink()


def main():
    """Configure once, reapply saved settings, or run an optional command."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, help="Save this disposable-storage directory"
    )
    parser.add_argument("--volume", type=Path, help="Require this mount to be present")
    parser.add_argument(
        "--disable",
        action="store_true",
        help="Restore normal storage defaults; keep external data",
    )
    parser.add_argument(
        "--run", nargs=argparse.REMAINDER, help="Run with saved settings"
    )
    args = parser.parse_args()
    if args.volume and not args.root:
        parser.error("--volume requires --root")
    if args.disable and (args.root or args.volume or args.run is not None):
        parser.error("--disable cannot be combined with --root, --volume, or --run")
    if args.run == []:
        parser.error("--run requires a command")
    repo = Path(__file__).resolve().parent.parent
    try:
        if args.disable:
            disable(repo)
            print(
                "Disposable storage disabled; external data retained. Start a new shell if you sourced its environment."
            )
            return
        if args.run and args.root is None and not load_settings(repo):
            env = {}
        else:
            env = configure(repo, args.root, args.volume)
    except (ValueError, OSError) as error:
        parser.exit(1, f"{error}\n")
    if args.run:
        os.execvpe(args.run[0], args.run, {**os.environ, **env})
    else:
        print(f"Disposable storage: {Path(env['CARGO_TARGET_DIR']).parent}")


if __name__ == "__main__":
    main()
