//! C++17 ownership and contract helpers over the generated C API.
use super::c::{claim_item, namespace_name};
use crate::naming::Scope;
use abi_typegen_core::types::{ContractIr, StateMutability};

/// Render a C++17 header using the accompanying C header and shared runtime.
pub fn render_cpp_file(ir: &ContractIr, wrappers: bool) -> String {
    let prefix = namespace_name(&ir.name);
    let mut out = format!(
        "// Generated by abi-typegen.\n#pragma once\n#include \"{}.h\"\n#include <memory>\n#include <stdexcept>\n#include <utility>\n#include <vector>\nnamespace {prefix} {{\ninline constexpr const char *abi = ::{prefix}_abi;\n",
        prefix
    );
    if wrappers {
        out.push_str("using RuntimeResult = std::unique_ptr<atg_result, decltype(&atg_result_free)>;\ninline RuntimeResult checked(atg_result *raw) { RuntimeResult result(raw, atg_result_free); if (const char *error = atg_result_error(raw)) throw std::runtime_error(error); return result; }\n// The owned result keeps all borrowed fields and arrays alive.\ntemplate<class T> class Decoded { RuntimeResult owner_; T value_; public: Decoded(RuntimeResult owner, T value) : owner_(std::move(owner)), value_(value) {} Decoded(Decoded&&) = default; Decoded& operator=(Decoded&&) = default; const T& value() const { return value_; } const T* operator->() const { return &value_; } };\ninline std::vector<uint8_t> copy_bytes(const RuntimeResult& r) { const auto *p = atg_result_data(r.get()); const auto n = atg_result_len(r.get()); if (!n) return {}; return {p, p + n}; }\n");
    }
    out.push_str(&format!(
        "using ConstructorParams = ::{prefix}_constructor_params;\n"
    ));
    if wrappers {
        out.push_str(&format!("inline std::vector<uint8_t> encode_constructor(const std::vector<uint8_t>& bytecode, const ConstructorParams& args) {{ return copy_bytes(checked(::{prefix}_encode_constructor(bytecode.data(),bytecode.size(),&args))); }}\ninline std::vector<uint8_t> deploy(atg_transport_fn transport, void *context, const std::vector<uint8_t>& bytecode, const ConstructorParams& args, const atg_call_options *options = nullptr) {{ return copy_bytes(checked(::{prefix}_deploy(transport,context,bytecode.data(),bytecode.size(),&args,options))); }}\n"));
    }
    let mut methods = String::new();
    let mut names = Scope::default();
    for f in &ir.functions {
        let name = claim_item(&mut names, &format!("{prefix}_{}", namespace_name(&f.name)));
        let short = name
            .strip_prefix(&format!("{prefix}_"))
            .expect("generated prefix");
        out.push_str(&format!(
            "using {short}_params = ::{name}_params;\nusing {short}_returns = ::{name}_returns;\n"
        ));
        if !wrappers {
            continue;
        }
        out.push_str(&format!("inline std::vector<uint8_t> {short}_encode(const {short}_params& args) {{ return copy_bytes(checked(::{name}_encode(&args))); }}\ninline Decoded<{short}_returns> {short}_decode(const std::vector<uint8_t>& bytes) {{ {short}_returns value{{}}; auto owner = checked(::{name}_decode(bytes.data(),bytes.size(),&value)); return {{std::move(owner),value}}; }}\n"));
        if matches!(
            f.state_mutability,
            StateMutability::View | StateMutability::Pure
        ) {
            methods.push_str(&format!("Decoded<{short}_returns> {short}(const {short}_params& args, const atg_call_options *options = nullptr) {{ {short}_returns value{{}}; auto owner = checked(::{name}(&client_,&args,options,&value)); return {{std::move(owner),value}}; }}\n"));
        } else {
            methods.push_str(&format!("std::vector<uint8_t> {short}(const {short}_params& args, const atg_call_options *options = nullptr) {{ return copy_bytes(checked(::{name}(&client_,&args,options))); }}\n"));
        }
    }
    for e in &ir.errors {
        let name = claim_item(
            &mut names,
            &format!("{prefix}_{}_error", namespace_name(&e.name)),
        );
        let short = name
            .strip_prefix(&format!("{prefix}_"))
            .expect("generated prefix");
        out.push_str(&format!("using {short}_fields = ::{name}_fields;\n"));
        if wrappers {
            out.push_str(&format!("inline Decoded<{short}_fields> {short}_decode(const std::vector<uint8_t>& bytes) {{ {short}_fields value{{}}; auto owner = checked(::{name}_decode(bytes.data(),bytes.size(),&value)); return {{std::move(owner),value}}; }}\n"));
        }
    }
    for e in &ir.events {
        let name = claim_item(
            &mut names,
            &format!("{prefix}_{}_event", namespace_name(&e.name)),
        );
        let short = name
            .strip_prefix(&format!("{prefix}_"))
            .expect("generated prefix");
        out.push_str(&format!("using {short}_fields = ::{name}_fields;\n"));
        if wrappers {
            out.push_str(&format!("inline Decoded<{short}_fields> {short}_decode(const std::vector<atg_word>& topics, const std::vector<uint8_t>& bytes) {{ {short}_fields value{{}}; auto owner = checked(::{name}_decode(reinterpret_cast<const uint8_t*>(topics.data()),topics.size(),bytes.data(),bytes.size(),&value)); return {{std::move(owner),value}}; }}\n"));
        }
    }
    if wrappers {
        out.push_str(&format!("class Client {{ ::{prefix}_client client_; public: Client(atg_address address, void *context, atg_transport_fn transport) : client_{{address,context,transport}} {{ if (!transport) throw std::invalid_argument(\"missing transport\"); }}\nconst atg_address& address() const {{ return client_.address; }}\n{methods}}};\n"));
    }
    out.push_str("}\n");
    out
}
