//! Dart bindings for web3dart.

use crate::tuples::TupleRegistry;
use abi_typegen_core::types::{ContractIr, SolType, StateMutability};
use heck::{ToLowerCamelCase, ToUpperCamelCase};

/// Dart source filename for a contract.
pub fn file_name(name: &str) -> String {
    format!("{}.dart", namespace_name(name).to_lower_camel_case())
}

/// A legal, non-keyword Dart library namespace/type name.
pub fn namespace_name(name: &str) -> String {
    let mut value = name.to_upper_camel_case();
    if value.is_empty() {
        value = "Contract".into();
    }
    if value.as_bytes()[0].is_ascii_digit() {
        value.insert(0, '_');
    }
    if [
        "Class",
        "Function",
        "BigInt",
        "EthereumAddress",
        "EtherAmount",
        "Credentials",
        "ContractAbi",
        "Web3Client",
        "FilterOptions",
        "ContractFunction",
        "DeployedContract",
        "Transaction",
        "Uint8List",
        "String",
        "Object",
        "List",
        "Map",
        "Set",
        "Future",
        "dynamic",
        "void",
        "int",
        "bool",
        "double",
        "import",
        "library",
        "extension",
        "switch",
        "default",
        "final",
        "var",
        "const",
        "return",
        "new",
        "this",
        "super",
        "enum",
        "try",
        "catch",
        "throw",
        "null",
        "true",
        "false",
    ]
    .contains(&value.as_str())
    {
        value.push_str("Contract");
    }
    value
}

/// Render a Dart package source file. With wrappers disabled ABI, tuple types,
/// signatures and selectors remain available for offline encoding/decoding.
pub fn render_dart_file(ir: &ContractIr, wrappers: bool) -> String {
    let contract = namespace_name(&ir.name);
    let registry = TupleRegistry::new(ir);
    let mut out = format!(
        "// Generated by abi-typegen. Do not edit.\n// ignore_for_file: constant_identifier_names, file_names, non_constant_identifier_names, unused_element, unused_local_variable, unnecessary_non_null_assertion, unused_import\nimport 'dart:typed_data';\nimport 'package:web3dart/web3dart.dart';\nimport 'package:wallet/wallet.dart';\n\nconst String {contract}AbiJson = r'''{}''';\n\n",
        serde_json::to_string(&ir.raw_abi).unwrap_or_else(|_| "[]".into())
    );
    out.push_str(&format!(
        "final ContractAbi {contract}Abi = ContractAbi.fromJson({contract}AbiJson, '{}');\n",
        ir.name.replace('\'', "\\'")
    ));
    for (i, def) in registry.defs().iter().enumerate() {
        let tn = format!("{}{}", contract, def.name.to_upper_camel_case());
        let fields = unique_names(def.components.iter().map(|c| c.name.as_str()));
        out.push_str(&format!("\nclass {tn} {{\n"));
        for (field, c) in fields.iter().zip(&def.components) {
            out.push_str(&format!(
                "  final {} {field};\n",
                dart_type_with_internal(&c.ty, c.internal_type.as_deref(), &registry, &contract)
            ));
        }
        out.push_str(&format!("  const {tn}({{required "));
        out.push_str(
            &fields
                .iter()
                .map(|f| format!("this.{f}"))
                .collect::<Vec<_>>()
                .join(", required "),
        );
        out.push_str("});\n");
        out.push_str("  List<dynamic> toAbi() => [");
        out.push_str(
            &fields
                .iter()
                .enumerate()
                .map(|(n, field)| to_dynamic(&def.components[n].ty, field))
                .collect::<Vec<_>>()
                .join(", "),
        );
        out.push_str("];\n");
        out.push_str(&format!("  factory {tn}.fromAbi(List<dynamic> v) => {tn}("));
        out.push_str(
            &fields
                .iter()
                .enumerate()
                .map(|(n, f)| {
                    format!(
                        "{f}: {}",
                        from_dynamic_with_internal(
                            &def.components[n].ty,
                            "v[".to_owned() + &n.to_string() + "]",
                            def.components[n].internal_type.as_deref(),
                            &registry,
                            &contract
                        )
                    )
                })
                .collect::<Vec<_>>()
                .join(", "),
        );
        out.push_str(");\n}\n");
        let _ = i;
    }
    out.push_str(&format!("\nclass {contract} {{\n  {contract}(this.address) : contract = DeployedContract({contract}Abi, address);\n  final EthereumAddress address;\n  final DeployedContract contract;\n"));
    out.push_str("  String _eventTopic(dynamic type, dynamic value) { final sink = LengthTrackingByteSink(); type.encode(value, sink); return bytesToHex(sink.asBytes(), include0x: true, padToEvenLength: true); }\n");
    let mut function_name_counts = std::collections::HashMap::new();
    for f in &ir.functions {
        *function_name_counts
            .entry(method_base(&f.name))
            .or_insert(0usize) += 1;
    }
    let mut used_methods = std::collections::HashSet::new();
    let mut function_methods = Vec::new();
    for (i, f) in ir.functions.iter().enumerate() {
        let mut candidate = method_name(
            f,
            i,
            function_name_counts
                .get(&method_base(&f.name))
                .copied()
                .unwrap_or(0)
                > 1,
        );
        while !used_methods.insert(candidate.clone()) {
            candidate = format!("{candidate}ByFunction{i}");
        }
        function_methods.push(candidate);
    }
    let event_names = unique_event_names(&ir.events);
    let error_names = unique_error_names(&ir.errors);
    for (function_index, f) in ir.functions.iter().enumerate() {
        let meth = function_methods[function_index].clone();
        let args = function_arg_names(f);
        let types = f
            .inputs
            .iter()
            .map(|p| {
                dart_type_with_internal(&p.ty, p.internal_type.as_deref(), &registry, &contract)
            })
            .collect::<Vec<_>>();
        let signature = f.signature();
        let params = args
            .iter()
            .zip(&types)
            .map(|(a, t)| format!("required {t} {a}"))
            .collect::<Vec<_>>()
            .join(", ");
        let named_params = if params.is_empty() {
            String::new()
        } else {
            format!("{{{params}}}")
        };
        let comma = if params.is_empty() {
            String::new()
        } else {
            format!(", {{{params}}}")
        };
        let inlist = f
            .inputs
            .iter()
            .enumerate()
            .map(|(i, p)| to_dynamic(&p.ty, &args[i]))
            .collect::<Vec<_>>()
            .join(", ");
        let validation_method = format!("_validate{}Args", meth.to_upper_camel_case());
        out.push_str(&format!("  void {validation_method}({named_params}) {{\n"));
        for (index, input) in f.inputs.iter().enumerate() {
            emit_validate_value(
                &mut out,
                &input.ty,
                &args[index],
                &format!("'{}'", input.name.replace('\'', "\\'")),
                "    ",
                &registry,
                index,
            );
        }
        out.push_str("  }\n");
        let outtype = if f.outputs.is_empty() {
            "void".into()
        } else if f.outputs.len() == 1 {
            dart_type_with_internal(
                &f.outputs[0].ty,
                f.outputs[0].internal_type.as_deref(),
                &registry,
                &contract,
            )
        } else {
            format!("{}{}FunctionResult", contract, meth.to_upper_camel_case())
        };
        out.push_str(&format!(
            "  static const String {}Signature = '{}';\n",
            meth, signature
        ));
        out.push_str(&format!(
            "  static const String {}Selector = '0x{}';\n",
            meth,
            bytes_hex(f.selector().as_slice())
        ));
        out.push_str(&format!("  ContractFunction get _{} => {contract}Abi.functions.singleWhere((f) => f.encodeName() == {}Signature);\n",meth,meth));
        if wrappers
            && matches!(
                f.state_mutability,
                StateMutability::View | StateMutability::Pure
            )
        {
            out.push_str(&format!("  Future<{outtype}> {meth}(Web3Client client{comma}) async {{\n    {validation_method}({});\n    final r = await client.call(contract: contract, function: _{meth}, params: [{inlist}]);\n", args.iter().map(|arg| format!("{arg}: {arg}")).collect::<Vec<_>>().join(", ")));
            emit_return(&mut out, &f.outputs, &registry, &contract, "    ", &meth);
            out.push_str("  }\n");
        } else if wrappers {
            let payable_options = if matches!(f.state_mutability, StateMutability::Payable) {
                "EtherAmount? value, "
            } else {
                ""
            };
            let value_arg = if matches!(f.state_mutability, StateMutability::Payable) {
                "value: value, "
            } else {
                ""
            };
            let tx_params = if params.is_empty() {
                String::new()
            } else {
                format!(", {params}")
            };
            out.push_str(&format!("  Future<String> {meth}(Web3Client client, Credentials credentials, {{int? chainId, {payable_options}int? maxGas, EtherAmount? gasPrice{tx_params}}}) {{ {validation_method}({}); return client.sendTransaction(credentials, Transaction.callContract(contract: contract, function: _{meth}, parameters: [{inlist}], {value_arg}maxGas: maxGas, gasPrice: gasPrice), chainId: chainId); }}\n", args.iter().map(|arg| format!("{arg}: {arg}")).collect::<Vec<_>>().join(", ")));
        }
        out.push_str(&format!(
            "  Uint8List {}Call({named_params}) {{ {validation_method}({}); return _{}.encodeCall([{inlist}]); }}\n",
            meth, args.iter().map(|arg| format!("{arg}: {arg}")).collect::<Vec<_>>().join(", "), meth
        ));
        if !f.outputs.is_empty() {
            out.push_str(&format!("  {outtype} decode{}Result(String data) {{ final r = _{}.decodeReturnValues(data);\n",meth.to_upper_camel_case(),meth));
            emit_return(&mut out, &f.outputs, &registry, &contract, "    ", &meth);
            out.push_str("  }\n");
        }
    }
    for (error_index, e) in ir.errors.iter().enumerate() {
        let name = error_names[error_index].clone();
        let abi = error_as_function_json(ir, &e.signature());
        out.push_str(&format!("  ContractFunction get _{name}Error => ContractAbi.fromJson(r'''{abi}''', '{contract}{name}Error').functions.single;\n"));
        let fields = unique_names(e.inputs.iter().map(|p| p.name.as_str()));
        let type_name = format!("{contract}Error{name}");
        out.push_str(&format!("  {type_name} decode{name}Error(String data) {{\n    if (!data.toLowerCase().startsWith('0x{}')) throw FormatException('error selector mismatch');\n    final values = _{name}Error.decodeReturnValues('0x${{data.substring(10)}}');\n    return {type_name}(\n", bytes_hex(e.selector().as_slice())));
        for (i, p) in e.inputs.iter().enumerate() {
            out.push_str(&format!(
                "      {}: {},\n",
                fields[i],
                from_dynamic_with_internal(
                    &p.ty,
                    format!("values[{i}]"),
                    p.internal_type.as_deref(),
                    &registry,
                    &contract
                )
            ));
        }
        out.push_str("    );\n  }\n");
    }
    if wrappers {
        out.push_str("  // Event lookup uses the canonical signature, so overloaded events remain distinct.\n");
        for (event_index, e) in ir.events.iter().enumerate() {
            let n = event_names[event_index].clone();
            let fields = unique_names(e.inputs.iter().map(|p| p.name.as_str()));
            let event_accessor = n.to_lower_camel_case();
            out.push_str(&format!(
                "  static const String {event_accessor}Topic0 = '0x{}';\n",
                bytes_hex(e.topic0().as_slice())
            ));
            out.push_str(&format!("  ContractEvent get {}Event => contract.events.singleWhere((e) => e.stringSignature == '{}');\n",n.to_lower_camel_case(),e.signature()));
            let topic_offset = if e.anonymous { 0 } else { 1 };
            let expected_topics = topic_offset + e.inputs.iter().filter(|p| p.indexed).count();
            let topic_count_guard = if expected_topics == 0 {
                "topics.isNotEmpty".to_owned()
            } else {
                format!("topics.length != {expected_topics}")
            };
            out.push_str(&format!("  {contract}{n}Event decode{n}Event(List<String?> topics, String data) {{\n    if ({topic_count_guard}) throw FormatException('event topic count mismatch');\n"));
            if !e.anonymous {
                out.push_str(&format!("    if (topics[0] != {event_accessor}Topic0) throw FormatException('event topic0 mismatch');\n"));
            }
            out.push_str(&format!("    final values = {}Event.decodeResults(topics, data);\n    return {contract}{n}Event(\n",n.to_lower_camel_case()));
            let mut indexed_topic = if e.anonymous { 0 } else { 1 };
            let mut decoded_value_index = 0usize;
            for (i, p) in e.inputs.iter().enumerate() {
                let reference = p.indexed
                    && matches!(
                        p.ty,
                        SolType::Bytes
                            | SolType::StringType
                            | SolType::Array(_)
                            | SolType::FixedArray(_, _)
                            | SolType::Tuple(_)
                    );
                let value = if reference {
                    let topic = indexed_topic;
                    indexed_topic += 1;
                    if sdk_includes_indexed_value(&p.ty) {
                        decoded_value_index += 1;
                    }
                    format!("hexToBytes(topics[{topic}]!)")
                } else if p.indexed {
                    indexed_topic += 1;
                    let index = decoded_value_index;
                    decoded_value_index += 1;
                    from_dynamic_with_internal(
                        &p.ty,
                        format!("values[{index}]"),
                        p.internal_type.as_deref(),
                        &registry,
                        &contract,
                    )
                } else {
                    let index = decoded_value_index;
                    decoded_value_index += 1;
                    from_dynamic_with_internal(
                        &p.ty,
                        format!("values[{index}]"),
                        p.internal_type.as_deref(),
                        &registry,
                        &contract,
                    )
                };
                out.push_str(&format!("      {}: {},\n", fields[i], value));
            }
            out.push_str("    );\n  }\n");
            let indexed_inputs = e
                .inputs
                .iter()
                .enumerate()
                .filter(|(_, p)| p.indexed)
                .collect::<Vec<_>>();
            let filter_params = indexed_inputs
                .iter()
                .map(|(i, p)| {
                    let ty = if matches!(
                        p.ty,
                        SolType::Bytes
                            | SolType::StringType
                            | SolType::Array(_)
                            | SolType::FixedArray(_, _)
                            | SolType::Tuple(_)
                    ) {
                        "Uint8List".to_owned()
                    } else {
                        dart_type_with_internal(
                            &p.ty,
                            p.internal_type.as_deref(),
                            &registry,
                            &contract,
                        )
                    };
                    format!("{ty}? {}", fields[*i])
                })
                .collect::<Vec<_>>();
            out.push_str(&format!("  Future<List<FilterEvent>> get{n}Logs(Web3Client client, {{BlockNum? fromBlock, BlockNum? toBlock{}}}) async {{\n", if filter_params.is_empty() { String::new() } else { format!(", {}", filter_params.join(", ")) }));
            let initial_filter = if e.anonymous {
                "[]".to_owned()
            } else {
                format!("[[{event_accessor}Topic0]]")
            };
            out.push_str(&format!(
                "    final topics = <List<String?>>{initial_filter};\n"
            ));
            for (i, p) in &indexed_inputs {
                let field = &fields[*i];
                let encoded = if matches!(
                    p.ty,
                    SolType::Bytes
                        | SolType::StringType
                        | SolType::Array(_)
                        | SolType::FixedArray(_, _)
                        | SolType::Tuple(_)
                ) {
                    format!("bytesToHex({field}!, include0x: true, padToEvenLength: true)")
                } else {
                    format!(
                        "_eventTopic({event_accessor}Event.components[{i}].parameter.type, {field}!)"
                    )
                };
                out.push_str(&format!(
                    "    topics.add({field} == null ? <String?>[null] : <String?>[{encoded}]);\n"
                ));
            }
            out.push_str("    return client.getLogs(FilterOptions(address: address, fromBlock: fromBlock, toBlock: toBlock, topics: topics));\n  }\n");
        }
    }
    out.push_str("}\n");
    // Named return value types make multiple outputs usable without positional dynamic values.
    for (i, f) in ir.functions.iter().enumerate() {
        if f.outputs.len() > 1 {
            let n = format!(
                "{}{}FunctionResult",
                contract,
                function_methods[i].to_upper_camel_case()
            );
            out.push_str(&format!("\nclass {n} {{\n"));
            let fields = unique_names(f.outputs.iter().map(|p| p.name.as_str()));
            for (field, p) in fields.iter().zip(&f.outputs) {
                out.push_str(&format!(
                    "  final {} {field};\n",
                    dart_type_with_internal(
                        &p.ty,
                        p.internal_type.as_deref(),
                        &registry,
                        &contract
                    )
                ));
            }
            out.push_str(&format!("  const {n}({{required "));
            out.push_str(
                &fields
                    .iter()
                    .map(|field| format!("this.{field}"))
                    .collect::<Vec<_>>()
                    .join(", required "),
            );
            out.push_str("});\n}\n");
        }
    }
    for (event_index, e) in ir.events.iter().enumerate() {
        let n = format!("{contract}{}Event", event_names[event_index]);
        let fields = unique_names(e.inputs.iter().map(|p| p.name.as_str()));
        out.push_str(&format!("\nclass {n} {{\n"));
        for (field, p) in fields.iter().zip(&e.inputs) {
            let ty = if p.indexed
                && matches!(
                    p.ty,
                    SolType::Bytes
                        | SolType::StringType
                        | SolType::Array(_)
                        | SolType::FixedArray(_, _)
                        | SolType::Tuple(_)
                ) {
                "Uint8List".into()
            } else {
                dart_type_with_internal(&p.ty, p.internal_type.as_deref(), &registry, &contract)
            };
            out.push_str(&format!("  final {ty} {field};\n"));
        }
        out.push_str(&format!("  const {n}({{required "));
        out.push_str(
            &fields
                .iter()
                .map(|f| format!("this.{f}"))
                .collect::<Vec<_>>()
                .join(", required "),
        );
        out.push_str("});\n}\n");
    }
    for (error_index, e) in ir.errors.iter().enumerate() {
        let n = error_names[error_index].clone();
        out.push_str(&format!("\n/// Canonical signature and selector for the declared custom error.\nconst String {contract}{n}ErrorSignature = '{}';\nconst String {contract}{n}ErrorSelector = '0x{}';\n",e.signature(),bytes_hex(e.selector().as_slice())));
        let type_name = format!("{contract}Error{n}");
        let fields = unique_names(e.inputs.iter().map(|p| p.name.as_str()));
        out.push_str(&format!("\nclass {type_name} {{\n"));
        for (field, p) in fields.iter().zip(&e.inputs) {
            out.push_str(&format!(
                "  final {} {field};\n",
                dart_type_with_internal(&p.ty, p.internal_type.as_deref(), &registry, &contract)
            ));
        }
        if fields.is_empty() {
            out.push_str(&format!("  const {type_name}();\n}}\n"));
        } else {
            out.push_str(&format!("  const {type_name}({{required "));
            out.push_str(
                &fields
                    .iter()
                    .map(|field| format!("this.{field}"))
                    .collect::<Vec<_>>()
                    .join(", required "),
            );
            out.push_str("});\n}\n");
        }
    }
    out
}

fn safe_name(s: &str, i: usize) -> String {
    let mut n = if s.trim().is_empty() {
        format!("value{}", i)
    } else {
        s.to_lower_camel_case()
    };
    if n.is_empty()
        || !n
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_' || c == '$')
    {
        n = format!("value{}", i);
    }
    if [
        "class", "function", "String", "int", "bool", "void", "import", "switch", "default",
        "return", "new", "this", "super", "final", "var", "const", "dynamic", "null", "true",
        "false", "required", "await", "async", "toAbi", "fromAbi",
    ]
    .contains(&n.as_str())
    {
        format!("{n}_")
    } else if n.is_empty() {
        format!("value{}", i)
    } else {
        n
    }
}

fn method_name(f: &abi_typegen_core::types::AbiFunction, index: usize, overloaded: bool) -> String {
    let base = method_base(&f.name);
    if !overloaded {
        return base;
    }
    let suffix = f
        .inputs
        .iter()
        .map(|p| p.ty.canonical())
        .collect::<Vec<_>>()
        .join("_")
        .to_upper_camel_case();
    if suffix.is_empty() {
        format!("{base}ByFunction{index}")
    } else {
        format!("{base}By{suffix}")
    }
}
fn method_base(name: &str) -> String {
    let base = safe_name(name, 0).to_lower_camel_case();
    if [
        "address",
        "contract",
        "toString",
        "hashCode",
        "runtimeType",
        "noSuchMethod",
        "_eventTopic",
    ]
    .contains(&base.as_str())
    {
        format!("{base}Function")
    } else {
        base
    }
}

fn function_arg_names(f: &abi_typegen_core::types::AbiFunction) -> Vec<String> {
    let reserved = [
        "client",
        "credentials",
        "chainId",
        "maxGas",
        "gasPrice",
        "value",
        "address",
        "contract",
        "this",
        "super",
    ];
    let mut used = std::collections::HashSet::new();
    f.inputs
        .iter()
        .enumerate()
        .map(|(i, p)| {
            let mut name = safe_name(&p.name, i);
            if reserved.contains(&name.as_str()) {
                name.push('_');
            }
            let base = name.clone();
            let mut suffix = 2;
            while !used.insert(name.clone()) {
                name = format!("{base}{suffix}");
                suffix += 1;
            }
            name
        })
        .collect()
}

fn unique_event_names(events: &[abi_typegen_core::types::AbiEvent]) -> Vec<String> {
    let mut counts = std::collections::HashMap::new();
    for event in events {
        *counts
            .entry(event.name.to_upper_camel_case())
            .or_insert(0usize) += 1;
    }
    let mut used = std::collections::HashSet::new();
    events
        .iter()
        .enumerate()
        .map(|(i, event)| {
            let mut name = event.name.to_upper_camel_case();
            if counts.get(&name).copied().unwrap_or(0) > 1 {
                let suffix = event
                    .inputs
                    .iter()
                    .map(|p| p.ty.canonical())
                    .collect::<Vec<_>>()
                    .join("_")
                    .to_upper_camel_case();
                name = format!(
                    "{name}By{}",
                    if suffix.is_empty() {
                        format!("Event{i}")
                    } else {
                        suffix
                    }
                );
            }
            while !used.insert(name.clone()) {
                name = format!("{name}Event{i}");
            }
            name
        })
        .collect()
}

fn unique_error_names(errors: &[abi_typegen_core::types::AbiError]) -> Vec<String> {
    let mut counts = std::collections::HashMap::new();
    for error in errors {
        *counts
            .entry(error.name.to_upper_camel_case())
            .or_insert(0usize) += 1;
    }
    let mut used = std::collections::HashSet::new();
    errors
        .iter()
        .enumerate()
        .map(|(i, error)| {
            let mut name = error.name.to_upper_camel_case();
            if counts.get(&name).copied().unwrap_or(0) > 1 {
                let suffix = error
                    .inputs
                    .iter()
                    .map(|p| p.ty.canonical())
                    .collect::<Vec<_>>()
                    .join("_")
                    .to_upper_camel_case();
                name = format!(
                    "{name}By{}",
                    if suffix.is_empty() {
                        format!("Error{i}")
                    } else {
                        suffix
                    }
                );
            }
            while !used.insert(name.clone()) {
                name = format!("{name}Error{i}");
            }
            name
        })
        .collect()
}
fn dart_type(t: &SolType, r: &TupleRegistry, c: &str) -> String {
    match t {
        SolType::Uint(_) | SolType::Int(_) => "BigInt".into(),
        SolType::Bool => "bool".into(),
        SolType::Address => "EthereumAddress".into(),
        SolType::Bytes | SolType::BytesN(_) => "Uint8List".into(),
        SolType::StringType => "String".into(),
        SolType::Array(x) => format!("List<{}>", dart_type(x, r, c)),
        SolType::FixedArray(x, _) => format!("List<{}>", dart_type(x, r, c)),
        SolType::Tuple(cs) => format!(
            "{c}{}",
            r.defs()
                .iter()
                .find(|d| d.components == *cs)
                .map(|d| d.name.as_str())
                .unwrap_or("Tuple")
                .to_upper_camel_case()
        ),
    }
}

fn dart_type_with_internal(
    t: &SolType,
    internal_type: Option<&str>,
    registry: &TupleRegistry,
    contract: &str,
) -> String {
    match t {
        SolType::Tuple(components) => format!(
            "{contract}{}",
            registry
                .name(components, internal_type)
                .to_upper_camel_case()
        ),
        SolType::Array(inner) => format!(
            "List<{}>",
            dart_type_with_internal(inner, internal_type, registry, contract)
        ),
        SolType::FixedArray(inner, _) => format!(
            "List<{}>",
            dart_type_with_internal(inner, internal_type, registry, contract)
        ),
        _ => dart_type(t, registry, contract),
    }
}
fn to_dynamic(t: &SolType, n: &str) -> String {
    match t {
        SolType::Tuple(_) => format!("{n}.toAbi()"),
        SolType::Array(x) | SolType::FixedArray(x, _) => {
            format!("{n}.map((e) => {}).toList()", to_dynamic(x, "e"))
        }
        _ => n.into(),
    }
}

fn sdk_includes_indexed_value(ty: &SolType) -> bool {
    static_encoding_length(ty).is_some_and(|length| length <= 32)
}

fn static_encoding_length(ty: &SolType) -> Option<usize> {
    match ty {
        SolType::Bytes | SolType::StringType | SolType::Array(_) => None,
        SolType::FixedArray(inner, length) => static_encoding_length(inner)?.checked_mul(*length),
        SolType::Tuple(components) => components.iter().try_fold(0usize, |total, component| {
            total.checked_add(static_encoding_length(&component.ty)?)
        }),
        _ => Some(32),
    }
}

#[allow(clippy::too_many_arguments)]
fn emit_validate_value(
    out: &mut String,
    ty: &SolType,
    expr: &str,
    label: &str,
    indent: &str,
    registry: &TupleRegistry,
    depth: usize,
) {
    match ty {
        SolType::Uint(bits) => out.push_str(&format!(
            "{indent}if ({expr}.isNegative || {expr}.bitLength > {bits}) throw RangeError(\"unsigned {bits}-bit value out of range for {label}\");\n"
        )),
        SolType::Int(bits) => out.push_str(&format!(
            "{indent}if ({expr} < -(BigInt.one << {}) || {expr} > (BigInt.one << {}) - BigInt.one) throw RangeError(\"signed {bits}-bit value out of range for {label}\");\n",
            bits - 1,
            bits - 1
        )),
        SolType::BytesN(size) => out.push_str(&format!(
            "{indent}if ({expr}.length != {size}) throw ArgumentError.value({expr}, {label}, 'expected exactly {size} bytes');\n"
        )),
        SolType::Array(inner) | SolType::FixedArray(inner, _) => {
            if let SolType::FixedArray(_, length) = ty {
                out.push_str(&format!(
                    "{indent}if ({expr}.length != {length}) throw ArgumentError.value({expr}, {label}, 'expected exactly {length} elements');\n"
                ));
            }
            let item = format!("abiItem{depth}");
            out.push_str(&format!("{indent}for (final {item} in {expr}) {{\n"));
            emit_validate_value(
                out,
                inner,
                &item,
                label,
                &format!("{indent}  "),
                registry,
                depth + 1,
            );
            out.push_str(&format!("{indent}}}\n"));
        }
        SolType::Tuple(components) => {
            let def = registry.defs().iter().find(|d| d.components == *components);
            if let Some(def) = def {
                let fields = unique_names(def.components.iter().map(|c| c.name.as_str()));
                for (index, component) in components.iter().enumerate() {
                    emit_validate_value(
                        out,
                        &component.ty,
                        &format!("{expr}.{}", fields[index]),
                        label,
                        indent,
                        registry,
                        depth + index + 1,
                    );
                }
            }
        }
        _ => {}
    }
}
fn from_dynamic_with_internal(
    t: &SolType,
    value: String,
    internal_type: Option<&str>,
    registry: &TupleRegistry,
    contract: &str,
) -> String {
    match t {
        SolType::Tuple(components) => format!(
            "{contract}{}.fromAbi({value} as List<dynamic>)",
            registry
                .name(components, internal_type)
                .to_upper_camel_case()
        ),
        SolType::Array(inner) | SolType::FixedArray(inner, _) => format!(
            "({value} as List<dynamic>).map((e) => {}).toList()",
            from_dynamic_with_internal(inner, "e".into(), internal_type, registry, contract)
        ),
        _ => format!(
            "{value} as {}",
            dart_type_with_internal(t, internal_type, registry, contract)
        ),
    }
}
fn emit_return(
    o: &mut String,
    outputs: &[abi_typegen_core::types::AbiParam],
    r: &TupleRegistry,
    c: &str,
    indent: &str,
    fn_name: &str,
) {
    if outputs.is_empty() {
        o.push_str(&format!("{indent}return;\n"));
    } else if outputs.len() == 1 {
        o.push_str(&format!(
            "{indent}return {};\n",
            from_dynamic_with_internal(
                &outputs[0].ty,
                "r[0]".into(),
                outputs[0].internal_type.as_deref(),
                r,
                c,
            )
        ));
    } else {
        o.push_str(&format!(
            "{indent}return {c}{}FunctionResult(\n",
            fn_name.to_upper_camel_case()
        ));
        for (i, p) in outputs.iter().enumerate() {
            o.push_str(&format!(
                "{indent}  {}: {},\n",
                safe_name(&p.name, i),
                from_dynamic_with_internal(
                    &p.ty,
                    format!("r[{i}]"),
                    p.internal_type.as_deref(),
                    r,
                    c,
                )
            ));
        }
        o.push_str(&format!("{indent});\n"));
    }
}
fn unique_names<'a>(names: impl Iterator<Item = &'a str>) -> Vec<String> {
    let mut used = std::collections::HashSet::new();
    names
        .enumerate()
        .map(|(i, n)| {
            let base = safe_name(n, i);
            let mut name = base.clone();
            let mut suffix = 2;
            while !used.insert(name.clone()) {
                name = format!("{base}{suffix}");
                suffix += 1;
            }
            name
        })
        .collect()
}
fn bytes_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn error_as_function_json(ir: &ContractIr, signature: &str) -> String {
    let entry = ir.raw_abi.as_array().and_then(|entries| entries.iter().find(|entry| {
        entry.get("type").and_then(serde_json::Value::as_str) == Some("error")
            && raw_abi_signature(entry).as_deref() == Some(signature)
    })).cloned().unwrap_or_else(|| serde_json::json!({"type":"function","name":"UnknownError","inputs":[],"outputs":[],"stateMutability":"view"}));
    let mut entry = entry;
    if let Some(object) = entry.as_object_mut() {
        object.insert("type".into(), serde_json::Value::String("function".into()));
        let error_inputs = object
            .get("inputs")
            .cloned()
            .unwrap_or_else(|| serde_json::Value::Array(Vec::new()));
        object.insert("outputs".into(), error_inputs);
        object.insert(
            "stateMutability".into(),
            serde_json::Value::String("view".into()),
        );
    }
    serde_json::to_string(&vec![entry]).unwrap_or_else(|_| "[]".into())
}

fn raw_abi_signature(entry: &serde_json::Value) -> Option<String> {
    let name = entry.get("name")?.as_str()?;
    let inputs = entry.get("inputs")?.as_array()?;
    let types = inputs
        .iter()
        .map(raw_abi_type)
        .collect::<Option<Vec<_>>>()?;
    Some(format!("{name}({})", types.join(",")))
}

fn raw_abi_type(param: &serde_json::Value) -> Option<String> {
    let ty = param.get("type")?.as_str()?;
    if !ty.starts_with("tuple") {
        return Some(ty.to_owned());
    }
    let suffix = &ty[5..];
    let components = param.get("components")?.as_array()?;
    let fields = components
        .iter()
        .map(raw_abi_type)
        .collect::<Option<Vec<_>>>()?;
    Some(format!("({}){suffix}", fields.join(",")))
}
