use super::ethers_common::{function_signature, method_names};
use crate::type_mapper::safe_param_name;
use abi_typegen_core::types::{
    AbiEvent, AbiFunction, AbiParam, ContractIr, SolType, StateMutability,
};

/// Generates `<ContractName>.ethers.ts` — a typed ethers v6 contract interface.
pub fn render_ethers_file(ir: &ContractIr) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by abi-typegen. Do not edit manually.\n");
    out.push_str("import { Contract, type AddressLike, type BigNumberish, type BytesLike, type ContractRunner, type ContractTransactionResponse, type EventFilter } from 'ethers';\n");
    out.push_str(&format!(
        "import {{ {}Abi }} from './{}.abi.js';\n\n",
        ir.name, ir.name
    ));

    // Interface — standalone (not extending Contract) to avoid index signature
    // conflicts with ethers v6's BaseContractMethod constraint.
    out.push_str(&format!("export interface {}Contract {{\n", ir.name));

    let names = method_names(&ir.functions);
    for (function, name) in ir.functions.iter().zip(&names) {
        out.push_str(&render_function_sig(name, function));
    }

    // Event filters
    if !ir.events.is_empty() {
        out.push_str("  filters: {\n");
        for event in &ir.events {
            out.push_str(&render_event_filter(event));
        }
        out.push_str("  };\n");
    }

    out.push_str("}\n\n");

    // connect factory function
    out.push_str(&format!(
        "export function connect{}(address: string, runner: ContractRunner): {}Contract {{\n",
        ir.name, ir.name
    ));
    out.push_str(&format!(
        "  const contract = new Contract(address, {}Abi, runner);\n",
        ir.name
    ));
    let aliases: Vec<_> = ir
        .functions
        .iter()
        .zip(&names)
        .filter(|(function, name)| function.name != **name)
        .collect();
    if !aliases.is_empty() {
        out.push_str("  Object.assign(contract, {\n");
        for (function, name) in aliases {
            let signature = serde_json::to_string(&function_signature(function))
                .expect("function signatures serialize as JSON strings");
            out.push_str(&format!(
                "    {}: contract.getFunction({}),\n",
                name, signature
            ));
        }
        out.push_str("  });\n");
    }
    out.push_str(&format!(
        "  return contract as unknown as {}Contract;\n",
        ir.name
    ));
    out.push_str("}\n");

    out
}

fn render_function_sig(method_name: &str, f: &AbiFunction) -> String {
    let params = f
        .inputs
        .iter()
        .enumerate()
        .map(|(i, p)| {
            format!(
                "{}: {}",
                safe_param_name(&p.name, i),
                sol_type_to_ethers_input(&p.ty)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");

    let return_type = match f.state_mutability {
        StateMutability::Pure | StateMutability::View => {
            let out_types: Vec<String> = f
                .outputs
                .iter()
                .map(|p| sol_type_to_ethers_output(&p.ty))
                .collect();
            match out_types.len() {
                0 => "Promise<void>".into(),
                1 => format!("Promise<{}>", out_types[0]),
                _ => render_multi_output_type(&f.outputs),
            }
        }
        _ => "Promise<ContractTransactionResponse>".into(),
    };

    format!("  {}({}): {};\n", method_name, params, return_type)
}

fn render_event_filter(event: &AbiEvent) -> String {
    let params = event
        .inputs
        .iter()
        .enumerate()
        .take(
            event
                .inputs
                .iter()
                .rposition(|param| param.indexed)
                .map_or(0, |index| index + 1),
        )
        .map(|(i, p)| {
            if !p.indexed {
                return format!("{}?: null", safe_param_name(&p.name, i));
            }
            format!(
                "{}?: {} | null",
                safe_param_name(&p.name, i),
                sol_type_to_ethers_input(&p.ty)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");

    format!("    {}({}): EventFilter;\n", event.name, params)
}

fn sol_type_to_ethers_input(ty: &SolType) -> String {
    match ty {
        SolType::Bool => "boolean".into(),
        SolType::StringType => "string".into(),
        SolType::Uint(_) | SolType::Int(_) => "BigNumberish".into(),
        SolType::Address => "AddressLike".into(),
        SolType::Bytes | SolType::BytesN(_) => "BytesLike".into(),
        SolType::Array(inner) => render_array_type(&sol_type_to_ethers_input(inner)),
        SolType::FixedArray(inner, n) => {
            render_tuple_type(std::iter::repeat_with(|| sol_type_to_ethers_input(inner)).take(*n))
        }
        SolType::Tuple(components) => {
            let fields: Vec<String> = components
                .iter()
                .enumerate()
                .map(|(i, c)| {
                    format!(
                        "{}: {}",
                        safe_param_name(&c.name, i),
                        sol_type_to_ethers_input(&c.ty)
                    )
                })
                .collect();
            format!("{{ {} }}", fields.join("; "))
        }
    }
}

fn sol_type_to_ethers_output(ty: &SolType) -> String {
    match ty {
        SolType::Bool => "boolean".into(),
        SolType::StringType => "string".into(),
        SolType::Uint(_) | SolType::Int(_) => "bigint".into(),
        SolType::Address => "string".into(),
        SolType::Bytes | SolType::BytesN(_) => "string".into(),
        SolType::Array(inner) => render_array_type(&sol_type_to_ethers_output(inner)),
        SolType::FixedArray(inner, n) => {
            render_tuple_type(std::iter::repeat_with(|| sol_type_to_ethers_output(inner)).take(*n))
        }
        SolType::Tuple(components) => {
            let item_types = components.iter().map(|component| {
                let ty = sol_type_to_ethers_output(&component.ty);
                let name = component.name.as_str();
                (name, ty)
            });
            render_tuple_output_type(item_types)
        }
    }
}

fn render_multi_output_type(outputs: &[AbiParam]) -> String {
    let item_types = outputs.iter().map(|param| {
        let ty = sol_type_to_ethers_output(&param.ty);
        let name = param.name.as_str();
        (name, ty)
    });
    format!("Promise<{}>", render_tuple_output_type(item_types))
}

fn render_tuple_output_type<'a>(items: impl IntoIterator<Item = (&'a str, String)>) -> String {
    let items: Vec<(&str, String)> = items.into_iter().collect();
    let tuple = render_tuple_type(items.iter().map(|(_, ty)| ty.clone()));
    if items.iter().all(|(name, _)| name.is_empty()) {
        return tuple;
    }

    let fields: Vec<String> = items
        .iter()
        .enumerate()
        .filter_map(|(i, (name, ty))| {
            let name = safe_tuple_field_name(name, i)?;
            Some(format!("{}: {}", name, ty))
        })
        .collect();
    if fields.is_empty() {
        tuple
    } else {
        format!("{} & {{ {} }}", tuple, fields.join("; "))
    }
}

fn render_tuple_type(items: impl IntoIterator<Item = String>) -> String {
    format!("[{}]", items.into_iter().collect::<Vec<_>>().join(", "))
}

fn render_array_type(inner: &str) -> String {
    if inner.contains(" & ") {
        format!("({})[]", inner)
    } else {
        format!("{}[]", inner)
    }
}

fn safe_tuple_field_name(name: &str, index: usize) -> Option<String> {
    if name.is_empty() {
        return None;
    }

    let name = safe_param_name(name, index);
    if is_tuple_property_name(&name) {
        None
    } else {
        Some(name)
    }
}

fn is_tuple_property_name(name: &str) -> bool {
    matches!(
        name,
        "length"
            | "toString"
            | "toLocaleString"
            | "pop"
            | "push"
            | "concat"
            | "join"
            | "reverse"
            | "shift"
            | "slice"
            | "sort"
            | "splice"
            | "unshift"
            | "indexOf"
            | "lastIndexOf"
            | "every"
            | "some"
            | "forEach"
            | "map"
            | "filter"
            | "reduce"
            | "reduceRight"
            | "find"
            | "findIndex"
            | "entries"
            | "keys"
            | "values"
            | "includes"
            | "flatMap"
            | "flat"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;

    fn erc20() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/erc20.json"),
        )
        .unwrap();
        parse_artifact("ERC20", &json).unwrap()
    }

    fn vault() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/vault.json"),
        )
        .unwrap();
        parse_artifact("Vault", &json).unwrap()
    }

    #[test]
    fn overload_aliases_are_bound_to_runtime_methods() {
        let out = render_ethers_file(&vault());
        assert!(
            out.contains(r#"contract.getFunction("deposit(uint256)")"#),
            "{out}"
        );
    }

    #[test]
    fn filter_preserves_non_indexed_slots_before_indexed_fields() {
        let ir = abi_typegen_core::parser::parse_artifact(
            "Mixed",
            r#"{"abi":[{"type":"event","name":"Moved","inputs":[
            {"name":"amount","type":"uint256","indexed":false},
            {"name":"from","type":"address","indexed":true},
            {"name":"memo","type":"bytes32","indexed":false},
            {"name":"to","type":"address","indexed":true},
            {"name":"ignored","type":"bool","indexed":false}
        ]}]}"#,
        )
        .unwrap();
        let out = render_ethers_file(&ir);
        assert!(out.contains("Moved(amount?: null, from?: AddressLike | null, memo?: null, to?: AddressLike | null)"), "{out}");
    }

    #[test]
    fn contains_imports() {
        let out = render_ethers_file(&erc20());
        assert!(out.contains("import { Contract, type AddressLike, type BigNumberish"));
        assert!(out.contains("import { ERC20Abi } from './ERC20.abi.js'"));
    }

    #[test]
    fn exports_interface() {
        let out = render_ethers_file(&erc20());
        assert!(out.contains("export interface ERC20Contract {"));
    }

    #[test]
    fn view_fn_returns_promise() {
        let out = render_ethers_file(&erc20());
        assert!(out.contains("balanceOf(account: AddressLike): Promise<bigint>;"));
    }

    #[test]
    fn write_fn_returns_transaction_response() {
        let out = render_ethers_file(&erc20());
        assert!(out.contains(
            "transfer(to: AddressLike, amount: BigNumberish): Promise<ContractTransactionResponse>;"
        ));
    }

    #[test]
    fn event_filters_block() {
        let out = render_ethers_file(&erc20());
        assert!(out.contains("filters: {"));
        assert!(out.contains(
            "Transfer(from?: AddressLike | null, to?: AddressLike | null): EventFilter;"
        ));
    }

    #[test]
    fn connect_factory_fn() {
        let out = render_ethers_file(&erc20());
        assert!(out.contains(
            "export function connectERC20(address: string, runner: ContractRunner): ERC20Contract {"
        ));
    }

    #[test]
    fn vault_overloads_get_signature_based_names() {
        let out = render_ethers_file(&vault());
        assert!(
            out.contains("depositUint256("),
            "Expected depositUint for deposit(uint256), got:\n{out}"
        );
        assert!(
            out.contains("depositUint256Address("),
            "Expected depositUint256Address for deposit(uint256, address), got:\n{out}"
        );
        // Old numbered names should not appear
        assert!(
            !out.contains("deposit_0("),
            "Old numbered overload name should not appear, got:\n{out}"
        );
        assert!(
            !out.contains("deposit_1("),
            "Old numbered overload name should not appear, got:\n{out}"
        );
    }

    #[test]
    fn vault_tuple_output_is_inline_type() {
        let out = render_ethers_file(&vault());
        assert!(out.contains("getPosition(user: AddressLike): Promise<["));
        assert!(out.contains("shares: bigint"));
        assert!(out.contains("depositedAt: bigint"));
    }

    #[test]
    fn vault_fixed_array_output_is_tuple_type() {
        let out = render_ethers_file(&vault());
        assert!(
            out.contains("getMatrix(): Promise<[bigint, bigint, bigint]>;"),
            "Expected fixed array output to match TypeChain tuple precision, got:\n{out}"
        );
    }

    // --- Hand-built IR tests below ---

    use abi_typegen_core::types::{AbiEventParam, AbiParam, SolType, TupleComponent};

    #[test]
    fn tuple_output_omits_names_that_collide_with_tuple_properties() {
        let ty = SolType::Tuple(vec![
            TupleComponent {
                name: "length".into(),
                ty: SolType::Uint(256),
                internal_type: None,
            },
            TupleComponent {
                name: "value".into(),
                ty: SolType::StringType,
                internal_type: None,
            },
        ]);
        assert_eq!(
            sol_type_to_ethers_output(&ty),
            "[bigint, string] & { value: string }"
        );
    }

    /// Helper to build a minimal ContractIr with the given functions and events.
    fn make_ir(name: &str, functions: Vec<AbiFunction>, events: Vec<AbiEvent>) -> ContractIr {
        ContractIr {
            name: name.to_string(),
            constructor: None,
            functions,
            events,
            errors: vec![],
            has_fallback: false,
            has_receive: false,
            natspec: None,
            raw_abi: serde_json::Value::Array(vec![]),
        }
    }

    #[test]
    fn view_fn_returning_void() {
        let ir = make_ir(
            "Minimal",
            vec![AbiFunction {
                name: "ping".to_string(),
                inputs: vec![],
                outputs: vec![],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("ping(): Promise<void>;"),
            "Expected `Promise<void>` for view fn with no outputs, got:\n{out}"
        );
    }

    #[test]
    fn view_fn_returning_multiple_outputs() {
        let ir = make_ir(
            "Multi",
            vec![AbiFunction {
                name: "getPair".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "a".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "b".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("getPair(): Promise<[string, bigint] & { a: string; b: bigint }>;"),
            "Expected tuple plus named fields for multi-output view fn with named outputs, got:\n{out}"
        );
    }

    #[test]
    fn contract_with_no_events_omits_filters() {
        let ir = make_ir(
            "NoEvents",
            vec![AbiFunction {
                name: "doSomething".to_string(),
                inputs: vec![],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            !out.contains("filters"),
            "Expected no `filters` block when there are no events, got:\n{out}"
        );
    }

    #[test]
    fn contract_with_no_functions() {
        let ir = make_ir(
            "EventOnly",
            vec![],
            vec![AbiEvent {
                name: "Ping".to_string(),
                inputs: vec![AbiEventParam {
                    name: "sender".to_string(),
                    ty: SolType::Address,
                    indexed: true,
                    internal_type: None,
                }],
                anonymous: false,
                natspec: None,
            }],
        );
        let out = render_ethers_file(&ir);
        // The interface should still contain the filters block
        assert!(
            out.contains("filters: {"),
            "Expected `filters` block even with no functions, got:\n{out}"
        );
        assert!(
            out.contains("Ping(sender?: AddressLike | null): EventFilter;"),
            "Expected Ping filter, got:\n{out}"
        );
        // There should be no function signatures (lines starting with two spaces
        // that look like function declarations, but filters block is fine).
        // Specifically, no line matching `  someName(` outside the filters block.
        let interface_start = out.find("Contract {").expect("interface");
        let filters_start = out.find("filters: {").expect("filters");
        let between = &out[interface_start..filters_start];
        // Between the opening brace and filters there should only be whitespace/newlines
        let trimmed = between
            .trim_start_matches(|c: char| c != '{')
            .trim_start_matches('{')
            .trim();
        assert!(
            trimmed.is_empty(),
            "Expected no function signatures before filters block, got:\n{between}"
        );
    }

    #[test]
    fn event_with_only_non_indexed_params() {
        let ir = make_ir(
            "LogOnly",
            vec![],
            vec![AbiEvent {
                name: "DataStored".to_string(),
                inputs: vec![
                    AbiEventParam {
                        name: "key".to_string(),
                        ty: SolType::Uint(256),
                        indexed: false,
                        internal_type: None,
                    },
                    AbiEventParam {
                        name: "value".to_string(),
                        ty: SolType::Uint(256),
                        indexed: false,
                        internal_type: None,
                    },
                ],
                anonymous: false,
                natspec: None,
            }],
        );
        let out = render_ethers_file(&ir);
        // The filter function should have no parameters since nothing is indexed
        assert!(
            out.contains("DataStored(): EventFilter;"),
            "Expected filter with no params for non-indexed event, got:\n{out}"
        );
    }

    #[test]
    fn pure_fn_returns_promise() {
        let ir = make_ir(
            "MathLib",
            vec![AbiFunction {
                name: "add".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "a".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "b".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Uint(256),
                    internal_type: None,
                }],
                state_mutability: StateMutability::Pure,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("add(a: BigNumberish, b: BigNumberish): Promise<bigint>;"),
            "Expected `Promise<bigint>` for pure fn, got:\n{out}"
        );
    }

    #[test]
    fn non_overloaded_fn_keeps_original_name() {
        let ir = make_ir(
            "Token",
            vec![AbiFunction {
                name: "transfer".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "to".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("transfer(to: AddressLike, amount: BigNumberish)"),
            "Expected `transfer(...)` without suffix, got:\n{out}"
        );
        assert!(
            !out.contains("transfer_0"),
            "Non-overloaded function should not get `_0` suffix, got:\n{out}"
        );
    }

    #[test]
    fn named_multi_return_produces_object_type() {
        let ir = make_ir(
            "Named",
            vec![AbiFunction {
                name: "getInfo".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "owner".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "balance".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains(
                "getInfo(): Promise<[string, bigint] & { owner: string; balance: bigint }>;"
            ),
            "Expected tuple plus named fields return type, got:\n{out}"
        );
    }

    #[test]
    fn unnamed_multi_return_produces_tuple_type() {
        let ir = make_ir(
            "Unnamed",
            vec![AbiFunction {
                name: "getValues".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("getValues(): Promise<[string, bigint]>;"),
            "Expected positional tuple return type for unnamed outputs, got:\n{out}"
        );
    }

    #[test]
    fn mixed_named_unnamed_multi_return_produces_tuple() {
        let ir = make_ir(
            "Mixed",
            vec![AbiFunction {
                name: "getMixed".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "owner".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("getMixed(): Promise<[string, bigint] & { owner: string }>;"),
            "Expected tuple plus available named fields when some outputs are unnamed, got:\n{out}"
        );
    }

    #[test]
    fn array_of_tuple_outputs_parenthesizes_intersection_type() {
        let ir = make_ir(
            "ArrayTuple",
            vec![AbiFunction {
                name: "getItems".to_string(),
                inputs: vec![],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Array(Box::new(SolType::Tuple(vec![TupleComponent {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    }]))),
                    internal_type: None,
                }],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ethers_file(&ir);
        assert!(
            out.contains("getItems(): Promise<([bigint] & { amount: bigint })[]>;"),
            "Expected array element intersection to be parenthesized, got:\n{out}"
        );
    }
}
