//! Java 21 web3j bindings with named ABI value types and optional contract wrappers.

use crate::naming::{Scope, exported, overload_indices, param_names, repeat_indices};
use crate::tuples::TupleRegistry;
use abi_typegen_core::types::{AbiParam, ContractIr, SolType};
use heck::ToShoutySnakeCase;
use std::collections::HashMap;

mod layout;

/// Returns the public Java class name for an ABI contract.
pub fn namespace_name(name: &str) -> String {
    let name = exported(name);
    if name.is_empty() {
        "Contract".to_string()
    } else if [
        "String",
        "Boolean",
        "Object",
        "Class",
        "Math",
        "Integer",
        "Client",
        "TransactionOptions",
        "Layout",
        "Atom",
        "ArrayLayout",
        "TupleLayout",
    ]
    .contains(&name.as_str())
    {
        format!("{name}Contract")
    } else {
        name
    }
}

/// Renders one standalone Java 21 source file using web3j 6.0.0.
pub fn render_java_file(ir: &ContractIr, package: &str, wrappers: bool) -> String {
    let registry = TupleRegistry::new(ir);
    let contract = namespace_name(&ir.name);
    let mut scope = Scope::with_reserved([
        contract.as_str(),
        "Client",
        "TransactionOptions",
        "ABI",
        "Layout",
        "Atom",
        "ArrayLayout",
        "TupleLayout",
        "String",
        "Boolean",
        "Object",
        "Class",
        "Math",
        "Integer",
    ]);
    let tuple_names: HashMap<String, String> = registry
        .defs()
        .iter()
        .map(|def| (def.name.clone(), scope.claim(&def.name)))
        .collect();
    let java = Java {
        registry: &registry,
        tuple_names: &tuple_names,
    };
    let mut out = format!(
        "// Generated by abi-typegen. Do not edit.\npackage {package};\n\n/** Types and bindings for the `{}` contract. */\npublic final class {contract} {{\n    private {contract}() {{}}\n",
        ir.name
    );
    let abi = serde_json::to_string(&ir.raw_abi).expect("JSON values serialize");
    out.push_str(&format!(
        "    /** JSON ABI for the contract. */\n    public static final String ABI = {};\n",
        java_json(&abi)
    ));
    out.push_str("    private static <T> T unsupportedStaticArray() { throw new UnsupportedOperationException(\"web3j supports static arrays with 1 to 32 elements\"); }\n");
    let mut constants = Scope::with_reserved(["ABI"]);
    for (function, index) in ir.functions.iter().zip(overload_indices(&ir.functions)) {
        let suffix = index.map(|i| format!("_{i}")).unwrap_or_default();
        let base = constants.claim_family(
            &format!("{}{}", function.name.to_shouty_snake_case(), suffix),
            &["_SIGNATURE", "_SELECTOR"],
        );
        out.push_str(&format!("    /** Canonical function signature. */\n    public static final String {base}_SIGNATURE = {};\n", java_string(&function.signature())));
        out.push_str(&format!("    /** Four-byte function selector. */\n    public static final String {base}_SELECTOR = {};\n", java_string(&function.selector().to_string())));
    }
    for (event, index) in ir
        .events
        .iter()
        .zip(repeat_indices(ir.events.iter().map(|e| e.name.as_str())))
    {
        let suffix = index.map(|i| format!("_{i}")).unwrap_or_default();
        let base = constants.claim_family(
            &format!("{}{}", event.name.to_shouty_snake_case(), suffix),
            &["_EVENT_SIGNATURE", "_EVENT_TOPIC"],
        );
        out.push_str(&format!("    /** Canonical event signature. */\n    public static final String {base}_EVENT_SIGNATURE = {};\n", java_string(&event.signature())));
        if !event.anonymous {
            out.push_str(&format!("    /** Event topic zero. */\n    public static final String {base}_EVENT_TOPIC = {};\n", java_string(&event.topic0().to_string())));
        }
    }
    for (error, index) in ir
        .errors
        .iter()
        .zip(repeat_indices(ir.errors.iter().map(|e| e.name.as_str())))
    {
        let suffix = index.map(|i| format!("_{i}")).unwrap_or_default();
        let base = constants.claim_family(
            &format!("{}{}", error.name.to_shouty_snake_case(), suffix),
            &["_ERROR_SIGNATURE", "_ERROR_SELECTOR"],
        );
        out.push_str(&format!("    /** Canonical error signature. */\n    public static final String {base}_ERROR_SIGNATURE = {};\n", java_string(&error.signature())));
        out.push_str(&format!("    /** Error selector. */\n    public static final String {base}_ERROR_SELECTOR = {};\n", java_string(&error.selector().to_string())));
    }
    for def in registry.defs() {
        let name = &tuple_names[&def.name];
        let fields = java.fields(
            &def.components
                .iter()
                .map(|c| AbiParam {
                    name: c.name.clone(),
                    ty: c.ty.clone(),
                    internal_type: c.internal_type.clone(),
                })
                .collect::<Vec<_>>(),
        );
        let dynamic = def.components.iter().any(|c| is_dynamic(&c.ty));
        let base = if dynamic {
            "org.web3j.abi.datatypes.DynamicStruct"
        } else {
            "org.web3j.abi.datatypes.StaticStruct"
        };
        let params = fields
            .iter()
            .map(|f| format!("{} {}", f.ty, f.name))
            .collect::<Vec<_>>()
            .join(", ");
        let sdk = def
            .components
            .iter()
            .zip(&fields)
            .map(|(c, f)| java.to_sdk(&f.name, &c.ty, c.internal_type.as_deref(), 0))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("\n    /** `{name}` tuple value. */\n    public static final class {name} extends {base} {{\n"));
        for f in &fields {
            out.push_str(&format!("        public final {} {};\n", f.ty, f.name));
        }
        out.push_str(&format!(
            "        public {name}({params}) {{\n            super({sdk});\n"
        ));
        for f in &fields {
            out.push_str(&format!("            this.{} = {};\n", f.name, f.name));
        }
        out.push_str("        }\n    }\n");
    }
    for (event, index) in ir
        .events
        .iter()
        .zip(repeat_indices(ir.events.iter().map(|e| e.name.as_str())))
    {
        let stem = format!(
            "{}{}",
            exported(&event.name),
            index.map(|i| i.to_string()).unwrap_or_default()
        );
        let params: Vec<AbiParam> = event
            .inputs
            .iter()
            .map(|p| AbiParam {
                name: p.name.clone(),
                ty: p.ty.clone(),
                internal_type: p.internal_type.clone(),
            })
            .collect();
        out.push_str(&java.record(&format!("{stem}Event"), &params));
    }
    for (error, index) in ir
        .errors
        .iter()
        .zip(repeat_indices(ir.errors.iter().map(|e| e.name.as_str())))
    {
        let stem = format!(
            "{}{}",
            exported(&error.name),
            index.map(|i| i.to_string()).unwrap_or_default()
        );
        out.push_str(&java.record(&format!("{stem}Error"), &error.inputs));
    }
    if wrappers {
        out.push_str(&layout::render(ir, &java));
    }
    out.push_str("}\n");
    out
}

struct Field {
    name: String,
    ty: String,
}

struct Java<'a> {
    registry: &'a TupleRegistry,
    tuple_names: &'a HashMap<String, String>,
}

impl Java<'_> {
    fn fields(&self, params: &[AbiParam]) -> Vec<Field> {
        let names = param_names(params.iter().map(|p| {
            (
                p.name.as_str(),
                &p.ty,
                self.registry
                    .name_of_type(&p.ty, p.internal_type.as_deref()),
            )
        }));
        let mut scope = Scope::default();
        params
            .iter()
            .zip(names)
            .map(|(p, name)| Field {
                name: scope.claim(&java_ident(&name)),
                ty: self.field_type(&p.ty, p.internal_type.as_deref()),
            })
            .collect()
    }
    fn field_type(&self, ty: &SolType, internal: Option<&str>) -> String {
        match ty {
            SolType::Bool => "Boolean".into(),
            SolType::Address | SolType::StringType => "String".into(),
            SolType::Uint(_) | SolType::Int(_) => "java.math.BigInteger".into(),
            SolType::Bytes => "org.web3j.abi.datatypes.DynamicBytes".into(),
            SolType::BytesN(size) => format!("org.web3j.abi.datatypes.generated.Bytes{size}"),
            SolType::Array(inner) | SolType::FixedArray(inner, _) => {
                format!("java.util.List<{}>", self.field_type(inner, internal))
            }
            SolType::Tuple(components) => {
                self.tuple_names[self.registry.name(components, internal)].clone()
            }
        }
    }
    fn sdk_type(&self, ty: &SolType, internal: Option<&str>) -> String {
        match ty {
            SolType::Bool => "org.web3j.abi.datatypes.Bool".into(),
            SolType::Address => "org.web3j.abi.datatypes.Address".into(),
            SolType::StringType => "org.web3j.abi.datatypes.Utf8String".into(),
            SolType::Uint(bits) => format!("org.web3j.abi.datatypes.generated.Uint{bits}"),
            SolType::Int(bits) => format!("org.web3j.abi.datatypes.generated.Int{bits}"),
            SolType::Bytes => "org.web3j.abi.datatypes.DynamicBytes".into(),
            SolType::BytesN(size) => format!("org.web3j.abi.datatypes.generated.Bytes{size}"),
            SolType::Array(inner) => format!(
                "org.web3j.abi.datatypes.DynamicArray<{}>",
                self.sdk_type(inner, internal)
            ),
            SolType::FixedArray(inner, size) => format!(
                "org.web3j.abi.datatypes.{}<{}>",
                if (1..=32).contains(size) {
                    format!("generated.StaticArray{size}")
                } else {
                    "StaticArray".into()
                },
                self.sdk_type(inner, internal)
            ),
            SolType::Tuple(components) => {
                self.tuple_names[self.registry.name(components, internal)].clone()
            }
        }
    }
    fn sdk_class(&self, ty: &SolType, internal: Option<&str>) -> String {
        match ty {
            SolType::Array(_) => "org.web3j.abi.datatypes.DynamicArray".into(),
            SolType::FixedArray(_, size) => {
                if (1..=32).contains(size) {
                    format!("org.web3j.abi.datatypes.generated.StaticArray{size}")
                } else {
                    "org.web3j.abi.datatypes.StaticArray".into()
                }
            }
            _ => self.sdk_type(ty, internal),
        }
    }
    fn to_sdk(&self, expr: &str, ty: &SolType, internal: Option<&str>, depth: usize) -> String {
        match ty {
            SolType::Bool
            | SolType::Address
            | SolType::StringType
            | SolType::Uint(_)
            | SolType::Int(_) => format!("new {}({expr})", self.sdk_type(ty, internal)),
            SolType::Bytes | SolType::BytesN(_) | SolType::Tuple(_) => expr.into(),
            SolType::Array(inner) => {
                let item = format!("item{depth}");
                let converted = self.to_sdk(&item, inner, internal, depth + 1);
                format!(
                    "new org.web3j.abi.datatypes.DynamicArray({} .class, {expr}.stream().map({item} -> {converted}).toList())",
                    self.sdk_class(inner, internal)
                )
            }
            SolType::FixedArray(inner, size) => {
                if !(1..=32).contains(size) {
                    return "unsupportedStaticArray()".into();
                }
                let item = format!("item{depth}");
                let converted = self.to_sdk(&item, inner, internal, depth + 1);
                format!(
                    "new org.web3j.abi.datatypes.generated.StaticArray{size}({}.class, {expr}.stream().map({item} -> {converted}).toList())",
                    self.sdk_class(inner, internal)
                )
            }
        }
    }
    fn record(&self, name: &str, params: &[AbiParam]) -> String {
        let fields = self.fields(params);
        let args = fields
            .iter()
            .map(|f| format!("{} {}", f.ty, f.name))
            .collect::<Vec<_>>()
            .join(", ");
        format!("\n    /** Decoded `{name}` ABI value. */\n    public record {name}({args}) {{}}\n")
    }
}

fn java_ident(name: &str) -> String {
    const RESERVED: &[&str] = &[
        "abstract",
        "assert",
        "boolean",
        "break",
        "byte",
        "case",
        "catch",
        "char",
        "class",
        "const",
        "continue",
        "default",
        "do",
        "double",
        "else",
        "enum",
        "extends",
        "final",
        "finally",
        "float",
        "for",
        "goto",
        "if",
        "implements",
        "import",
        "instanceof",
        "int",
        "interface",
        "long",
        "native",
        "new",
        "package",
        "private",
        "protected",
        "public",
        "return",
        "short",
        "static",
        "strictfp",
        "super",
        "switch",
        "synchronized",
        "this",
        "throw",
        "throws",
        "transient",
        "try",
        "void",
        "volatile",
        "while",
        "record",
        "sealed",
        "permits",
        "yield",
        "var",
        "true",
        "false",
        "null",
        "_into",
        "value",
    ];
    let name = if name.is_empty() { "arg" } else { name };
    if RESERVED.contains(&name) || name == "_" {
        format!("{name}_")
    } else {
        name.into()
    }
}

fn is_dynamic(ty: &SolType) -> bool {
    match ty {
        SolType::Bytes | SolType::StringType | SolType::Array(_) => true,
        SolType::FixedArray(inner, _) => is_dynamic(inner),
        SolType::Tuple(parts) => parts.iter().any(|part| is_dynamic(&part.ty)),
        SolType::Bool
        | SolType::Address
        | SolType::Uint(_)
        | SolType::Int(_)
        | SolType::BytesN(_) => false,
    }
}

fn java_string(value: &str) -> String {
    let mut out = String::from("\"");
    for c in value.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
fn java_json(json: &str) -> String {
    let chars: Vec<char> = json.chars().collect();
    let chunks = chars
        .chunks(16_000)
        .map(|chunk| java_string(&chunk.iter().collect::<String>()))
        .collect::<Vec<_>>();
    if chunks.is_empty() {
        "\"\"".into()
    } else {
        format!("String.join(\"\", {})", chunks.join(",\n        "))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;
    #[test]
    fn renders_wrappers_and_metadata_mode() {
        let ir=parse_artifact("Token",r#"{"abi":[{"type":"function","name":"balanceOf","inputs":[{"name":"owner","type":"address"}],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},{"type":"function","name":"mint","inputs":[{"name":"to","type":"address"},{"name":"amount","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"}]}"#).expect("abi");
        let full = render_java_file(&ir, "contracts", true);
        assert!(full.contains("encodeBalanceOf"), "{full}");
        assert!(full.contains("decodeBalanceOfResult"), "{full}");
        assert!(full.contains("callBalanceOf"), "{full}");
        assert!(full.contains("sendMint"), "{full}");
        let plain = render_java_file(&ir, "contracts", false);
        assert!(plain.contains("public static final String ABI"));
        assert!(!plain.contains("encodeBalanceOf"));
    }
}
