use crate::type_mapper::{overload_suffix, safe_param_name, struct_name_from_internal_type};
use abi_typegen_core::types::{AbiFunction, ContractIr, SolType, StateMutability, TupleComponent};
use heck::ToSnakeCase;
use std::collections::{HashMap, HashSet};

/// Generates `<ContractName>.py` -- a typed Python stub for web3.py.
pub fn render_python_file(ir: &ContractIr) -> String {
    render_python_file_inner(ir, false, true)
}

/// Generates Python ABI metadata and optionally callable web3.py wrappers.
pub fn render_python_file_with_wrappers(ir: &ContractIr, wrappers: bool) -> String {
    render_python_file_inner(ir, wrappers, false)
}

fn render_python_file_inner(ir: &ContractIr, wrappers: bool, legacy_stub: bool) -> String {
    let mut out = String::new();
    let name = &ir.name;
    let name_upper = name.to_ascii_uppercase();

    // Header
    out.push_str("# Auto-generated by abi-typegen. Do not edit manually.\n");
    let module_description = if wrappers {
        "Web3.py bindings"
    } else {
        "Type stubs"
    };
    out.push_str(&format!(
        "\"\"\"{module_description} for the {name} contract.\"\"\"\n\n"
    ));

    // Imports
    out.push_str("from __future__ import annotations\n\n");
    out.push_str("import json\n");
    if wrappers {
        out.push_str("from collections.abc import Sequence\n");
    }
    out.push_str("from typing import Any, TypedDict\n");
    if wrappers {
        out.push_str("from eth_abi import decode as abi_decode, encode as abi_encode\n");
    }
    out.push('\n');
    out.push_str("from eth_typing import ChecksumAddress\n");
    out.push_str("from web3 import Web3\n");
    out.push_str("from web3.contract import Contract\n\n\n");

    // Embedded ABI
    let abi_json = serde_json::to_string_pretty(&ir.raw_abi).unwrap_or_else(|_| "[]".to_string());
    out.push_str(&format!(
        "{}_ABI: list[dict[str, Any]] = json.loads('''\n{}\n''')\n\n\n",
        name_upper, abi_json
    ));
    if wrappers {
        out.push_str("def _strict_abi_decode(types: list[str], raw: bytes) -> tuple[Any, ...]:\n    values = abi_decode(types, raw)\n    if abi_encode(types, values) != raw:\n        raise ValueError(\"Non-canonical ABI output\")\n    return values\n\n\n");
    }

    // Collect tuple types that should be emitted as TypedDict classes.
    let mut typed_dicts: Vec<(String, Vec<(String, String)>)> = Vec::new();
    collect_typed_dicts(ir, &mut typed_dicts);

    for (class_name, fields) in &typed_dicts {
        out.push_str(&format!("class {}(TypedDict):\n", class_name));
        if fields.is_empty() {
            out.push_str("    pass\n");
        } else {
            for (field_name, field_type) in fields {
                out.push_str(&format!("    {}: {}\n", field_name, field_type));
            }
        }
        out.push_str("\n\n");
    }

    if !wrappers && !legacy_stub {
        return out;
    }

    // Contract wrapper class
    out.push_str(&format!("class {}Contract:\n", name));

    // Docstring from NatSpec or default
    if let Some(ref ns) = ir.natspec {
        if let Some(ref notice) = ns.notice {
            out.push_str(&format!(
                "    \"\"\"{}.\"\"\"\n",
                notice.trim_end_matches('.')
            ));
        } else {
            out.push_str(&format!(
                "    \"\"\"Typed wrapper for the {} contract.\"\"\"\n",
                name
            ));
        }
    } else {
        out.push_str(&format!(
            "    \"\"\"Typed wrapper for the {} contract.\"\"\"\n",
            name
        ));
    }
    out.push('\n');

    // __init__
    out.push_str("    def __init__(self, address: ChecksumAddress, w3: Web3) -> None:\n");
    out.push_str(&format!(
        "        self.contract: Contract = w3.eth.contract(\n\
         {s}address=address, abi={name_upper}_ABI,\n\
         {s2})\n",
        s = "            ",
        s2 = "        ",
    ));

    // Partition functions into view/pure and write
    let wrapper_names = python_function_names(ir);
    let mut view_fns: Vec<&AbiFunction> = Vec::new();
    let mut write_fns: Vec<&AbiFunction> = Vec::new();
    for f in &ir.functions {
        match f.state_mutability {
            StateMutability::Pure | StateMutability::View => view_fns.push(f),
            _ => write_fns.push(f),
        }
    }

    if !view_fns.is_empty() {
        // Count overloaded names within the view partition
        let mut view_name_counts: HashMap<&str, u32> = HashMap::new();
        for f in &view_fns {
            *view_name_counts.entry(f.name.as_str()).or_insert(0) += 1;
        }

        out.push('\n');
        out.push_str("    # View/pure functions\n");
        for f in &view_fns {
            let method_name = if wrappers {
                wrapper_names[ir
                    .functions
                    .iter()
                    .position(|candidate| std::ptr::eq(candidate, *f))
                    .expect("function belongs to IR")]
                .clone()
            } else {
                resolve_method_name(f, &view_name_counts)
            };
            out.push_str(&render_view_function(&method_name, f, wrappers));
        }
    }

    if !write_fns.is_empty() {
        // Count overloaded names within the write partition
        let mut write_name_counts: HashMap<&str, u32> = HashMap::new();
        for f in &write_fns {
            *write_name_counts.entry(f.name.as_str()).or_insert(0) += 1;
        }

        out.push('\n');
        out.push_str("    # Write functions\n");
        for f in &write_fns {
            let method_name = if wrappers {
                wrapper_names[ir
                    .functions
                    .iter()
                    .position(|candidate| std::ptr::eq(candidate, *f))
                    .expect("function belongs to IR")]
                .clone()
            } else {
                resolve_method_name(f, &write_name_counts)
            };
            out.push_str(&render_write_function(&method_name, f, wrappers));
        }
    }

    if wrappers {
        out.push_str(&render_python_wrapper_extras(ir));
    }

    out
}

fn render_python_wrapper_extras(ir: &ContractIr) -> String {
    let mut out = String::new();
    for (function, method) in ir.functions.iter().zip(python_function_names(ir)) {
        let signature = function.signature();
        let arg_names = python_param_names(function.inputs.iter().map(|param| param.name.as_str()));
        let values = arg_names.join(", ");
        let params = build_param_list(function, true);
        let result_types = function
            .outputs
            .iter()
            .map(|param| format!("\"{}\"", param.ty.canonical()))
            .collect::<Vec<_>>()
            .join(", ");
        let decode_body = match function.outputs.len() {
            0 => "        if data.removeprefix(\"0x\"):\n            raise ValueError(\"Unexpected output for void function\")\n        return None\n".to_string(),
            1 => format!("        return _strict_abi_decode([{result_types}], bytes.fromhex(data.removeprefix(\"0x\")))[0]\n"),
            _ => format!("        return _strict_abi_decode([{result_types}], bytes.fromhex(data.removeprefix(\"0x\")))\n"),
        };
        out.push_str(&format!("\n    def encode_{method}(self{params}) -> str:\n        \"\"\"Encodes {signature} calldata without RPC.\"\"\"\n        return self.contract.encode_abi(\"{signature}\", args=[{values}])\n\n    def decode_{method}_result(self, data: str) -> {ret}:\n        \"\"\"Decodes {signature} output without RPC.\"\"\"\n{decode_body}", ret = python_return_type(function, true)));
    }
    for (event, stem) in ir.events.iter().zip(python_event_names(ir)) {
        let signature = event.signature();
        out.push_str(&format!("\n    def filter_{stem}(self, from_block: int = 0, to_block: int | str = \"latest\", argument_filters: dict[str, Any] | None = None) -> list[Any]:\n        \"\"\"Retrieves decoded {signature} logs.\"\"\"\n        event = self.contract.get_event_by_signature(\"{signature}\")\n        return list(event.get_logs(argument_filters=argument_filters, from_block=from_block, to_block=to_block))\n\n    def decode_{stem}_log(self, log: Any) -> Any:\n        \"\"\"Decodes a {signature} receipt log.\"\"\"\n        return self.contract.get_event_by_signature(\"{signature}\").process_log(log)\n"));
    }
    for (error, stem) in ir.errors.iter().zip(python_error_names(ir)) {
        let selector = error
            .selector()
            .as_slice()
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<String>();
        let types = error
            .inputs
            .iter()
            .map(|param| format!("\"{}\"", param.ty.canonical()))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("\n    def decode_{stem}_error(self, data: str) -> tuple[Any, ...]:\n        \"\"\"Decodes {signature} custom error arguments.\"\"\"\n        raw = bytes.fromhex(data.removeprefix(\"0x\"))\n        if raw[:4] != bytes.fromhex(\"{selector}\"):\n            raise ValueError(\"Custom error selector mismatch\")\n        return _strict_abi_decode([{types}], raw[4:])\n", signature = error.signature()));
    }
    if let Some(constructor) = &ir.constructor {
        let constructor_names =
            python_param_names(constructor.inputs.iter().map(|param| param.name.as_str()));
        let fields = constructor
            .inputs
            .iter()
            .zip(&constructor_names)
            .map(|(param, name)| format!("{}: {}", name, python_runtime_type(&param.ty)))
            .collect::<Vec<_>>();
        let names = constructor_names.join(", ");
        let typed_params = if fields.is_empty() {
            String::new()
        } else {
            format!(", {}", fields.join(", "))
        };
        let guard = if matches!(constructor.state_mutability, StateMutability::NonPayable) {
            "        if transaction.get(\"value\", 0):\n            raise ValueError(\"Constructor is not payable\")\n"
        } else {
            ""
        };
        let abi_name = format!("{}_ABI", ir.name.to_ascii_uppercase());
        out.push_str(&format!("\n    @staticmethod\n    def build_deployment(w3: Web3, bytecode: str, transaction: dict[str, Any]{typed_params}) -> dict[str, Any]:\n        \"\"\"Builds deployment with caller-supplied bytecode and typed constructor arguments.\"\"\"\n{guard}        contract = w3.eth.contract(abi={abi_name}, bytecode=bytecode)\n        return contract.constructor({names}).build_transaction(transaction)\n"));
    }
    out
}

/// Resolves the Python method name, converting to snake_case and appending
/// a type-based suffix for overloaded functions.
fn resolve_method_name(f: &AbiFunction, name_counts: &HashMap<&str, u32>) -> String {
    let count = *name_counts.get(f.name.as_str()).unwrap_or(&1);
    let snake = f.name.to_snake_case();
    if count > 1 {
        let suffix = overload_suffix(&f.inputs).to_snake_case();
        if suffix.is_empty() {
            snake
        } else {
            format!("{}_{}", snake, suffix)
        }
    } else {
        snake
    }
}

fn python_function_names(ir: &ContractIr) -> Vec<String> {
    let mut counts = HashMap::new();
    for function in &ir.functions {
        *counts.entry(function.name.as_str()).or_insert(0) += 1;
    }
    let mut used = HashSet::from(["__init__".to_string(), "build_deployment".to_string()]);
    ir.functions
        .iter()
        .map(|function| {
            let base = resolve_method_name(function, &counts);
            let mut candidate = base.clone();
            let mut index = 2;
            while used.contains(&candidate)
                || used.contains(&format!("encode_{candidate}"))
                || used.contains(&format!("decode_{candidate}_result"))
            {
                candidate = format!("{base}_{index}");
                index += 1;
            }
            used.insert(candidate.clone());
            used.insert(format!("encode_{candidate}"));
            used.insert(format!("decode_{candidate}_result"));
            candidate
        })
        .collect()
}

fn python_event_names(ir: &ContractIr) -> Vec<String> {
    let mut used = python_function_names(ir)
        .into_iter()
        .collect::<HashSet<_>>();
    for name in python_function_names(ir) {
        used.insert(format!("encode_{name}"));
        used.insert(format!("decode_{name}_result"));
    }
    ir.events
        .iter()
        .map(|event| {
            let base = event.name.to_snake_case();
            let mut candidate = base.clone();
            let mut index = 2;
            while used.contains(&format!("filter_{candidate}"))
                || used.contains(&format!("decode_{candidate}_log"))
            {
                candidate = format!("{base}_{index}");
                index += 1;
            }
            used.insert(format!("filter_{candidate}"));
            used.insert(format!("decode_{candidate}_log"));
            candidate
        })
        .collect()
}

fn python_error_names(ir: &ContractIr) -> Vec<String> {
    let mut used = python_function_names(ir)
        .into_iter()
        .collect::<HashSet<_>>();
    for name in python_function_names(ir) {
        used.insert(format!("encode_{name}"));
        used.insert(format!("decode_{name}_result"));
    }
    for name in python_event_names(ir) {
        used.insert(format!("filter_{name}"));
        used.insert(format!("decode_{name}_log"));
    }
    ir.errors
        .iter()
        .map(|error| {
            let base = error.name.to_snake_case();
            let mut candidate = base.clone();
            let mut index = 2;
            while used.contains(&format!("decode_{candidate}_error")) {
                candidate = format!("{base}_{index}");
                index += 1;
            }
            used.insert(format!("decode_{candidate}_error"));
            candidate
        })
        .collect()
}

/// Converts a Solidity type to its Python type string.
fn sol_type_to_python(ty: &SolType) -> String {
    match ty {
        SolType::Uint(_) | SolType::Int(_) => "int".into(),
        SolType::Bool => "bool".into(),
        SolType::Address => "ChecksumAddress".into(),
        SolType::Bytes | SolType::BytesN(_) => "bytes".into(),
        SolType::StringType => "str".into(),
        SolType::Array(inner) | SolType::FixedArray(inner, _) => {
            format!("list[{}]", sol_type_to_python(inner))
        }
        SolType::Tuple(_) => "dict[str, Any]".into(),
    }
}

fn python_runtime_type(ty: &SolType) -> String {
    match ty {
        SolType::Array(inner) | SolType::FixedArray(inner, _) => {
            format!("Sequence[{}]", python_runtime_type(inner))
        }
        SolType::Tuple(components) => {
            if components.is_empty() {
                "tuple[()]".to_string()
            } else {
                format!(
                    "tuple[{}]",
                    components
                        .iter()
                        .map(|component| python_runtime_type(&component.ty))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            }
        }
        SolType::Uint(_)
        | SolType::Int(_)
        | SolType::Bool
        | SolType::Address
        | SolType::Bytes
        | SolType::BytesN(_)
        | SolType::StringType => sol_type_to_python(ty),
    }
}

/// Python keywords that cannot be used as parameter names.
///
/// This supplements the JS/TS reserved-word check in `safe_param_name` with
/// words that are legal identifiers in JavaScript but keywords in Python
/// (e.g. `from`, `as`, `lambda`, `nonlocal`).
const PYTHON_KEYWORDS: &[&str] = &[
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
    "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
    "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield",
];

/// Converts a parameter name to a Python-safe snake_case name.
///
/// Checks both JS/TS reserved words (via `safe_param_name`) and Python
/// keywords, since names like `from` are valid in TypeScript but not Python.
/// The Python keyword check runs after snake_case conversion so that
/// camelCase names like `From` → `from` are also caught.
fn python_safe_param_name(name: &str, index: usize) -> String {
    let base = safe_param_name(name, index);
    let snake = base.to_snake_case();
    if snake.is_empty() || snake.starts_with(|ch: char| ch.is_ascii_digit()) {
        format!("arg{index}")
    } else if PYTHON_KEYWORDS.contains(&snake.as_str()) {
        format!("_{}", snake)
    } else {
        snake
    }
}

fn python_param_names<'a>(names: impl Iterator<Item = &'a str>) -> Vec<String> {
    let mut scope = crate::naming::Scope::default();
    scope.claim("self");
    scope.claim("w3");
    scope.claim("bytecode");
    scope.claim("transaction");
    names
        .enumerate()
        .map(|(index, name)| scope.claim(&python_safe_param_name(name, index)))
        .collect()
}

/// Builds the Python return type for a view/pure function.
fn python_return_type(f: &AbiFunction, runtime: bool) -> String {
    let out_types: Vec<String> = f
        .outputs
        .iter()
        .map(|p| {
            if runtime {
                python_runtime_type(&p.ty)
            } else {
                sol_type_to_python(&p.ty)
            }
        })
        .collect();
    match out_types.len() {
        0 => "None".into(),
        1 => out_types[0].clone(),
        _ => format!("tuple[{}]", out_types.join(", ")),
    }
}

/// Renders a view/pure function as a Python stub method.
fn render_view_function(method_name: &str, f: &AbiFunction, wrappers: bool) -> String {
    let params = build_param_list(f, wrappers);
    let ret = python_return_type(f, wrappers);

    if wrappers {
        let values =
            python_param_names(f.inputs.iter().map(|param| param.name.as_str())).join(", ");
        return format!(
            "    def {method_name}(self{params}) -> {ret}:\n        \"\"\"Calls {signature} through web3.py.\"\"\"\n        return self.contract.get_function_by_signature(\"{signature}\")({values}).call()\n\n",
            signature = f.signature()
        );
    }

    let mut s = String::new();
    if let Some(doc) = natspec_docstring(f) {
        s.push_str(&format!(
            "    def {}(self{}) -> {}:\n        \"\"\"{}\"\"\"\n        ...\n",
            method_name, params, ret, doc
        ));
    } else {
        s.push_str(&format!(
            "    def {}(self{}) -> {}: ...\n",
            method_name, params, ret
        ));
    }
    s
}

/// Renders a write (nonpayable/payable) function as a Python stub method.
fn render_write_function(method_name: &str, f: &AbiFunction, wrappers: bool) -> String {
    let params = build_param_list(f, wrappers);

    if wrappers {
        let values =
            python_param_names(f.inputs.iter().map(|param| param.name.as_str())).join(", ");
        let signature = f.signature();
        let guard = if matches!(f.state_mutability, StateMutability::NonPayable) {
            "        if transaction.get(\"value\", 0):\n            raise ValueError(\"Function is not payable\")\n"
        } else {
            ""
        };
        return format!(
            "    def {method_name}(self{params}, transaction: dict[str, Any]) -> dict[str, Any]:\n        \"\"\"Builds a transaction for {signature}.\"\"\"\n{guard}        return self.contract.get_function_by_signature(\"{signature}\")({values}).build_transaction(transaction)\n\n"
        );
    }

    let mut s = String::new();
    if let Some(doc) = natspec_docstring(f) {
        s.push_str(&format!(
            "    def {}(self{}) -> dict[str, Any]:\n        \"\"\"{}\"\"\"\n        ...\n",
            method_name, params, doc
        ));
    } else {
        s.push_str(&format!(
            "    def {}(self{}) -> dict[str, Any]: ...\n",
            method_name, params
        ));
    }
    s
}

/// Builds the parameter list string (without `self`) for a function.
fn build_param_list(f: &AbiFunction, runtime: bool) -> String {
    if f.inputs.is_empty() {
        return String::new();
    }
    let names = python_param_names(f.inputs.iter().map(|param| param.name.as_str()));
    let params: Vec<String> = f
        .inputs
        .iter()
        .zip(&names)
        .map(|(param, name)| {
            format!(
                "{}: {}",
                name,
                if runtime {
                    python_runtime_type(&param.ty)
                } else {
                    sol_type_to_python(&param.ty)
                }
            )
        })
        .collect();
    format!(", {}", params.join(", "))
}

/// Extracts a NatSpec docstring from a function, if available.
fn natspec_docstring(f: &AbiFunction) -> Option<String> {
    let ns = f.natspec.as_ref()?;
    ns.notice.as_ref().map(|s| s.trim().to_string())
}

/// Collects all tuple types that should be emitted as TypedDict classes.
fn collect_typed_dicts(ir: &ContractIr, dicts: &mut Vec<(String, Vec<(String, String)>)>) {
    let mut seen = HashSet::new();

    // Collect from function inputs/outputs
    for f in &ir.functions {
        for p in f.inputs.iter().chain(f.outputs.iter()) {
            if let SolType::Tuple(ref components) = p.ty {
                let struct_name = p
                    .internal_type
                    .as_deref()
                    .and_then(struct_name_from_internal_type)
                    .unwrap_or(&p.name);
                if struct_name.is_empty() {
                    continue;
                }
                let class_name = format!("{}{}", ir.name, struct_name);
                if seen.insert(class_name.clone()) {
                    let fields = typed_dict_fields(components);
                    dicts.push((class_name, fields));
                }
            }
        }
    }

    // Collect from event parameters
    for e in &ir.events {
        for p in &e.inputs {
            if let SolType::Tuple(ref components) = p.ty {
                let struct_name = p
                    .internal_type
                    .as_deref()
                    .and_then(struct_name_from_internal_type)
                    .unwrap_or(&p.name);
                if struct_name.is_empty() {
                    continue;
                }
                let class_name = format!("{}{}", ir.name, struct_name);
                if seen.insert(class_name.clone()) {
                    let fields = typed_dict_fields(components);
                    dicts.push((class_name, fields));
                }
            }
        }
    }

    // Collect from error parameters
    for e in &ir.errors {
        for p in &e.inputs {
            if let SolType::Tuple(ref components) = p.ty {
                let struct_name = p
                    .internal_type
                    .as_deref()
                    .and_then(struct_name_from_internal_type)
                    .unwrap_or(&p.name);
                if struct_name.is_empty() {
                    continue;
                }
                let class_name = format!("{}{}", ir.name, struct_name);
                if seen.insert(class_name.clone()) {
                    let fields = typed_dict_fields(components);
                    dicts.push((class_name, fields));
                }
            }
        }
    }
}

/// Converts tuple components to TypedDict field definitions.
fn typed_dict_fields(components: &[TupleComponent]) -> Vec<(String, String)> {
    components
        .iter()
        .enumerate()
        .map(|(i, c)| {
            let fname = python_safe_param_name(&c.name, i);
            let ftype = sol_type_to_python(&c.ty);
            (fname, ftype)
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;
    use abi_typegen_core::types::{AbiError, AbiEvent, AbiEventParam, AbiParam};

    fn erc20() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/erc20.json"),
        )
        .unwrap();
        parse_artifact("Token", &json).unwrap()
    }

    /// Helper to build a minimal ContractIr with the given functions and events.
    fn make_ir(name: &str, functions: Vec<AbiFunction>, events: Vec<AbiEvent>) -> ContractIr {
        ContractIr {
            name: name.to_string(),
            constructor: None,
            functions,
            events,
            errors: vec![],
            has_fallback: false,
            has_receive: false,
            natspec: None,
            raw_abi: serde_json::Value::Array(vec![]),
        }
    }

    #[test]
    fn contains_class_token_contract() {
        let out = render_python_file(&erc20());
        assert!(
            out.contains("class TokenContract"),
            "Expected `class TokenContract`, got:\n{out}"
        );
    }

    #[test]
    fn function_names_are_snake_case() {
        let out = render_python_file(&erc20());
        assert!(
            out.contains("balance_of"),
            "Expected `balance_of` (snake_case), got:\n{out}"
        );
        // Check that method definitions use snake_case (the raw ABI JSON will
        // still contain camelCase, so we only check the class body).
        let class_body = out
            .split("class TokenContract:")
            .nth(1)
            .expect("class body");
        assert!(
            !class_body.contains("def balanceOf"),
            "Method definitions should not use camelCase `balanceOf`, got:\n{class_body}"
        );
    }

    #[test]
    fn contains_token_abi() {
        let out = render_python_file(&erc20());
        assert!(
            out.contains("TOKEN_ABI"),
            "Expected `TOKEN_ABI`, got:\n{out}"
        );
    }

    #[test]
    fn contains_web3_import() {
        let out = render_python_file(&erc20());
        assert!(
            out.contains("from web3 import Web3"),
            "Expected `from web3 import Web3`, got:\n{out}"
        );
    }

    #[test]
    fn write_fn_returns_dict() {
        let out = render_python_file(&erc20());
        assert!(
            out.contains("dict[str, Any]"),
            "Expected write function to return `dict[str, Any]`, got:\n{out}"
        );
    }

    #[test]
    fn callable_wrappers_use_canonical_sdk_functions() {
        let out = render_python_file_with_wrappers(&erc20(), true);
        assert!(
            out.contains("get_function_by_signature(\"balanceOf(address)\")"),
            "{out}"
        );
        assert!(out.contains("build_transaction(transaction)"), "{out}");
        assert!(
            out.contains("encode_abi(\"transfer(address,uint256)\""),
            "{out}"
        );
        assert!(out.contains("get_event_by_signature("), "{out}");
        assert!(out.contains("abi_decode("), "{out}");
    }

    #[test]
    fn no_wrappers_keeps_abi_without_executable_stubs() {
        let out = render_python_file_with_wrappers(&erc20(), false);
        assert!(out.contains("TOKEN_ABI"), "{out}");
        assert!(!out.contains("class TokenContract"), "{out}");
        assert!(!out.contains("..."), "{out}");
    }

    #[test]
    fn wrapper_method_families_and_parameters_do_not_collide() {
        let input = |name: &str, ty: SolType| AbiParam {
            name: name.into(),
            ty,
            internal_type: None,
        };
        let function = |name: &str, param: AbiParam| AbiFunction {
            name: name.into(),
            inputs: vec![param],
            outputs: vec![],
            state_mutability: StateMutability::View,
            natspec: None,
        };
        let event = |ty: SolType| AbiEvent {
            name: "Changed".into(),
            inputs: vec![AbiEventParam {
                name: "value".into(),
                ty,
                indexed: true,
                internal_type: None,
            }],
            anonymous: false,
            natspec: None,
        };
        let mut ir = make_ir(
            "Collision",
            vec![
                function("foo", input("value", SolType::Uint(256))),
                function("encodeFoo", input("value", SolType::Uint(256))),
                function("inspect", input("self", SolType::Uint(256))),
            ],
            vec![event(SolType::Uint(256)), event(SolType::Address)],
        );
        ir.errors = vec![
            AbiError {
                name: "Denied".into(),
                inputs: vec![input("value", SolType::Uint(256))],
                natspec: None,
            },
            AbiError {
                name: "Denied".into(),
                inputs: vec![input("value", SolType::Address)],
                natspec: None,
            },
        ];
        let out = render_python_file_with_wrappers(&ir, true);
        for method in [
            "encode_foo",
            "encode_foo_2",
            "filter_changed",
            "filter_changed_2",
            "decode_denied_error",
            "decode_denied_2_error",
        ] {
            assert_eq!(
                out.matches(&format!("    def {method}(")).count(),
                1,
                "{out}"
            );
        }
        assert!(out.contains("def inspect(self, self2: int)"), "{out}");
    }

    #[test]
    fn view_fn_returns_typed_output() {
        let ir = make_ir(
            "MyToken",
            vec![AbiFunction {
                name: "balanceOf".to_string(),
                inputs: vec![AbiParam {
                    name: "account".to_string(),
                    ty: SolType::Address,
                    internal_type: None,
                }],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Uint(256),
                    internal_type: None,
                }],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_python_file(&ir);
        assert!(
            out.contains("def balance_of(self, account: ChecksumAddress) -> int: ..."),
            "Expected typed view function, got:\n{out}"
        );
    }

    #[test]
    fn write_fn_signature() {
        let ir = make_ir(
            "MyToken",
            vec![AbiFunction {
                name: "transfer".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "to".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
        );
        let out = render_python_file(&ir);
        assert!(
            out.contains(
                "def transfer(self, to: ChecksumAddress, amount: int) -> dict[str, Any]: ..."
            ),
            "Expected write function signature, got:\n{out}"
        );
    }

    #[test]
    fn view_fn_void_returns_none() {
        let ir = make_ir(
            "Minimal",
            vec![AbiFunction {
                name: "ping".to_string(),
                inputs: vec![],
                outputs: vec![],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_python_file(&ir);
        assert!(
            out.contains("def ping(self) -> None: ..."),
            "Expected `-> None` for view fn with no outputs, got:\n{out}"
        );
    }

    #[test]
    fn view_fn_multiple_outputs_returns_tuple() {
        let ir = make_ir(
            "Multi",
            vec![AbiFunction {
                name: "getPair".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "a".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "b".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_python_file(&ir);
        assert!(
            out.contains("def get_pair(self) -> tuple[ChecksumAddress, int]: ..."),
            "Expected tuple return type, got:\n{out}"
        );
    }

    #[test]
    fn type_mappings_bool_and_string() {
        let ir = make_ir(
            "Test",
            vec![AbiFunction {
                name: "check".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "flag".to_string(),
                        ty: SolType::Bool,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "label".to_string(),
                        ty: SolType::StringType,
                        internal_type: None,
                    },
                ],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Bool,
                    internal_type: None,
                }],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_python_file(&ir);
        assert!(
            out.contains("def check(self, flag: bool, label: str) -> bool: ..."),
            "Expected bool and str types, got:\n{out}"
        );
    }

    #[test]
    fn type_mapping_bytes() {
        let ir = make_ir(
            "Test",
            vec![AbiFunction {
                name: "setData".to_string(),
                inputs: vec![AbiParam {
                    name: "data".to_string(),
                    ty: SolType::Bytes,
                    internal_type: None,
                }],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::BytesN(32),
                    internal_type: None,
                }],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_python_file(&ir);
        assert!(
            out.contains("def set_data(self, data: bytes) -> bytes: ..."),
            "Expected bytes types, got:\n{out}"
        );
    }

    #[test]
    fn type_mapping_array() {
        let ir = make_ir(
            "Test",
            vec![AbiFunction {
                name: "getList".to_string(),
                inputs: vec![],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Array(Box::new(SolType::Uint(256))),
                    internal_type: None,
                }],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_python_file(&ir);
        assert!(
            out.contains("-> list[int]"),
            "Expected list[int] return type, got:\n{out}"
        );
    }

    #[test]
    fn type_mapping_fixed_array() {
        let ir = make_ir(
            "Test",
            vec![AbiFunction {
                name: "getFixed".to_string(),
                inputs: vec![],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::FixedArray(Box::new(SolType::Address), 3),
                    internal_type: None,
                }],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_python_file(&ir);
        assert!(
            out.contains("-> list[ChecksumAddress]"),
            "Expected list[ChecksumAddress] return type, got:\n{out}"
        );
    }

    #[test]
    fn header_and_docstring() {
        let out = render_python_file(&erc20());
        assert!(
            out.contains("# Auto-generated by abi-typegen. Do not edit manually."),
            "Expected header comment, got:\n{out}"
        );
        assert!(
            out.contains("\"\"\"Type stubs for the Token contract.\"\"\""),
            "Expected module docstring, got:\n{out}"
        );
    }

    #[test]
    fn init_method() {
        let out = render_python_file(&erc20());
        assert!(
            out.contains("def __init__(self, address: ChecksumAddress, w3: Web3) -> None:"),
            "Expected __init__ method, got:\n{out}"
        );
    }

    #[test]
    fn contract_import() {
        let out = render_python_file(&erc20());
        assert!(
            out.contains("from web3.contract import Contract"),
            "Expected web3 Contract import, got:\n{out}"
        );
    }

    #[test]
    fn empty_param_name_gets_fallback() {
        let ir = make_ir(
            "Test",
            vec![AbiFunction {
                name: "doThing".to_string(),
                inputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Uint(256),
                    internal_type: None,
                }],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
        );
        let out = render_python_file(&ir);
        assert!(
            out.contains("arg0: int"),
            "Expected positional fallback name `arg0`, got:\n{out}"
        );
    }

    #[test]
    fn python_overloaded_write_fns_get_suffix() {
        let ir = make_ir(
            "Vault",
            vec![
                AbiFunction {
                    name: "deposit".to_string(),
                    inputs: vec![AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    }],
                    outputs: vec![],
                    state_mutability: StateMutability::NonPayable,
                    natspec: None,
                },
                AbiFunction {
                    name: "deposit".to_string(),
                    inputs: vec![
                        AbiParam {
                            name: "amount".to_string(),
                            ty: SolType::Uint(256),
                            internal_type: None,
                        },
                        AbiParam {
                            name: "recipient".to_string(),
                            ty: SolType::Address,
                            internal_type: None,
                        },
                    ],
                    outputs: vec![],
                    state_mutability: StateMutability::NonPayable,
                    natspec: None,
                },
            ],
            vec![],
        );
        let out = render_python_file(&ir);
        // Both deposit overloads should have suffixed method names
        assert!(
            out.contains("def deposit_uint256(self"),
            "Expected `deposit_uint` method, got:\n{out}"
        );
        assert!(
            out.contains("def deposit_uint256_address(self"),
            "Expected `deposit_uint256_address` method, got:\n{out}"
        );
    }

    #[test]
    fn python_cross_partition_same_name_no_suffix() {
        // A view `getInfo` and a write `getInfo` should NOT get suffixes
        // because each partition has only 1 occurrence.
        let ir = make_ir(
            "Mixed",
            vec![
                AbiFunction {
                    name: "getInfo".to_string(),
                    inputs: vec![AbiParam {
                        name: "id".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    }],
                    outputs: vec![AbiParam {
                        name: "".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    }],
                    state_mutability: StateMutability::View,
                    natspec: None,
                },
                AbiFunction {
                    name: "getInfo".to_string(),
                    inputs: vec![AbiParam {
                        name: "data".to_string(),
                        ty: SolType::Bytes,
                        internal_type: None,
                    }],
                    outputs: vec![],
                    state_mutability: StateMutability::NonPayable,
                    natspec: None,
                },
            ],
            vec![],
        );
        let out = render_python_file(&ir);
        // Each partition has only 1 getInfo, so no suffix needed
        assert!(
            out.contains("def get_info(self, id: int) -> int"),
            "View getInfo should not have suffix, got:\n{out}"
        );
        assert!(
            out.contains("def get_info(self, data: bytes)"),
            "Write getInfo should not have suffix, got:\n{out}"
        );
    }

    #[test]
    fn from_param_name_is_escaped() {
        let ir = make_ir(
            "Bridge",
            vec![AbiFunction {
                name: "transferFrom".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "from".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "to".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Bool,
                    internal_type: None,
                }],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
        );
        let out = render_python_file(&ir);
        assert!(
            out.contains("_from: ChecksumAddress"),
            "Expected `from` to be escaped as `_from`, got:\n{out}"
        );
        // `to` is not a Python keyword — must NOT be escaped
        assert!(
            out.contains(", to: ChecksumAddress"),
            "Expected `to` to remain unescaped, got:\n{out}"
        );
    }

    #[test]
    fn python_keywords_escaped_after_snake_case() {
        // camelCase "From" becomes "from" after snake_case — must still be escaped
        assert_eq!(python_safe_param_name("from", 0), "_from");
        assert_eq!(python_safe_param_name("lambda", 0), "_lambda");
        assert_eq!(python_safe_param_name("yield", 0), "_yield");
        assert_eq!(python_safe_param_name("nonlocal", 0), "_nonlocal");
        // Non-keyword should pass through unchanged
        assert_eq!(python_safe_param_name("amount", 0), "amount");
        assert_eq!(python_safe_param_name("to", 0), "to");
    }

    #[test]
    fn tuple_param_no_inline_comment() {
        let ir = make_ir(
            "Router",
            vec![AbiFunction {
                name: "swap".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "path".to_string(),
                        ty: SolType::Tuple(vec![
                            abi_typegen_core::types::TupleComponent {
                                name: "tokenIn".to_string(),
                                ty: SolType::Address,
                                internal_type: None,
                            },
                            abi_typegen_core::types::TupleComponent {
                                name: "tokenOut".to_string(),
                                ty: SolType::Address,
                                internal_type: None,
                            },
                        ]),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
        );
        let out = render_python_file(&ir);
        // The function signature must be on one line with no inline comment
        assert!(
            out.contains(
                "def swap(self, path: dict[str, Any], amount: int) -> dict[str, Any]: ..."
            ),
            "Tuple param should render as `dict[str, Any]` without inline comment, got:\n{out}"
        );
    }

    #[test]
    fn tuple_return_type_no_inline_comment() {
        let ir = make_ir(
            "Vault",
            vec![AbiFunction {
                name: "getPosition".to_string(),
                inputs: vec![AbiParam {
                    name: "id".to_string(),
                    ty: SolType::Uint(256),
                    internal_type: None,
                }],
                outputs: vec![
                    AbiParam {
                        name: "shares".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "data".to_string(),
                        ty: SolType::Tuple(vec![abi_typegen_core::types::TupleComponent {
                            name: "x".to_string(),
                            ty: SolType::Uint(256),
                            internal_type: None,
                        }]),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_python_file(&ir);
        assert!(
            out.contains("-> tuple[int, dict[str, Any]]: ..."),
            "Tuple in return type should have no inline comment, got:\n{out}"
        );
    }

    #[test]
    fn no_functions_still_valid() {
        let ir = make_ir(
            "Empty",
            vec![],
            vec![AbiEvent {
                name: "Ping".to_string(),
                inputs: vec![AbiEventParam {
                    name: "sender".to_string(),
                    ty: SolType::Address,
                    indexed: true,
                    internal_type: None,
                }],
                anonymous: false,
                natspec: None,
            }],
        );
        let out = render_python_file(&ir);
        assert!(
            out.contains("class EmptyContract:"),
            "Expected class even with no functions, got:\n{out}"
        );
        // Should not contain view/write section headers
        assert!(
            !out.contains("# View/pure functions"),
            "Should not have view section with no functions"
        );
    }
}
