//! Event table bindings for q/kdb+.
use abi_typegen_core::types::ContractIr;
/// Generated q source and its optional shared C adapter.
pub struct QArtifacts {
    /// Contract ABI, schemas, and optional decoders.
    pub source: String,
    /// Shared q C adapter, empty when wrappers are disabled.
    pub bridge: String,
}
/// Shared q extension source; compile with the official k.h and shared ABI runtime.
pub const RUNTIME_BRIDGE: &str = include_str!("q/abi_typegen_q.c");

fn identifier(value: &str) -> String {
    value.chars().filter(char::is_ascii_alphanumeric).collect()
}

/// Namespace used by a generated contract, including its leading dot.
pub fn namespace_name(name: &str) -> String {
    format!(".atg{}", identifier(name))
}

fn literal(value: &str) -> String {
    // q accepts octal escapes, but not JSON's Unicode escapes.
    let mut out = String::from("\"");
    for byte in value.bytes() {
        match byte {
            b'"' => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            32..=126 => out.push(char::from(byte)),
            _ => out.push_str(&format!("\\{byte:03o}")),
        }
    }
    out.push('"');
    out
}

fn list(items: &[String]) -> String {
    match items {
        [] => "()".into(),
        [item] => format!("enlist {item}"),
        _ => format!("({})", items.join(";")),
    }
}

fn conversion(ty: &abi_typegen_core::types::SolType, value: &str) -> String {
    use abi_typegen_core::types::SolType;
    match ty {
        SolType::Address => format!("12_({value})"),
        SolType::StringType => format!("\"c\"$({value})"),
        SolType::Uint(_)
        | SolType::Int(_)
        | SolType::Bool
        | SolType::Bytes
        | SolType::BytesN(_) => value.into(),
        SolType::Array(inner) | SolType::FixedArray(inner, _) => {
            format!("{{{}}} each ({value})", conversion(inner, "x"))
        }
        SolType::Tuple(fields) => list(
            &fields
                .iter()
                .enumerate()
                .map(|(i, f)| conversion(&f.ty, &format!("({value})[{i}]")))
                .collect::<Vec<_>>(),
        ),
    }
}

/// Render event schemas and optional log decoders; no RPC or indexing service is generated.
pub fn render_q_artifacts(ir: &ContractIr, wrappers: bool) -> QArtifacts {
    let ns = namespace_name(&ir.name);
    let abi = serde_json::to_string(&ir.raw_abi).expect("ABI JSON serializes");
    let mut source = format!(
        "/ Generated by abi-typegen: event tables for q/kdb+.\n/ Integers are lossless 32-byte big-endian words; signed integers use two's complement.\n/ Addresses are 20 bytes; hashes are 32 bytes; strings are UTF-8 char vectors.\n/ Arrays and tuples are nested general lists in ABI order. Indexed complex values remain hashes.\n/ Decoder rejects values nested beyond 64 containers.\n/ Metadata is supplied by the caller; no RPC, persistence, or reorg policy is implied.\n{ns}.abi:{};\n",
        literal(&abi)
    );
    if wrappers {
        source.push_str(&format!("/ Build abi_typegen_q.c with k.h and libabi_typegen_runtime; load explicitly before decoding.\n{ns}.loadBridge:{{[path] {ns}.nativeDecode:path 2:(`atg_q_decode;1);}};\n"));
    }
    let metadata = "`chainId`contract`blockNumber`blockHash`transactionHash`logIndex`removed";
    source.push_str(&format!("{ns}.metadataColumns:{metadata};\n"));
    for (index, event) in ir.events.iter().enumerate() {
        let name = format!("e{index}{}", identifier(&event.name));
        let fields: Vec<_> = event
            .inputs
            .iter()
            .enumerate()
            .map(|(i, field)| format!("f{i}{}", identifier(&field.name)))
            .collect();
        let signature = format!(
            "{}({})",
            event.name,
            event
                .inputs
                .iter()
                .map(|f| f.ty.canonical())
                .collect::<Vec<_>>()
                .join(",")
        );
        source.push_str(&format!(
            "{ns}.{name}Signature:{};\n{ns}.{name}Anonymous:{}b;\n",
            literal(&signature),
            u8::from(event.anonymous)
        ));
        source.push_str(&format!(
            "{ns}.{name}Types:{};\n",
            list(
                &event
                    .inputs
                    .iter()
                    .map(|f| literal(&f.ty.canonical()))
                    .collect::<Vec<_>>()
            )
        ));
        source.push_str(&format!(
            "{ns}.{name}Names:{};\n",
            list(
                &event
                    .inputs
                    .iter()
                    .map(|f| {
                        let value = literal(&f.name);
                        // q parses a one-byte quoted value as a character atom.
                        if f.name.len() == 1 {
                            format!("(enlist {value})")
                        } else {
                            value
                        }
                    })
                    .collect::<Vec<_>>()
            )
        ));
        source.push_str(&format!(
            "{ns}.{name}Indexed:{};\n",
            list(
                &event
                    .inputs
                    .iter()
                    .map(|f| format!("{}b", u8::from(f.indexed)))
                    .collect::<Vec<_>>()
            )
        ));
        source.push_str(&format!("{ns}.{name}Table:([]chainId:();contract:();blockNumber:();blockHash:();transactionHash:();logIndex:();removed:`boolean$(){});\n", fields.iter().map(|f| format!(";{f}:()")).collect::<String>()));
        if wrappers {
            let values: Vec<_> = event
                .inputs
                .iter()
                .enumerate()
                .map(|(i, field)| {
                    let value = format!("v[{i}]");
                    if field.indexed
                        && matches!(
                            field.ty,
                            abi_typegen_core::types::SolType::Array(_)
                                | abi_typegen_core::types::SolType::FixedArray(_, _)
                                | abi_typegen_core::types::SolType::Tuple(_)
                                | abi_typegen_core::types::SolType::StringType
                                | abi_typegen_core::types::SolType::Bytes
                        )
                    {
                        value
                    } else {
                        conversion(&field.ty, &value)
                    }
                })
                .collect();
            let columns = if fields.is_empty() {
                "`symbol$()".to_string()
            } else {
                format!("`{}", fields.join("`"))
            };
            // Explicit signature selection also supports anonymous and overloaded events.
            source.push_str(&format!("{ns}.{name}Decode:{{[topics;data] v:{ns}.nativeDecode[({ns}.abi;{ns}.{name}Signature;topics;data)];{list}}};\n", list=list(&values)));
            source.push_str(&format!("{ns}.{name}Row:{{[metadata;topics;data] if[99h<>type metadata;'\"metadata must be a dictionary\"];if[not all {ns}.metadataColumns in key metadata;'\"missing log metadata\"];if[-1h<>type metadata`removed;'\"removed must be boolean\"];({ns}.metadataColumns,{columns})!((metadata {ns}.metadataColumns),{ns}.{name}Decode[topics;data])}};\n"));
        }
    }
    QArtifacts {
        source,
        bridge: if wrappers {
            RUNTIME_BRIDGE.into()
        } else {
            String::new()
        },
    }
}
