use crate::type_mapper::{overload_suffix, safe_param_name, struct_name_from_internal_type};
use abi_typegen_core::types::{AbiFunction, ContractIr, SolType, StateMutability, TupleComponent};
use heck::{ToShoutySnakeCase, ToSnakeCase};
use std::collections::{HashMap, HashSet};

/// Generates `<ContractName>.rb` -- a Ruby binding stub shaped like the Python backend.
pub fn render_ruby_file(ir: &ContractIr) -> String {
    render_ruby_file_inner(ir, false, true)
}

/// Generates Ruby ABI metadata and optionally callable `eth` gem wrappers.
pub fn render_ruby_file_with_wrappers(ir: &ContractIr, wrappers: bool) -> String {
    render_ruby_file_inner(ir, wrappers, false)
}

/// Returns every top-level Ruby constant declared by a generated contract file.
///
/// Callers can compare these names across files before writing a shared output directory.
pub fn declared_constant_names(ir: &ContractIr, wrappers: bool) -> Vec<String> {
    let mut names = vec![ruby_abi_name(&ir.name)];
    names.extend(collect_tuple_structs(ir).into_iter().map(|(name, _)| name));
    if wrappers {
        names.push(ruby_contract_name(&ir.name));
    }
    names
}

fn ruby_abi_name(name: &str) -> String {
    let mut base = name.to_shouty_snake_case();
    if base.is_empty() || !base.starts_with(|c: char| c.is_ascii_alphabetic()) {
        base = format!("CONTRACT_{base}");
    }
    format!("{base}_ABI")
}

fn render_ruby_file_inner(ir: &ContractIr, wrappers: bool, legacy_stub: bool) -> String {
    let mut out = String::new();
    let name = &ir.name;
    let contract_name = ruby_contract_name(name);
    let abi_name = ruby_abi_name(name);

    out.push_str("# frozen_string_literal: true\n\n");
    out.push_str("# Auto-generated by abi-typegen. Do not edit manually.\n");
    out.push_str(&format!(
        "# {} for the {} contract.\n\n",
        if wrappers {
            "Ruby eth.rb bindings"
        } else {
            "Ruby ABI metadata"
        },
        name
    ));
    out.push_str("require \"json\"\n");
    if wrappers || legacy_stub {
        out.push_str("require \"eth\"\n");
    }
    out.push('\n');

    let abi_json = serde_json::to_string_pretty(&ir.raw_abi).unwrap_or_else(|_| "[]".into());
    out.push_str(&format!("{abi_name} = JSON.parse(<<~'ABI_JSON').freeze\n"));
    for line in abi_json.lines() {
        out.push_str("  ");
        out.push_str(line);
        out.push('\n');
    }
    out.push_str("ABI_JSON\n\n");

    // Ruby has no built-in structural type declarations like Python's TypedDict,
    // so emit lightweight keyword Structs for named tuples. They are accepted by
    // generated encoders through the recursive `_abi_value` helper.
    let tuple_structs = collect_tuple_structs(ir);
    for (class_name, fields) in &tuple_structs {
        if fields.is_empty() {
            out.push_str(&format!(
                "class {class_name}\n  def to_abi\n    []\n  end\nend\n\n"
            ));
        } else {
            let symbols = fields
                .iter()
                .map(|field| format!(":{field}"))
                .collect::<Vec<_>>()
                .join(", ");
            let values = fields.join(", ");
            out.push_str(&format!(
                "{class_name} = Struct.new({symbols}, keyword_init: true) do\n  def to_abi\n    [{values}]\n  end\nend\n\n"
            ));
        }
    }

    if !wrappers && !legacy_stub {
        return out;
    }

    out.push_str(&format!("class {contract_name}\n"));
    if let Some(ref natspec) = ir.natspec {
        if let Some(ref notice) = natspec.notice {
            out.push_str(&format!("  # {}\n", notice.replace('\n', " ").trim()));
        }
    }
    out.push_str(&format!("  ABI = {abi_name}\n"));

    // Metadata constants are cheap in Ruby and make the generated surface useful
    // even without a live client.
    let mut constants = crate::naming::Scope::with_reserved(["ABI"]);
    for (function, suffix) in ir
        .functions
        .iter()
        .zip(overload_indices_by_name(&ir.functions))
    {
        let suffix = suffix.map(|i| format!("_{i}")).unwrap_or_default();
        let base = constants.claim_family(
            &format!("{}{}", ruby_constant_stem(&function.name), suffix),
            &["_SIGNATURE", "_SELECTOR"],
        );
        out.push_str(&format!(
            "  {base}_SIGNATURE = {}.freeze\n  {base}_SELECTOR = {}.freeze\n",
            ruby_string(&function.signature()),
            ruby_string(&function.selector().to_string())
        ));
    }
    for (event, suffix) in ir.events.iter().zip(repeat_indices_by_name(
        ir.events.iter().map(|event| event.name.as_str()),
    )) {
        let suffix = suffix.map(|i| format!("_{i}")).unwrap_or_default();
        let base = constants.claim_family(
            &format!("{}{}", ruby_constant_stem(&event.name), suffix),
            &["_EVENT_SIGNATURE", "_EVENT_TOPIC"],
        );
        out.push_str(&format!(
            "  {base}_EVENT_SIGNATURE = {}.freeze\n",
            ruby_string(&event.signature())
        ));
        if !event.anonymous {
            out.push_str(&format!(
                "  {base}_EVENT_TOPIC = {}.freeze\n",
                ruby_string(&event.topic0().to_string())
            ));
        }
    }
    for (error, suffix) in ir.errors.iter().zip(repeat_indices_by_name(
        ir.errors.iter().map(|error| error.name.as_str()),
    )) {
        let suffix = suffix.map(|i| format!("_{i}")).unwrap_or_default();
        let base = constants.claim_family(
            &format!("{}{}", ruby_constant_stem(&error.name), suffix),
            &["_ERROR_SIGNATURE", "_ERROR_SELECTOR"],
        );
        out.push_str(&format!(
            "  {base}_ERROR_SIGNATURE = {}.freeze\n  {base}_ERROR_SELECTOR = {}.freeze\n",
            ruby_string(&error.signature()),
            ruby_string(&error.selector().to_string())
        ));
    }

    out.push_str("\n  attr_reader :address, :client, :contract\n\n");
    out.push_str("  def initialize(address, client)\n");
    out.push_str("    @address = Eth::Address.new(address.to_s).to_s\n");
    out.push_str("    @client = client\n");
    out.push_str(&format!(
        "    @contract = Eth::Contract.from_abi(abi: ABI, address: @address, name: {})\n",
        ruby_string(name)
    ));
    out.push_str("    @functions_by_signature = {}\n    @events_by_signature = {}\n    @errors_by_signature = {}\n  end\n");

    let wrapper_names = ruby_function_names(ir);
    let mut view_functions = Vec::new();
    let mut write_functions = Vec::new();
    for function in &ir.functions {
        match function.state_mutability {
            StateMutability::Pure | StateMutability::View => view_functions.push(function),
            _ => write_functions.push(function),
        }
    }

    if !view_functions.is_empty() {
        out.push_str("\n  # View/pure functions\n");
        for function in &view_functions {
            let index = ir
                .functions
                .iter()
                .position(|candidate| std::ptr::eq(candidate, *function))
                .expect("function belongs to IR");
            let method = if wrappers {
                wrapper_names[index].clone()
            } else {
                resolve_legacy_method_name(function, &view_functions)
            };
            out.push_str(&render_view_function(&method, function, wrappers));
        }
    }

    if !write_functions.is_empty() {
        out.push_str("\n  # Write functions\n");
        for function in &write_functions {
            let index = ir
                .functions
                .iter()
                .position(|candidate| std::ptr::eq(candidate, *function))
                .expect("function belongs to IR");
            let method = if wrappers {
                wrapper_names[index].clone()
            } else {
                resolve_legacy_method_name(function, &write_functions)
            };
            out.push_str(&render_write_function(&method, function, wrappers));
        }
    }

    if wrappers {
        out.push_str(&render_wrapper_extras(ir));
        out.push_str(RUNTIME_HELPERS);
    }

    out.push_str("end\n");
    out
}

fn render_view_function(method: &str, function: &AbiFunction, wrappers: bool) -> String {
    let names = ruby_param_names(function.inputs.iter().map(|param| param.name.as_str()));
    let params = names.join(", ");
    let params = if params.is_empty() {
        String::new()
    } else {
        format!("({params})")
    };
    if wrappers {
        return format!(
            "\n  # Calls `{signature}` through Eth::Client#eth_call.\n  def {method}{params}\n    data = encode_{method}{params}\n    result = @client.eth_call(to: @address, data: data).fetch(\"result\")\n    decode_{method}_result(result)\n  end\n",
            signature = function.signature()
        );
    }

    let doc = natspec_comment(function)
        .map(|doc| format!("  # {doc}\n"))
        .unwrap_or_default();
    format!("\n{doc}  def {method}{params}\n    raise NotImplementedError\n  end\n")
}

fn render_write_function(method: &str, function: &AbiFunction, wrappers: bool) -> String {
    let names = ruby_param_names(function.inputs.iter().map(|param| param.name.as_str()));
    if wrappers {
        let mut args = names.clone();
        args.push("transaction = {}".into());
        let args = args.join(", ");
        let call_args = names.join(", ");
        let encoded = if call_args.is_empty() {
            format!("encode_{method}")
        } else {
            format!("encode_{method}({call_args})")
        };
        let guard = if matches!(function.state_mutability, StateMutability::NonPayable) {
            "    value = transaction.fetch(:value, transaction.fetch(\"value\", 0))\n    raise ArgumentError, \"Function is not payable\" unless value.is_a?(Integer) && value.zero?\n"
        } else {
            "    value = transaction.fetch(:value, transaction.fetch(\"value\", 0))\n    raise ArgumentError, \"Transaction value must be a nonnegative Integer\" unless value.is_a?(Integer) && value >= 0\n"
        };
        return format!(
            "\n  # Builds a transaction Hash for `{signature}`; signing/sending stays with the caller.\n  def {method}({args})\n{guard}    transaction.merge(to: @address, data: {encoded}, value: value)\n  end\n",
            signature = function.signature()
        );
    }

    let params = if names.is_empty() {
        String::new()
    } else {
        format!("({})", names.join(", "))
    };
    let doc = natspec_comment(function)
        .map(|doc| format!("  # {doc}\n"))
        .unwrap_or_default();
    format!("\n{doc}  def {method}{params}\n    raise NotImplementedError\n  end\n")
}

fn render_wrapper_extras(ir: &ContractIr) -> String {
    let mut out = String::new();

    for (function, method) in ir.functions.iter().zip(ruby_function_names(ir)) {
        let signature = function.signature();
        let names = ruby_param_names(function.inputs.iter().map(|param| param.name.as_str()));
        let params = names.join(", ");
        let args = names
            .iter()
            .map(|name| format!("_abi_value({name})"))
            .collect::<Vec<_>>()
            .join(", ");
        let declaration = if params.is_empty() {
            String::new()
        } else {
            format!("({params})")
        };
        out.push_str(&format!(
            "\n  # Encodes `{signature}` calldata without RPC.\n  def encode_{method}{declaration}\n    function = _function({sig})\n    encoded = Eth::Abi.encode(function.inputs.map(&:parsed_type), [{args}])\n    Eth::Util.prefix_hex(function.signature + Eth::Util.bin_to_hex(encoded))\n  end\n",
            sig = ruby_string(&signature)
        ));

        if function.outputs.is_empty() {
            out.push_str(&format!(
                "\n  # Decodes `{signature}` output without RPC.\n  def decode_{method}_result(data)\n    raise ArgumentError, \"Unexpected output for void function\" unless data.nil? || data == \"\" || data == \"0x\"\n    nil\n  end\n"
            ));
        } else {
            out.push_str(&format!(
                "\n  # Decodes `{signature}` output without RPC and rejects non-canonical ABI data.\n  def decode_{method}_result(data)\n    function = _function({sig})\n    values = function.decode_call_result(data) || []\n    _assert_canonical(function.outputs.map(&:parsed_type), values, data)\n    {}\n  end\n",
                if function.outputs.len() == 1 { "values[0]" } else { "values" },
                sig = ruby_string(&signature)
            ));
        }
    }

    for (event, stem) in ir.events.iter().zip(ruby_event_names(ir)) {
        let signature = event.signature();
        let indexed = event
            .inputs
            .iter()
            .filter(|param| param.indexed)
            .collect::<Vec<_>>();
        let indexed_names = ruby_param_names(indexed.iter().map(|param| param.name.as_str()));
        let mut filter_params = vec![
            "from_block: 0".to_string(),
            "to_block: \"latest\"".to_string(),
        ];
        for name in &indexed_names {
            filter_params.push(format!("{name}: nil"));
        }
        let topic_zero = if event.anonymous {
            "[]".to_string()
        } else {
            format!("[{}]", ruby_string(&event.topic0().to_string()))
        };
        let nonindexed_types = event
            .inputs
            .iter()
            .filter(|param| !param.indexed)
            .map(|param| ruby_string(&param.ty.canonical()))
            .collect::<Vec<_>>()
            .join(", ");
        let field_names = ruby_param_names(event.inputs.iter().map(|param| param.name.as_str()));
        let mut decoded_fields = String::new();
        let mut topic_index = usize::from(!event.anonymous);
        let mut data_index = 0usize;
        for (param, field_name) in event.inputs.iter().zip(field_names) {
            let value = if param.indexed {
                let current = topic_index;
                topic_index += 1;
                if indexed_hash(&param.ty) {
                    format!("topics[{current}]")
                } else {
                    format!(
                        "Eth::Abi.decode([{}], topics[{current}])[0]",
                        ruby_string(&param.ty.canonical())
                    )
                }
            } else {
                let current = data_index;
                data_index += 1;
                format!("values[{current}]")
            };
            decoded_fields.push_str(&format!(
                "    decoded[{}] = {value}\n",
                ruby_string(&field_name)
            ));
        }
        out.push_str(&format!(
            "\n  # Decodes one `{signature}` receipt/log entry. Indexed reference values are topic hashes.\n  def decode_{stem}_log(log)\n    raise ArgumentError, \"Invalid log\" unless log.is_a?(Hash)\n    topics = log[\"topics\"] || log[:topics] || []\n    data = log[\"data\"] || log[:data] || \"0x\"\n    raise ArgumentError, \"Invalid event topics\" unless topics.is_a?(Array) && topics.all? {{ |topic| topic.is_a?(String) && topic.match?(/\\A0x[0-9a-fA-F]{{64}}\\z/) }}\n{}    raise ArgumentError, \"Incorrect event topic count\" unless topics.length == {topic_index}\n    types = [{nonindexed_types}]\n    values = Eth::Abi.decode(types, data)\n    _assert_canonical(types, values, data)\n    decoded = {{}}\n{decoded_fields}    decoded\n  end\n",
            if event.anonymous {
                String::new()
            } else {
                format!(
                    "    return nil if topics.empty? || !topics[0].casecmp?({})\n",
                    ruby_string(&event.topic0().to_string())
                )
            },
        ));

        let mut topic_lines = String::new();
        for ((param, name), _index) in indexed.iter().zip(&indexed_names).zip(0usize..) {
            let canonical = param.ty.canonical();
            if indexed_hash(&param.ty) {
                let helper = match param.ty {
                    SolType::StringType => "_topic_hash_string",
                    SolType::Bytes => "_topic_hash_bytes",
                    SolType::Array(_) | SolType::FixedArray(_, _) | SolType::Tuple(_) => {
                        "_topic_hash_preencoded"
                    }
                    _ => unreachable!("indexed hash helper only for reference-like types"),
                };
                topic_lines.push_str(&format!(
                    "    topics << ({name}.nil? ? nil : {helper}({name}))\n"
                ));
            } else {
                topic_lines.push_str(&format!(
                    "    topics << ({name}.nil? ? nil : Eth::Util.bin_to_prefixed_hex(Eth::Abi.encode([{}], [_abi_value({name})])))\n",
                    ruby_string(&canonical)
                ));
            }
        }
        out.push_str(&format!(
            "\n  # Retrieves and decodes `{signature}` logs. Indexed reference-type filters may be supplied\n  # either as their 32-byte topic hash or as the original String/bytes value.\n  def filter_{stem}({params})\n    topics = {topic_zero}\n{topic_lines}    filter = {{ address: @address, from_block: from_block, to_block: to_block, topics: topics }}\n    logs = @client.eth_get_logs(filter).fetch(\"result\")\n    logs.filter_map {{ |log| decode_{stem}_log(log) }}\n  end\n",
            params = filter_params.join(", ")
        ));
    }

    for (error, stem) in ir.errors.iter().zip(ruby_error_names(ir)) {
        out.push_str(&format!(
            "\n  # Decodes `{signature}` custom error arguments, or nil for another selector.\n  def decode_{stem}_error(data)\n    return nil unless data.is_a?(String) && data.length >= 10 && data[0, 10].casecmp?({selector})\n    error = _error({sig})\n    types = error.inputs.map(&:parsed_type)\n    payload = \"0x#{{data[10..]}}\"\n    values = Eth::Abi.decode(types, payload)\n    _assert_canonical(types, values, payload)\n    values\n  end\n",
            signature = error.signature(),
            selector = ruby_string(&error.selector().to_string()),
            sig = ruby_string(&error.signature())
        ));
    }

    if let Some(constructor) = &ir.constructor {
        let names = ruby_param_names(constructor.inputs.iter().map(|param| param.name.as_str()));
        let mut params = names.clone();
        params.push("transaction = {}".into());
        let args = names
            .iter()
            .map(|name| format!("_class_abi_value({name})"))
            .collect::<Vec<_>>()
            .join(", ");
        let types = constructor
            .inputs
            .iter()
            .map(|param| ruby_string(&param.ty.canonical()))
            .collect::<Vec<_>>()
            .join(", ");
        let guard = if matches!(constructor.state_mutability, StateMutability::NonPayable) {
            "    value = transaction.fetch(:value, transaction.fetch(\"value\", 0))\n    raise ArgumentError, \"Constructor is not payable\" unless value.is_a?(Integer) && value.zero?\n"
        } else {
            "    value = transaction.fetch(:value, transaction.fetch(\"value\", 0))\n    raise ArgumentError, \"Transaction value must be a nonnegative Integer\" unless value.is_a?(Integer) && value >= 0\n"
        };
        out.push_str(&format!(
            "\n  # Builds a deployment transaction with caller-supplied bytecode.\n  def self.build_deployment(bytecode, {params})\n{guard}    code = bytecode.to_s.sub(/\\A0x/i, \"\")\n    encoded = Eth::Abi.encode([{types}], [{args}])\n    transaction.merge(data: \"0x#{{code}}#{{Eth::Util.bin_to_hex(encoded)}}\", value: value)\n  end\n",
            params = params.join(", ")
        ));
    }

    out
}

fn resolve_legacy_method_name(function: &AbiFunction, partition: &[&AbiFunction]) -> String {
    let count = partition
        .iter()
        .filter(|candidate| candidate.name == function.name)
        .count();
    let snake = function.name.to_snake_case();
    if count > 1 {
        let suffix = overload_suffix(&function.inputs).to_snake_case();
        if suffix.is_empty() {
            snake
        } else {
            format!("{snake}_{suffix}")
        }
    } else {
        snake
    }
}

fn ruby_function_names(ir: &ContractIr) -> Vec<String> {
    let mut counts = HashMap::new();
    for function in &ir.functions {
        *counts.entry(function.name.as_str()).or_insert(0usize) += 1;
    }
    let mut used = HashSet::from([
        "initialize".to_string(),
        "build_deployment".to_string(),
        "contract".to_string(),
        "client".to_string(),
        "address".to_string(),
    ]);
    used.extend(RUNTIME_METHOD_NAMES.iter().map(|name| (*name).to_string()));
    ir.functions
        .iter()
        .map(|function| {
            let mut base = function.name.to_snake_case();
            if counts.get(function.name.as_str()).copied().unwrap_or(1) > 1 {
                let suffix = overload_suffix(&function.inputs).to_snake_case();
                if !suffix.is_empty() {
                    base = format!("{base}_{suffix}");
                }
            }
            let base = ruby_safe_method_name(&base);
            let mut candidate = base.clone();
            let mut index = 2;
            while used.contains(&candidate)
                || used.contains(&format!("encode_{candidate}"))
                || used.contains(&format!("decode_{candidate}_result"))
            {
                candidate = format!("{base}_{index}");
                index += 1;
            }
            used.insert(candidate.clone());
            used.insert(format!("encode_{candidate}"));
            used.insert(format!("decode_{candidate}_result"));
            candidate
        })
        .collect()
}

fn ruby_event_names(ir: &ContractIr) -> Vec<String> {
    let mut used = HashSet::new();
    for name in ruby_function_names(ir) {
        used.insert(name.clone());
        used.insert(format!("encode_{name}"));
        used.insert(format!("decode_{name}_result"));
    }
    ir.events
        .iter()
        .map(|event| {
            let base = ruby_safe_method_name(&event.name.to_snake_case());
            let mut candidate = base.clone();
            let mut index = 2;
            while used.contains(&format!("filter_{candidate}"))
                || used.contains(&format!("decode_{candidate}_log"))
            {
                candidate = format!("{base}_{index}");
                index += 1;
            }
            used.insert(format!("filter_{candidate}"));
            used.insert(format!("decode_{candidate}_log"));
            candidate
        })
        .collect()
}

fn ruby_error_names(ir: &ContractIr) -> Vec<String> {
    let mut used = HashSet::new();
    for name in ruby_function_names(ir) {
        used.insert(name.clone());
        used.insert(format!("encode_{name}"));
        used.insert(format!("decode_{name}_result"));
    }
    for name in ruby_event_names(ir) {
        used.insert(format!("filter_{name}"));
        used.insert(format!("decode_{name}_log"));
    }
    ir.errors
        .iter()
        .map(|error| {
            let base = ruby_safe_method_name(&error.name.to_snake_case());
            let mut candidate = base.clone();
            let mut index = 2;
            while used.contains(&format!("decode_{candidate}_error")) {
                candidate = format!("{base}_{index}");
                index += 1;
            }
            used.insert(format!("decode_{candidate}_error"));
            candidate
        })
        .collect()
}

fn ruby_param_names<'a>(names: impl Iterator<Item = &'a str>) -> Vec<String> {
    let mut scope = crate::naming::Scope::default();
    for reserved in [
        "client",
        "contract",
        "address",
        "transaction",
        "bytecode",
        "from_block",
        "to_block",
        "data",
        "topics",
        "value",
    ] {
        scope.claim(reserved);
    }
    names
        .enumerate()
        .map(|(index, name)| scope.claim(&ruby_safe_param_name(name, index)))
        .collect()
}

fn ruby_safe_param_name(name: &str, index: usize) -> String {
    let base = safe_param_name(name, index).to_snake_case();
    let base = if base.is_empty() || base.starts_with(|c: char| c.is_ascii_digit()) {
        format!("arg{index}")
    } else {
        base
    };
    if RUBY_KEYWORDS.contains(&base.as_str()) {
        format!("{base}_")
    } else {
        base
    }
}

fn ruby_safe_method_name(name: &str) -> String {
    if name.is_empty() || name.starts_with(|c: char| c.is_ascii_digit()) {
        format!("method_{name}")
    } else if RUBY_KEYWORDS.contains(&name) || name == "initialize" {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

fn ruby_constant_stem(name: &str) -> String {
    let stem = name.to_shouty_snake_case();
    if stem.is_empty() || !stem.starts_with(|c: char| c.is_ascii_alphabetic()) {
        format!("METHOD_{stem}")
    } else {
        stem
    }
}

fn ruby_contract_name(name: &str) -> String {
    let exported = crate::naming::exported(name);
    if exported.is_empty() {
        return "ContractBinding".into();
    }
    format!("{exported}Contract")
}

fn natspec_comment(function: &AbiFunction) -> Option<String> {
    function
        .natspec
        .as_ref()?
        .notice
        .as_ref()
        .map(|notice| notice.replace('\n', " ").trim().to_string())
}

fn collect_tuple_structs(ir: &ContractIr) -> Vec<(String, Vec<String>)> {
    let mut structs = Vec::new();
    let mut seen = HashSet::new();
    let mut used = HashSet::from([ruby_abi_name(&ir.name), ruby_contract_name(&ir.name)]);
    for function in &ir.functions {
        for param in function.inputs.iter().chain(function.outputs.iter()) {
            collect_tuple_from_type(
                ir,
                &param.name,
                &param.ty,
                param.internal_type.as_deref(),
                &mut seen,
                &mut used,
                &mut structs,
            );
        }
    }
    for event in &ir.events {
        for param in &event.inputs {
            collect_tuple_from_type(
                ir,
                &param.name,
                &param.ty,
                param.internal_type.as_deref(),
                &mut seen,
                &mut used,
                &mut structs,
            );
        }
    }
    for error in &ir.errors {
        for param in &error.inputs {
            collect_tuple_from_type(
                ir,
                &param.name,
                &param.ty,
                param.internal_type.as_deref(),
                &mut seen,
                &mut used,
                &mut structs,
            );
        }
    }
    structs
}

fn collect_tuple_from_type(
    ir: &ContractIr,
    fallback_name: &str,
    ty: &SolType,
    internal: Option<&str>,
    seen: &mut HashSet<String>,
    used: &mut HashSet<String>,
    structs: &mut Vec<(String, Vec<String>)>,
) {
    match ty {
        SolType::Tuple(components) => {
            let struct_name = internal
                .and_then(struct_name_from_internal_type)
                .unwrap_or(fallback_name);
            if !struct_name.is_empty() {
                let base = format!(
                    "{}{}",
                    crate::naming::exported(&ir.name),
                    crate::naming::exported(struct_name)
                );
                let identity = format!("{internal:?}:{ty:?}");
                if seen.insert(identity) {
                    let mut class_name = base.clone();
                    let mut suffix = 2;
                    while used.contains(&class_name) {
                        class_name = format!("{base}{suffix}");
                        suffix += 1;
                    }
                    used.insert(class_name.clone());
                    structs.push((class_name, ruby_tuple_fields(components)));
                }
            }
            for component in components {
                collect_tuple_from_type(
                    ir,
                    &component.name,
                    &component.ty,
                    component.internal_type.as_deref(),
                    seen,
                    used,
                    structs,
                );
            }
        }
        SolType::Array(inner) | SolType::FixedArray(inner, _) => {
            collect_tuple_from_type(ir, fallback_name, inner, internal, seen, used, structs);
        }
        _ => {}
    }
}

fn ruby_tuple_fields(components: &[TupleComponent]) -> Vec<String> {
    let mut scope = crate::naming::Scope::default();
    components
        .iter()
        .enumerate()
        .map(|(index, component)| scope.claim(&ruby_safe_param_name(&component.name, index)))
        .collect()
}

fn indexed_hash(ty: &SolType) -> bool {
    matches!(
        ty,
        SolType::StringType
            | SolType::Bytes
            | SolType::Array(_)
            | SolType::FixedArray(_, _)
            | SolType::Tuple(_)
    )
}

fn ruby_string(value: &str) -> String {
    serde_json::to_string(value).expect("strings serialize")
}

fn overload_indices_by_name(functions: &[AbiFunction]) -> Vec<Option<usize>> {
    let mut counts = HashMap::new();
    for function in functions {
        *counts.entry(function.name.as_str()).or_insert(0usize) += 1;
    }
    let mut seen = HashMap::new();
    functions
        .iter()
        .map(|function| {
            if counts[function.name.as_str()] <= 1 {
                None
            } else {
                let index = seen.entry(function.name.as_str()).or_insert(0usize);
                *index += 1;
                Some(*index)
            }
        })
        .collect()
}

fn repeat_indices_by_name<'a>(names: impl Iterator<Item = &'a str>) -> Vec<Option<usize>> {
    let names = names.collect::<Vec<_>>();
    let mut counts = HashMap::new();
    for name in &names {
        *counts.entry(*name).or_insert(0usize) += 1;
    }
    let mut seen = HashMap::new();
    names
        .into_iter()
        .map(|name| {
            if counts[name] <= 1 {
                None
            } else {
                let index = seen.entry(name).or_insert(0usize);
                *index += 1;
                Some(*index)
            }
        })
        .collect()
}

const RUBY_KEYWORDS: &[&str] = &[
    "__ENCODING__",
    "__FILE__",
    "__LINE__",
    "alias",
    "and",
    "begin",
    "break",
    "case",
    "class",
    "def",
    "defined",
    "do",
    "else",
    "elsif",
    "end",
    "ensure",
    "false",
    "for",
    "if",
    "in",
    "module",
    "next",
    "nil",
    "not",
    "or",
    "redo",
    "rescue",
    "retry",
    "return",
    "self",
    "super",
    "then",
    "true",
    "undef",
    "unless",
    "until",
    "when",
    "while",
    "yield",
];

const RUNTIME_METHOD_NAMES: &[&str] = &[
    "_function",
    "_event",
    "_error",
    "_abi_value",
    "_assert_canonical",
    "_topic_hash_string",
    "_topic_hash_bytes",
    "_topic_hash_preencoded",
];

const RUNTIME_HELPERS: &str = r#"

  private

  def _function(signature)
    @functions_by_signature[signature] ||= begin
      found = @contract.functions.find { |function| function.function_string == signature }
      raise ArgumentError, "Unknown ABI function #{signature}" if found.nil?
      found
    end
  end

  def _event(signature)
    @events_by_signature[signature] ||= begin
      found = @contract.events.find { |event| event.event_string == signature }
      raise ArgumentError, "Unknown ABI event #{signature}" if found.nil?
      found
    end
  end

  def _error(signature)
    @errors_by_signature[signature] ||= begin
      found = @contract.errors.find { |error| error.error_string == signature }
      raise ArgumentError, "Unknown ABI error #{signature}" if found.nil?
      found
    end
  end

  def _abi_value(value)
    case value
    when Struct
      value.to_a.map { |item| _abi_value(item) }
    when Array
      value.map { |item| _abi_value(item) }
    when Eth::Address
      value.to_s
    else
      value.respond_to?(:to_abi) ? _abi_value(value.to_abi) : value
    end
  end

  def _assert_canonical(types, values, data)
    raw = Eth::Util.hex_to_bin(data)
    encoded = Eth::Abi.encode(types, values)
    raise ArgumentError, "Non-canonical ABI output" unless encoded == raw
  end

  def _topic_hash_string(value)
    raise ArgumentError, "Indexed string filter must be a String" unless value.is_a?(String)
    Eth::Util.bin_to_prefixed_hex(Eth::Util.keccak256(value))
  end

  def _topic_hash_bytes(value)
    raise ArgumentError, "Indexed bytes filter must be a String" unless value.is_a?(String)
    bytes = Eth::Util.hex?(value) ? Eth::Util.hex_to_bin(value) : value
    Eth::Util.bin_to_prefixed_hex(Eth::Util.keccak256(bytes))
  end

  def _topic_hash_preencoded(value)
    return value if value.is_a?(String) && value.match?(/\A0x[0-9a-fA-F]{64}\z/)
    raise ArgumentError, "Indexed array/tuple filters must be supplied as a 32-byte topic hash"
  end

  def self._class_abi_value(value)
    case value
    when Struct
      value.to_a.map { |item| _class_abi_value(item) }
    when Array
      value.map { |item| _class_abi_value(item) }
    when Eth::Address
      value.to_s
    else
      value.respond_to?(:to_abi) ? _class_abi_value(value.to_abi) : value
    end
  end
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;
    use abi_typegen_core::types::{AbiError, AbiEvent, AbiEventParam, AbiParam};

    fn erc20() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/erc20.json"),
        )
        .unwrap();
        parse_artifact("Token", &json).unwrap()
    }

    fn make_ir(name: &str, functions: Vec<AbiFunction>, events: Vec<AbiEvent>) -> ContractIr {
        ContractIr {
            name: name.to_string(),
            constructor: None,
            functions,
            events,
            errors: vec![],
            has_fallback: false,
            has_receive: false,
            natspec: None,
            raw_abi: serde_json::Value::Array(vec![]),
        }
    }

    #[test]
    fn contains_contract_and_abi() {
        let out = render_ruby_file(&erc20());
        assert!(out.contains("class TokenContract"), "{out}");
        assert!(out.contains("TOKEN_ABI = JSON.parse"), "{out}");
    }

    #[test]
    fn wrapper_uses_eth_gem_and_canonical_signatures() {
        let out = render_ruby_file_with_wrappers(&erc20(), true);
        assert!(out.contains("require \"eth\""), "{out}");
        assert!(out.contains("_function(\"balanceOf(address)\")"), "{out}");
        assert!(out.contains("def encode_transfer("), "{out}");
        assert!(out.contains("Eth::Abi.encode"), "{out}");
        assert!(out.contains("@client.eth_call"), "{out}");
    }

    #[test]
    fn no_wrappers_keeps_metadata_without_contract() {
        let out = render_ruby_file_with_wrappers(&erc20(), false);
        assert!(out.contains("TOKEN_ABI"), "{out}");
        assert!(!out.contains("class TokenContract"), "{out}");
    }

    #[test]
    fn function_names_are_snake_case_and_overload_safe() {
        let input = |name: &str, ty: SolType| AbiParam {
            name: name.into(),
            ty,
            internal_type: None,
        };
        let function = |ty: SolType| AbiFunction {
            name: "deposit".into(),
            inputs: vec![input("value", ty)],
            outputs: vec![],
            state_mutability: StateMutability::NonPayable,
            natspec: None,
        };
        let ir = make_ir(
            "Vault",
            vec![function(SolType::Uint(256)), function(SolType::Address)],
            vec![],
        );
        let out = render_ruby_file_with_wrappers(&ir, true);
        assert!(out.contains("def deposit_uint256("), "{out}");
        assert!(out.contains("def deposit_address("), "{out}");
    }

    #[test]
    fn ruby_keywords_and_runtime_names_are_escaped() {
        let ir = make_ir(
            "Bridge",
            vec![AbiFunction {
                name: "transferFrom".into(),
                inputs: vec![
                    AbiParam {
                        name: "class".into(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "transaction".into(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ruby_file_with_wrappers(&ir, true);
        assert!(out.contains("class_"), "{out}");
        assert!(out.contains("transaction2"), "{out}");
    }

    #[test]
    fn events_and_errors_get_offline_helpers() {
        let input = |name: &str, ty: SolType| AbiParam {
            name: name.into(),
            ty,
            internal_type: None,
        };
        let mut ir = make_ir(
            "Example",
            vec![],
            vec![AbiEvent {
                name: "Changed".into(),
                inputs: vec![AbiEventParam {
                    name: "owner".into(),
                    ty: SolType::Address,
                    indexed: true,
                    internal_type: None,
                }],
                anonymous: false,
                natspec: None,
            }],
        );
        ir.errors = vec![AbiError {
            name: "Denied".into(),
            inputs: vec![input("code", SolType::Uint(256))],
            natspec: None,
        }];
        let out = render_ruby_file_with_wrappers(&ir, true);
        assert!(out.contains("def filter_changed("), "{out}");
        assert!(out.contains("def decode_changed_log("), "{out}");
        assert!(out.contains("def decode_denied_error("), "{out}");
    }

    #[test]
    fn normalized_tuple_constants_do_not_shadow_each_other_or_contract() {
        let tuple = |internal: &str| AbiParam {
            name: "item".into(),
            ty: SolType::Tuple(vec![TupleComponent {
                name: "value".into(),
                ty: SolType::Uint(256),
                internal_type: None,
            }]),
            internal_type: Some(format!("struct Token.{internal}")),
        };
        let ir = make_ir(
            "Token",
            vec![AbiFunction {
                name: "inspect".into(),
                inputs: vec![tuple("Contract"), tuple("fooBar"), tuple("foo_bar")],
                outputs: vec![],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let constants = declared_constant_names(&ir, true);
        assert_eq!(
            constants.len(),
            constants.iter().collect::<HashSet<_>>().len()
        );
        assert!(constants.contains(&"TokenContract".to_string()));
        assert!(constants.contains(&"TokenContract2".to_string()));
        assert!(constants.contains(&"TokenFooBar".to_string()));
        assert!(constants.contains(&"TokenFooBar2".to_string()));
    }

    #[test]
    fn abi_methods_cannot_replace_runtime_helpers() {
        let ir = make_ir(
            "Helper",
            vec![AbiFunction {
                name: "_function".into(),
                inputs: vec![],
                outputs: vec![],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ruby_file_with_wrappers(&ir, true);
        assert!(out.contains("def function\n"), "{out}");
        assert_eq!(out.matches("  def _function(").count(), 1);
    }

    #[test]
    fn digit_leading_abi_names_generate_ruby_identifiers() {
        let ir = make_ir(
            "Token",
            vec![AbiFunction {
                name: "_0".into(),
                inputs: vec![],
                outputs: vec![],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_ruby_file_with_wrappers(&ir, true);
        assert!(out.contains("METHOD_0_SIGNATURE"), "{out}");
        assert!(out.contains("def method_0\n"), "{out}");
    }
}
