//! Rust output: an alloy `sol!` invocation plus the JSON ABI.
//!
//! alloy's macro expands the Solidity declarations into named structs,
//! `…Call`/`…Return` types, events with indexed fields, errors, selectors,
//! and (with `rpc`) a contract instance. Field names match the ABI, so serde
//! JSON uses ABI names.

use crate::naming::Scope;
use crate::renderers::solidity::{data_location_for_type, render_mutability};
use crate::tuples::TupleRegistry;
use abi_typegen_core::types::{AbiParam, ContractIr, NatSpec, SolType};
use heck::{ToShoutySnakeCase, ToSnakeCase};

/// Words that cannot name a parameter or field in the `sol!` body: Solidity
/// keywords and reserved words, plus Rust keywords alloy cannot map.
const RESERVED: &[&str] = &[
    // Solidity keywords and reserved words.
    "abstract",
    "address",
    "after",
    "alias",
    "anonymous",
    "apply",
    "as",
    "assembly",
    "auto",
    "bool",
    "break",
    "byte",
    "bytes",
    "calldata",
    "case",
    "catch",
    "constant",
    "constructor",
    "continue",
    "contract",
    "copyof",
    "default",
    "define",
    "delete",
    "do",
    "else",
    "emit",
    "enum",
    "error",
    "event",
    "external",
    "fallback",
    "false",
    "final",
    "fixed",
    "for",
    "function",
    "if",
    "immutable",
    "implements",
    "import",
    "in",
    "indexed",
    "inline",
    "interface",
    "internal",
    "is",
    "let",
    "library",
    "macro",
    "mapping",
    "match",
    "memory",
    "modifier",
    "mutable",
    "new",
    "null",
    "of",
    "override",
    "partial",
    "payable",
    "pragma",
    "private",
    "promise",
    "public",
    "pure",
    "receive",
    "reference",
    "relocatable",
    "return",
    "returns",
    "revert",
    "sealed",
    "sizeof",
    "static",
    "storage",
    "string",
    "struct",
    "supports",
    "switch",
    "this",
    "true",
    "try",
    "type",
    "typedef",
    "typeof",
    "ufixed",
    "unchecked",
    "using",
    "var",
    "view",
    "virtual",
    "while",
    // Rust keywords.
    "async",
    "await",
    "crate",
    "dyn",
    "extern",
    "fn",
    "impl",
    "loop",
    "mod",
    "move",
    "mut",
    "pub",
    "ref",
    "self",
    "Self",
    "super",
    "trait",
    "unsafe",
    "use",
    "where",
    "yield",
];

/// Returns the file name for a contract: `TupleCases` becomes `tuple_cases.rs`.
pub fn file_name(contract_name: &str) -> String {
    format!("{}.rs", module_file_stem(contract_name))
}

/// Rust keywords (all editions) that a snake_case module name could collide with.
const RUST_KEYWORDS: &[&str] = &[
    "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "crate",
    "do", "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "gen", "if", "impl",
    "in", "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref",
    "return", "self", "static", "struct", "super", "trait", "true", "try", "type", "typeof",
    "unsafe", "unsized", "use", "virtual", "where", "while", "yield",
];

/// Keywords that cannot be raw identifiers, so their modules get a suffix.
const NON_RAW_KEYWORDS: &[&str] = &["crate", "self", "super"];

fn module_file_stem(contract_name: &str) -> String {
    let stem = contract_name.to_snake_case();
    if NON_RAW_KEYWORDS.contains(&stem.as_str()) {
        format!("{stem}_")
    } else {
        stem
    }
}

/// The module identifier for a contract: raw (`r#static`) for keywords.
fn module_ident(contract_name: &str) -> String {
    let stem = module_file_stem(contract_name);
    if RUST_KEYWORDS.contains(&stem.as_str()) {
        format!("r#{stem}")
    } else {
        stem
    }
}

/// Renders `mod.rs`, declaring and re-exporting each contract module.
pub fn render_mod_file(contract_names: &[String]) -> String {
    let mut modules: Vec<(String, &str)> = contract_names
        .iter()
        .map(|name| (module_ident(name), name.as_str()))
        .collect();
    modules.sort();
    let mut out = String::from("//! Generated by abi-typegen. Do not edit.\n\n");
    for (module, _) in &modules {
        out.push_str(&format!("pub mod {module};\n"));
    }
    out.push('\n');
    for (module, name) in &modules {
        out.push_str(&format!("pub use {module}::{name};\n"));
    }
    out
}

/// Renders the Rust bindings file for `ir`.
///
/// `rpc` adds alloy's contract instance (`#[sol(rpc)]`).
pub fn render_rust_file(ir: &ContractIr, rpc: bool) -> String {
    let registry = TupleRegistry::new(ir);
    let mut out = String::from("//! Generated by abi-typegen. Do not edit.\n//!\n");
    out.push_str(&format!("//! Bindings for the `{}` contract.\n\n", ir.name));

    let abi_json = serde_json::to_string(&ir.raw_abi).expect("JSON values serialize");
    out.push_str(&format!("/// JSON ABI of the `{}` contract.\n", ir.name));
    out.push_str(&format!(
        "pub const {}_ABI: &str = {};\n\n",
        ir.name.to_shouty_snake_case(),
        raw_string(&abi_json)
    ));

    out.push_str("alloy::sol! {\n");
    let attributes = if rpc { "rpc, abi" } else { "abi" };
    if has_long_fixed_array(ir) {
        // serde implements arrays only up to 32 elements.
        out.push_str("    // No serde derives: a fixed array is longer than 32 elements.\n");
        out.push_str(&format!("    #[sol({attributes}, all_derives)]\n"));
    } else {
        out.push_str(&format!(
            "    #[sol({attributes}, all_derives, extra_derives(serde::Serialize, serde::Deserialize))]\n"
        ));
    }
    push_docs(&mut out, "    ", ir.natspec.as_ref(), &[], &[]);
    out.push_str(&format!("    contract {} {{\n", ir.name));

    let mut items: Vec<String> = Vec::new();
    let ty =
        |ty: &SolType, internal_type: Option<&str>| solidity_type(ty, internal_type, &registry);

    for def in registry.defs() {
        let mut item = format!("        struct {} {{\n", def.name);
        let mut scope = Scope::default();
        for (index, component) in def.components.iter().enumerate() {
            let name = if component.name.is_empty() {
                format!("_{index}")
            } else {
                sanitize(&component.name)
            };
            item.push_str(&format!(
                "            {} {};\n",
                ty(&component.ty, component.internal_type.as_deref()),
                scope.claim(&name)
            ));
        }
        item.push_str("        }\n");
        items.push(item);
    }

    for error in &ir.errors {
        let mut item = String::new();
        push_docs(
            &mut item,
            "        ",
            error.natspec.as_ref(),
            &error.inputs,
            &[],
        );
        item.push_str(&format!(
            "        error {}({});\n",
            error.name,
            params(&error.inputs, None, &ty)
        ));
        items.push(item);
    }

    for event in &ir.events {
        let mut item = String::new();
        let names: Vec<AbiParam> = event
            .inputs
            .iter()
            .map(|input| AbiParam {
                name: input.name.clone(),
                ty: input.ty.clone(),
                internal_type: input.internal_type.clone(),
            })
            .collect();
        push_docs(&mut item, "        ", event.natspec.as_ref(), &names, &[]);
        let fields = event
            .inputs
            .iter()
            .map(|input| {
                let mut field = ty(&input.ty, input.internal_type.as_deref());
                if input.indexed {
                    field.push_str(" indexed");
                }
                if !input.name.is_empty() {
                    field.push(' ');
                    field.push_str(&sanitize(&input.name));
                }
                field
            })
            .collect::<Vec<_>>()
            .join(", ");
        item.push_str(&format!(
            "        event {}({fields}){};\n",
            event.name,
            if event.anonymous { " anonymous" } else { "" }
        ));
        items.push(item);
    }

    if let Some(constructor) = &ir.constructor {
        items.push(format!(
            "        constructor({}){};\n",
            params(&constructor.inputs, Some(true), &ty),
            render_mutability(&constructor.state_mutability)
        ));
    }

    for function in &ir.functions {
        let mut item = String::new();
        push_docs(
            &mut item,
            "        ",
            function.natspec.as_ref(),
            &function.inputs,
            &function.outputs,
        );
        item.push_str(&format!(
            "        function {}({}) external{}",
            function.name,
            params(&function.inputs, Some(true), &ty),
            render_mutability(&function.state_mutability)
        ));
        if !function.outputs.is_empty() {
            item.push_str(&format!(
                " returns ({})",
                params(&function.outputs, Some(false), &ty)
            ));
        }
        item.push_str(";\n");
        items.push(item);
    }

    if ir.has_fallback {
        items.push("        fallback() external;\n".to_string());
    }
    if ir.has_receive {
        items.push("        receive() external payable;\n".to_string());
    }

    out.push_str(&items.join("\n"));
    out.push_str("    }\n}\n");
    out
}

/// Whether any type in the contract has a fixed array longer than serde supports.
fn has_long_fixed_array(ir: &ContractIr) -> bool {
    fn long(ty: &SolType) -> bool {
        match ty {
            SolType::FixedArray(inner, size) => *size > 32 || long(inner),
            SolType::Array(inner) => long(inner),
            SolType::Tuple(components) => components.iter().any(|c| long(&c.ty)),
            SolType::Uint(_)
            | SolType::Int(_)
            | SolType::Bool
            | SolType::Address
            | SolType::Bytes
            | SolType::BytesN(_)
            | SolType::StringType => false,
        }
    }
    let params = ir
        .functions
        .iter()
        .flat_map(|f| f.inputs.iter().chain(&f.outputs))
        .chain(ir.errors.iter().flat_map(|e| &e.inputs))
        .chain(ir.constructor.iter().flat_map(|c| &c.inputs))
        .map(|p| &p.ty);
    let events = ir.events.iter().flat_map(|e| &e.inputs).map(|p| &p.ty);
    params.chain(events).any(long)
}

/// Renders a parameter list. `input` selects the data location: `Some(true)`
/// for calldata inputs, `Some(false)` for memory outputs, `None` for none.
fn params(
    params: &[AbiParam],
    input: Option<bool>,
    ty: &dyn Fn(&SolType, Option<&str>) -> String,
) -> String {
    let mut scope = Scope::default();
    params
        .iter()
        .map(|param| {
            let mut out = ty(&param.ty, param.internal_type.as_deref());
            if let Some(is_input) = input
                && let Some(location) = data_location_for_type(&param.ty, is_input)
            {
                out.push(' ');
                out.push_str(location);
            }
            if !param.name.is_empty() {
                out.push(' ');
                out.push_str(&scope.claim(&sanitize(&param.name)));
            }
            out
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn solidity_type(ty: &SolType, internal_type: Option<&str>, registry: &TupleRegistry) -> String {
    match ty {
        SolType::Array(inner) => format!("{}[]", solidity_type(inner, internal_type, registry)),
        SolType::FixedArray(inner, size) => {
            format!("{}[{size}]", solidity_type(inner, internal_type, registry))
        }
        SolType::Tuple(components) => registry.name(components, internal_type).to_string(),
        SolType::Uint(_)
        | SolType::Int(_)
        | SolType::Bool
        | SolType::Address
        | SolType::Bytes
        | SolType::BytesN(_)
        | SolType::StringType => ty.canonical(),
    }
}

fn sanitize(name: &str) -> String {
    if RESERVED.contains(&name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

/// Picks a raw string delimiter that the content cannot terminate.
fn raw_string(content: &str) -> String {
    let mut hashes = 1;
    while content.contains(&format!("\"{}", "#".repeat(hashes))) {
        hashes += 1;
    }
    let fence = "#".repeat(hashes);
    format!("r{fence}\"{content}\"{fence}")
}

fn push_docs(
    out: &mut String,
    indent: &str,
    natspec: Option<&NatSpec>,
    inputs: &[AbiParam],
    outputs: &[AbiParam],
) {
    let Some(natspec) = natspec else {
        return;
    };
    let mut blocks: Vec<Vec<String>> = Vec::new();
    for text in natspec.notice.iter().chain(natspec.dev.iter()) {
        let lines: Vec<String> = text.lines().map(rustdoc_line).collect();
        if lines.iter().any(|line| !line.is_empty()) {
            blocks.push(lines);
        }
    }
    let arguments: Vec<String> = inputs
        .iter()
        .filter_map(|param| {
            let description = natspec.params.get(&param.name)?;
            Some(format!("- `{}`: {}", param.name, rustdoc_line(description)))
        })
        .collect();
    if !arguments.is_empty() {
        blocks.push(
            std::iter::once("# Arguments".to_string())
                .chain(std::iter::once(String::new()))
                .chain(arguments)
                .collect(),
        );
    }
    let returns: Vec<String> = outputs
        .iter()
        .enumerate()
        .filter_map(|(index, param)| {
            let key = if param.name.is_empty() {
                format!("_{index}")
            } else {
                param.name.clone()
            };
            let description = natspec.returns.get(&key)?;
            let label = if param.name.is_empty() {
                String::new()
            } else {
                format!("`{}`: ", param.name)
            };
            Some(format!("- {label}{}", rustdoc_line(description)))
        })
        .collect();
    if !returns.is_empty() {
        blocks.push(
            std::iter::once("# Returns".to_string())
                .chain(std::iter::once(String::new()))
                .chain(returns)
                .collect(),
        );
    }
    let lines: Vec<String> = blocks.join(&String::new());
    for line in lines {
        if line.is_empty() {
            out.push_str(&format!("{indent}///\n"));
        } else {
            out.push_str(&format!("{indent}/// {line}\n"));
        }
    }
}

/// Makes one line of NatSpec safe for rustdoc lints.
///
/// Trims indentation (which would start a code block), escapes Markdown and
/// HTML syntax, and wraps bare URLs in `<>` so rustdoc links them.
fn rustdoc_line(line: &str) -> String {
    line.trim()
        .split(' ')
        .map(|word| {
            if word.starts_with("http://") || word.starts_with("https://") {
                let url = word.trim_end_matches(['.', ',', ';', ':', ')', '!', '?']);
                let rest = &word[url.len()..];
                format!("<{url}>{}", escape_markdown(rest))
            } else {
                escape_markdown(word)
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn escape_markdown(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for (index, c) in text.char_indices() {
        match c {
            '[' | ']' | '<' | '>' | '`' | '*' | '_' | '\\' => {
                out.push('\\');
                out.push(c);
            }
            // A leading `#` starts a heading and `~~~` a code fence.
            '#' | '~' if index == 0 => {
                out.push('\\');
                out.push(c);
            }
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;

    fn render_with(json: &str, rpc: bool) -> String {
        let ir = parse_artifact("Token", json).expect("valid artifact");
        render_rust_file(&ir, rpc)
    }

    fn render(abi: &str) -> String {
        render_with(&format!(r#"{{"abi":{abi}}}"#), true)
    }

    #[test]
    fn file_and_module_names_are_snake_case() {
        assert_eq!(file_name("TupleCases"), "tuple_cases.rs");
        assert_eq!(file_name("ERC20"), "erc20.rs");
        let out = render_mod_file(&["Vault".to_string(), "ERC20".to_string()]);
        assert_eq!(
            out,
            "//! Generated by abi-typegen. Do not edit.\n\npub mod erc20;\npub mod vault;\n\npub use erc20::ERC20;\npub use vault::Vault;\n"
        );
    }

    #[test]
    fn keyword_contract_names_use_raw_or_suffixed_modules() {
        assert_eq!(file_name("Override"), "override.rs");
        assert_eq!(file_name("Self"), "self_.rs");
        let out = render_mod_file(&["Override".to_string(), "Super".to_string()]);
        assert!(
            out.contains("pub mod r#override;\npub mod super_;\n"),
            "{out}"
        );
        assert!(
            out.contains("pub use r#override::Override;\npub use super_::Super;\n"),
            "{out}"
        );
    }

    #[test]
    fn long_fixed_arrays_drop_serde_derives() {
        let out = render(
            r#"[{"type":"function","name":"f","inputs":[{"name":"x","type":"uint256[64]"}],"outputs":[],"stateMutability":"nonpayable"}]"#,
        );
        assert!(out.contains("#[sol(rpc, abi, all_derives)]"), "{out}");
        assert!(!out.contains("serde::Serialize"), "{out}");
        let out = render(
            r#"[{"type":"function","name":"f","inputs":[{"name":"x","type":"uint256[32]"}],"outputs":[],"stateMutability":"nonpayable"}]"#,
        );
        assert!(out.contains("extra_derives(serde::Serialize"), "{out}");
    }

    #[test]
    fn emits_abi_const_and_sol_macro() {
        let out = render(
            r#"[{"type":"function","name":"tokenURI","inputs":[{"name":"id","type":"uint256"}],"outputs":[{"name":"","type":"string"}],"stateMutability":"view"}]"#,
        );
        assert!(out.contains("pub const TOKEN_ABI: &str = r#\"["), "{out}");
        assert!(out.contains("alloy::sol! {\n    #[sol(rpc, abi, all_derives, extra_derives(serde::Serialize, serde::Deserialize))]\n    contract Token {\n"), "{out}");
        assert!(
            out.contains("function tokenURI(uint256 id) external view returns (string memory);"),
            "{out}"
        );
    }

    #[test]
    fn disabling_wrappers_drops_only_rpc() {
        let out = render_with(r#"{"abi":[]}"#, false);
        assert!(out.contains("#[sol(abi, all_derives"), "{out}");
        assert!(out.contains("pub const TOKEN_ABI"), "{out}");
    }

    #[test]
    fn single_field_tuple_becomes_named_struct() {
        let out = render(
            r#"[{"type":"function","name":"deposit","inputs":[{"name":"position","type":"tuple","internalType":"struct TupleAccount.Position","components":[{"name":"account","type":"address"}]}],"outputs":[],"stateMutability":"nonpayable"}]"#,
        );
        assert!(
            out.contains("struct TupleAccountPosition {\n            address account;\n        }"),
            "{out}"
        );
        assert!(
            out.contains("function deposit(TupleAccountPosition calldata position) external;"),
            "{out}"
        );
        assert!(!out.contains("(Address)"), "{out}");
    }

    #[test]
    fn events_keep_indexed_and_anonymous() {
        let out = render(
            r#"[{"type":"event","name":"Moved","inputs":[{"name":"from","type":"address","indexed":true},{"name":"","type":"uint256","indexed":false}],"anonymous":true}]"#,
        );
        assert!(
            out.contains("event Moved(address indexed from, uint256) anonymous;"),
            "{out}"
        );
    }

    #[test]
    fn overloads_constructor_fallback_and_receive() {
        let out = render(
            r#"[
            {"type":"constructor","inputs":[{"name":"owner","type":"address"}],"stateMutability":"nonpayable"},
            {"type":"function","name":"deposit","inputs":[],"outputs":[],"stateMutability":"payable"},
            {"type":"function","name":"deposit","inputs":[{"name":"amount","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
            {"type":"fallback","stateMutability":"nonpayable"},
            {"type":"receive","stateMutability":"payable"}
        ]"#,
        );
        assert!(out.contains("constructor(address owner);"), "{out}");
        assert!(
            out.contains("function deposit() external payable;"),
            "{out}"
        );
        assert!(
            out.contains("function deposit(uint256 amount) external;"),
            "{out}"
        );
        assert!(out.contains("fallback() external;"), "{out}");
        assert!(out.contains("receive() external payable;"), "{out}");
    }

    #[test]
    fn reserved_names_get_underscore() {
        let out = render(
            r#"[{"type":"function","name":"f","inputs":[{"name":"self","type":"uint8"},{"name":"type","type":"uint8"}],"outputs":[],"stateMutability":"nonpayable"}]"#,
        );
        assert!(
            out.contains("function f(uint8 self_, uint8 type_)"),
            "{out}"
        );
    }

    #[test]
    fn docs_are_rustdoc_safe() {
        let out = render_with(
            r#"{"abi":[{"type":"function","name":"f","inputs":[{"name":"x","type":"uint8"}],"outputs":[],"stateMutability":"nonpayable"}],
            "metadata":{"output":{
                "devdoc":{"methods":{"f(uint8)":{"details":"    See [EIP-20] at https://eips.ethereum.org/EIPS/eip-20. Uses <T> and `code`.\n~~~\n# Heading","params":{"x":"the value"}}}},
                "userdoc":{"methods":{"f(uint8)":{"notice":"Does f."}}}}}}"#,
            true,
        );
        assert!(out.contains("        /// Does f.\n        ///\n"), "{out}");
        assert!(
            out.contains("/// See \\[EIP-20\\] at <https://eips.ethereum.org/EIPS/eip-20>. Uses \\<T\\> and \\`code\\`."),
            "{out}"
        );
        assert!(out.contains("/// \\~~~\n"), "{out}");
        assert!(out.contains("/// \\# Heading\n"), "{out}");
        assert!(
            out.contains("/// # Arguments\n        ///\n        /// - `x`: the value\n"),
            "{out}"
        );
    }

    #[test]
    fn raw_string_fence_outgrows_content() {
        assert_eq!(raw_string("a"), "r#\"a\"#");
        assert_eq!(raw_string("a\"#b"), "r##\"a\"#b\"##");
    }
}
