//! Thin Unreal Engine adapters over abi-typegen's generated C API.
//!
//! The Unreal backend does not implement ABI encoding, hashing, RPC signing, or
//! cryptography. It emits reflected scalar DTOs and asynchronous read nodes that
//! call the generated C encode/decode functions, which in turn use the shared
//! Rust ABI runtime. Tuple/array operations remain available through the native C
//! API but are not reflected in this first pass. With wrappers enabled, the
//! generated metadata class lists unsupported read and write functions.

use super::c::{claim_item, namespace_name};
use crate::naming::Scope;
use crate::type_mapper::overload_suffix;
use abi_typegen_core::types::{AbiFunction, ContractIr, SolType, StateMutability};
use heck::ToUpperCamelCase;
use std::collections::{HashMap, HashSet};

/// Unreal header and source generated for one contract.
pub struct UnrealArtifacts {
    /// Header with reflected metadata and supported read nodes.
    pub header: String,
    /// Source implementation for the header.
    pub source: String,
}

/// Renders Unreal adapters using the host module's `*_API` export macro.
pub fn render_unreal_artifacts(
    ir: &ContractIr,
    wrappers: bool,
    api_macro: &str,
) -> UnrealArtifacts {
    let contract = contract_name(&ir.name);
    let c_prefix = namespace_name(&ir.name);
    let stems = unreal_function_stems(ir);
    let c_names = c_function_names(ir);

    let mut unsupported = Vec::new();
    let exposed: Vec<_> = ir
        .functions
        .iter()
        .zip(stems.iter())
        .zip(c_names.iter())
        .filter_map(|((function, stem), c_name)| {
            if !matches!(
                function.state_mutability,
                StateMutability::View | StateMutability::Pure
            ) {
                return None;
            }
            if !function.inputs.iter().all(|p| blueprint_scalar(&p.ty))
                || !function.outputs.iter().all(|p| blueprint_scalar(&p.ty))
            {
                unsupported.push(format!(
                    "{}: tuples and arrays are native-C-only in the first Unreal pass",
                    function.signature()
                ));
                return None;
            }
            Some((function, stem.as_str(), c_name.as_str()))
        })
        .collect();

    for function in &ir.functions {
        if matches!(
            function.state_mutability,
            StateMutability::View | StateMutability::Pure
        ) && (function.inputs.iter().any(|p| !blueprint_scalar(&p.ty))
            || function.outputs.iter().any(|p| !blueprint_scalar(&p.ty)))
        {
            // already captured above
        } else if !matches!(
            function.state_mutability,
            StateMutability::View | StateMutability::Pure
        ) && wrappers
        {
            unsupported.push(format!(
                "{}: write signing/submission belongs to IAbiTypegenSigner and is not exposed as a generated Blueprint node",
                function.signature()
            ));
        }
    }

    let runtime_includes = if wrappers {
        "#include \"AbiTypegenAsyncActionBase.h\"\n#include \"AbiTypegenTypes.h\"\n"
    } else {
        ""
    };
    let mut header = format!(
        "// Generated by abi-typegen. Do not edit.\n#pragma once\n\n#include \"CoreMinimal.h\"\n#include \"Kismet/BlueprintFunctionLibrary.h\"\n{runtime_includes}#include \"Generated/{c_prefix}.h\"\n#include \"{contract}Unreal.generated.h\"\n\n"
    );

    header.push_str(&format!(
        "UCLASS()\nclass {api_macro} U{contract}UnrealMetadata : public UBlueprintFunctionLibrary\n{{\n    GENERATED_BODY()\npublic:\n    UFUNCTION(BlueprintPure, Category=\"abi-typegen|{contract}\")\n    static FString GetAbi();\n\n    UFUNCTION(BlueprintPure, Category=\"abi-typegen|{contract}\")\n    static TArray<FString> GetBlueprintUnsupportedOperations();\n}};\n"
    ));

    let mut source = format!(
        "// Generated by abi-typegen. Do not edit.\n#include \"Generated/{contract}Unreal.h\"\n\n#include \"Dom/JsonObject.h\"\n#include \"Containers/StringConv.h\"\n\nFString U{contract}UnrealMetadata::GetAbi() {{ return UTF8_TO_TCHAR({c_prefix}_abi); }}\n\nTArray<FString> U{contract}UnrealMetadata::GetBlueprintUnsupportedOperations()\n{{\n    return {{\n"
    );
    for item in &unsupported {
        source.push_str(&format!("        TEXT({}),\n", cpp_string(item)));
    }
    source.push_str("    };\n}\n");

    if wrappers {
        for (function, stem, c_name) in exposed {
            render_read_node(
                &mut header,
                &mut source,
                &contract,
                stem,
                c_name,
                function,
                api_macro,
            );
        }
    }

    UnrealArtifacts { header, source }
}

fn render_read_node(
    header: &mut String,
    source: &mut String,
    contract: &str,
    stem: &str,
    c_name: &str,
    function: &AbiFunction,
    api_macro: &str,
) {
    let input_names = reflected_names(
        function.inputs.iter().map(|p| p.name.as_str()),
        &[
            stem,
            "WorldContextObject",
            "RequestOwner",
            "RpcUrl",
            "ContractAddress",
            "RpcUrlValue",
            "ContractAddressValue",
            "Action",
            "Error",
            "Params",
            "Encoded",
            "CallData",
            "DataHex",
            "To",
            "Rpc",
            "Response",
            "Raw",
            "DecodeError",
            "Native",
            "Reflected",
            "Activate",
            "OnSuccess",
            "OnFailure",
            "Finish",
            "TrackRequest",
            "IsRequestOwnerAlive",
            "InitializeLifetime",
            "Cancel",
            "BeginDestroy",
            "GetClass",
            "GetWorld",
            "GetName",
            "GetOuter",
        ],
    );
    let output_names = reflected_names(
        function.outputs.iter().map(|p| p.name.as_str()),
        &["bCompleted"],
    );
    let input_c_fields = c_field_names(function.inputs.iter().map(|p| p.name.as_str()));
    let output_c_fields = c_field_names(function.outputs.iter().map(|p| p.name.as_str()));
    let result = format!("F{contract}{stem}Result");
    header.push_str(&format!(
        "\nUSTRUCT(BlueprintType)\nstruct {api_macro} {result}\n{{\n    GENERATED_BODY()\n"
    ));
    for (index, output) in function.outputs.iter().enumerate() {
        let name = &output_names[index];
        header.push_str(&format!(
            "    UPROPERTY(BlueprintReadOnly, Category=\"abi-typegen\")\n    {} {name};\n",
            unreal_type(&output.ty)
        ));
    }
    if function.outputs.is_empty() {
        header.push_str("    UPROPERTY(BlueprintReadOnly, Category=\"abi-typegen\")\n    bool bCompleted = true;\n");
    }
    header.push_str("};\n");

    let success_delegate = format!("F{contract}{stem}Success");
    let failure_delegate = format!("F{contract}{stem}Failure");
    let action = format!("U{contract}{stem}AsyncAction");
    header.push_str(&format!(
        "\nDECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam({success_delegate}, {result}, Result);\nDECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam({failure_delegate}, FString, Error);\n\nUCLASS()\nclass {api_macro} {action} : public UAbiTypegenAsyncActionBase\n{{\n    GENERATED_BODY()\npublic:\n    UPROPERTY(BlueprintAssignable) {success_delegate} OnSuccess;\n    UPROPERTY(BlueprintAssignable) {failure_delegate} OnFailure;\n\n"
    ));

    let params = function
        .inputs
        .iter()
        .enumerate()
        .map(|(index, p)| format!("{} {}", unreal_type(&p.ty), input_names[index]))
        .collect::<Vec<_>>();
    let tail = if params.is_empty() {
        String::new()
    } else {
        format!(", {}", params.join(", "))
    };
    header.push_str(&format!(
        "    UFUNCTION(BlueprintCallable, meta=(BlueprintInternalUseOnly=\"true\", WorldContext=\"WorldContextObject\"), Category=\"abi-typegen|{contract}\")\n    static {action}* {stem}(UObject* WorldContextObject, UObject* RequestOwner, const FString& RpcUrl, FAbiTypegenAddress ContractAddress{tail});\n\n    virtual void Activate() override;\n\nprivate:\n    FString RpcUrlValue;\n    FAbiTypegenAddress ContractAddressValue;\n"
    ));
    for (index, p) in function.inputs.iter().enumerate() {
        header.push_str(&format!(
            "    {} {};\n",
            unreal_type(&p.ty),
            input_names[index]
        ));
    }
    header.push_str("};\n");

    source.push_str(&format!(
        "\n{action}* {action}::{stem}(UObject* WorldContextObject, UObject* RequestOwner, const FString& RpcUrl, FAbiTypegenAddress ContractAddress{tail})\n{{\n    {action}* Action = NewObject<{action}>();\n    Action->InitializeLifetime(WorldContextObject, RequestOwner);\n    Action->RpcUrlValue = RpcUrl;\n    Action->ContractAddressValue = ContractAddress;\n"
    ));
    for (index, _) in function.inputs.iter().enumerate() {
        let name = &input_names[index];
        source.push_str(&format!("    Action->{name} = {name};\n"));
    }
    source.push_str("    return Action;\n}\n");

    source.push_str(&format!("\nvoid {action}::Activate()\n{{\n    FString Error;\n    atg_address ContractAddress{{}};\n    if (!ContractAddressValue.TryToAddress(ContractAddress, Error)) {{ OnFailure.Broadcast(Error); Finish(); return; }}\n    {c_name}_params Params{{}};\n"));

    for (index, p) in function.inputs.iter().enumerate() {
        let cpp = &input_names[index];
        let c_field = &input_c_fields[index];
        source.push_str(&to_c(
            &format!("this->{cpp}"),
            &format!("Params.{c_field}"),
            &p.ty,
            index,
        ));
    }

    source.push_str(&format!(
        "    FAbiTypegenResult Encoded({c_name}_encode(&Params));\n    if (!Encoded.IsOk()) {{ OnFailure.Broadcast(Encoded.Error()); Finish(); return; }}\n    const TArray<uint8> CallData = Encoded.CopyBytes();\n    const FString DataHex = AbiTypegen::BytesToHex(CallData.GetData(), CallData.Num(), true);\n    const FString To = AbiTypegen::AddressToHex(ContractAddress);\n    FAbiTypegenRpcClient Rpc(RpcUrlValue);\n    TrackRequest(Rpc.EthCall(this, To, DataHex, [this](FAbiTypegenRpcResponse&& Response)\n    {{\n        if (!IsRequestOwnerAlive()) {{ Finish(); return; }}\n        if (!Response.bOk || !Response.Result.IsValid() || Response.Result->Type != EJson::String)\n        {{\n            OnFailure.Broadcast(Response.Error.IsEmpty() ? TEXT(\"eth_call failed\") : Response.Error);\n            Finish();\n            return;\n        }}\n        TArray<uint8> Raw;\n        FString DecodeError;\n        if (!AbiTypegen::HexToBytes(Response.Result->AsString(), Raw, DecodeError))\n        {{\n            OnFailure.Broadcast(DecodeError);\n            Finish();\n            return;\n        }}\n        {c_name}_returns Native{{}};\n        FAbiTypegenResult Decoded({c_name}_decode(Raw.GetData(), static_cast<size_t>(Raw.Num()), &Native));\n        if (!Decoded.IsOk()) {{ OnFailure.Broadcast(Decoded.Error()); Finish(); return; }}\n        {result} Reflected{{}};\n"
    ));
    for (index, output) in function.outputs.iter().enumerate() {
        let field = &output_names[index];
        let c_field = &output_c_fields[index];
        source.push_str(&from_c(
            &format!("Native.{c_field}"),
            &format!("Reflected.{field}"),
            &output.ty,
        ));
    }
    source.push_str("        OnSuccess.Broadcast(Reflected);\n        Finish();\n    }));\n}\n");
}

fn blueprint_scalar(ty: &SolType) -> bool {
    matches!(
        ty,
        SolType::Bool
            | SolType::Address
            | SolType::Uint(_)
            | SolType::Int(_)
            | SolType::StringType
            | SolType::Bytes
            | SolType::BytesN(_)
    )
}

fn unreal_type(ty: &SolType) -> &'static str {
    match ty {
        SolType::Bool => "bool",
        SolType::Address => "FAbiTypegenAddress",
        SolType::Uint(_) | SolType::Int(_) => "FAbiTypegenWord256",
        SolType::StringType => "FString",
        SolType::Bytes | SolType::BytesN(_) => "FAbiTypegenBytes",
        SolType::Array(_) | SolType::FixedArray(_, _) | SolType::Tuple(_) => {
            unreachable!("non-scalar types are not Blueprint-reflected in first pass")
        }
    }
}

fn to_c(cpp: &str, c: &str, ty: &SolType, index: usize) -> String {
    match ty {
        SolType::Bool => format!("    {c} = {cpp};\n"),
        SolType::Address => format!(
            "    if (!{cpp}.TryToAddress({c}, Error)) {{ OnFailure.Broadcast(Error); Finish(); return; }}\n"
        ),
        SolType::Uint(_) | SolType::Int(_) => format!(
            "    if (!{cpp}.TryToWord({c}, Error)) {{ OnFailure.Broadcast(Error); Finish(); return; }}\n"
        ),
        SolType::StringType => format!(
            "    FTCHARToUTF8 AtgUtf8{index}(*{cpp});\n    {c}.data = reinterpret_cast<const uint8*>(AtgUtf8{index}.Get());\n    {c}.len = static_cast<size_t>(AtgUtf8{index}.Length());\n"
        ),
        SolType::Bytes => format!(
            "    {c}.data = {cpp}.Data.GetData();\n    {c}.len = static_cast<size_t>({cpp}.Data.Num());\n"
        ),
        SolType::BytesN(n) => format!(
            "    if ({cpp}.Data.Num() != {n}) {{ OnFailure.Broadcast(TEXT(\"bytes{n} requires exactly {n} bytes\")); Finish(); return; }}\n    FMemory::Memcpy({c}.bytes, {cpp}.Data.GetData(), {n});\n"
        ),
        _ => unreachable!(),
    }
}

fn from_c(c: &str, cpp: &str, ty: &SolType) -> String {
    match ty {
        SolType::Bool => format!("        {cpp} = {c};\n"),
        SolType::Address => format!("        {cpp} = FAbiTypegenAddress::FromAddress({c});\n"),
        SolType::Uint(_) | SolType::Int(_) => {
            format!("        {cpp} = FAbiTypegenWord256::FromWord({c});\n")
        }
        SolType::StringType => format!(
            "        if ({c}.len > static_cast<size_t>(MAX_int32)) {{ OnFailure.Broadcast(TEXT(\"decoded string exceeds Unreal array limits\")); Finish(); return; }}\n        {{ FUTF8ToTCHAR Converted(reinterpret_cast<const ANSICHAR*>({c}.data), static_cast<int32>({c}.len)); {cpp} = FString(Converted.Length(), Converted.Get()); }}\n"
        ),
        SolType::Bytes => format!(
            "        if ({c}.len > static_cast<size_t>(MAX_int32)) {{ OnFailure.Broadcast(TEXT(\"decoded bytes exceed Unreal array limits\")); Finish(); return; }}\n        {cpp}.Data.Append({c}.data, static_cast<int32>({c}.len));\n"
        ),
        SolType::BytesN(n) => format!("        {cpp}.Data.Append({c}.bytes, {n});\n"),
        _ => unreachable!(),
    }
}

fn c_function_names(ir: &ContractIr) -> Vec<String> {
    let prefix = namespace_name(&ir.name);
    let mut names = Scope::default();
    ir.functions
        .iter()
        .map(|f| claim_item(&mut names, &format!("{prefix}_{}", namespace_name(&f.name))))
        .collect()
}

fn unreal_function_stems(ir: &ContractIr) -> Vec<String> {
    let mut counts = HashMap::new();
    for f in &ir.functions {
        *counts.entry(f.name.as_str()).or_insert(0usize) += 1;
    }
    let mut used = HashSet::new();
    ir.functions
        .iter()
        .map(|f| {
            let suffix = if counts[f.name.as_str()] > 1 {
                overload_suffix(&f.inputs)
            } else {
                String::new()
            };
            let base = format!("{}{}", contract_name(&f.name), suffix);
            let mut candidate = base.clone();
            let mut i = 2;
            while !used.insert(candidate.to_ascii_lowercase()) {
                candidate = format!("{base}{i}");
                i += 1;
            }
            candidate
        })
        .collect()
}

fn reflected_names<'a>(names: impl Iterator<Item = &'a str>, reserved: &[&str]) -> Vec<String> {
    let mut used: HashSet<String> = reserved.iter().map(|s| s.to_ascii_lowercase()).collect();
    names
        .enumerate()
        .map(|(index, name)| {
            let base = if name.is_empty() {
                format!("Value{index}")
            } else {
                contract_name(name)
            };
            let mut candidate = base.clone();
            let mut suffix = 2;
            while !used.insert(candidate.to_ascii_lowercase()) {
                candidate = format!("{base}{suffix}");
                suffix += 1;
            }
            candidate
        })
        .collect()
}

/// C++ and Unreal reflected identifier stem for a contract name.
pub fn contract_name(raw: &str) -> String {
    let name = raw.to_upper_camel_case();
    if name.is_empty() {
        "Atg".into()
    } else if name.starts_with(|c: char| c.is_ascii_digit()) {
        format!("Atg{name}")
    } else {
        name
    }
}

/// Names declared in the host C++ module, used for cross-contract collision checks.
pub fn declared_symbol_names(ir: &ContractIr, wrappers: bool) -> Vec<String> {
    let contract = contract_name(&ir.name);
    let mut names = vec![format!("U{contract}UnrealMetadata")];
    if wrappers {
        for (function, stem) in ir.functions.iter().zip(unreal_function_stems(ir)) {
            if matches!(
                function.state_mutability,
                StateMutability::View | StateMutability::Pure
            ) && function.inputs.iter().all(|p| blueprint_scalar(&p.ty))
                && function.outputs.iter().all(|p| blueprint_scalar(&p.ty))
            {
                names.extend([
                    format!("F{contract}{stem}Result"),
                    format!("U{contract}{stem}AsyncAction"),
                    format!("F{contract}{stem}Success"),
                    format!("F{contract}{stem}Failure"),
                ]);
            }
        }
    }
    names
}

fn c_field_names<'a>(names: impl Iterator<Item = &'a str>) -> Vec<String> {
    let mut scope = Scope::default();
    names
        .enumerate()
        .map(|(index, name)| {
            let raw = if name.is_empty() { "field" } else { name };
            let base = c_ident(raw);
            let claimed = scope.claim(&base);
            if claimed.is_empty() {
                format!("atg_field{index}")
            } else {
                claimed
            }
        })
        .collect()
}

fn c_ident(name: &str) -> String {
    let clean = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect::<String>()
        .split('_')
        .filter(|p| !p.is_empty())
        .collect::<Vec<_>>()
        .join("_");
    format!("atg_{}", if clean.is_empty() { "field" } else { &clean })
}

fn cpp_string(value: &str) -> String {
    let escaped = value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r");
    format!("\"{escaped}\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;

    #[test]
    fn emits_blueprint_scalar_read_and_reports_nested_container_limit() {
        let ir = parse_artifact(
            "Token",
            r#"{"abi":[
                {"type":"function","name":"balanceOf","inputs":[{"name":"owner","type":"address"}],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"},
                {"type":"function","name":"matrix","inputs":[],"outputs":[{"name":"","type":"uint256[][]"}],"stateMutability":"view"},
                {"type":"function","name":"mint","inputs":[{"name":"to","type":"address"},{"name":"amount","type":"uint256"}],"outputs":[],"stateMutability":"nonpayable"}
            ]}"#,
        ).expect("fixture");
        let full = render_unreal_artifacts(&ir, true, "HOST_API");
        assert!(
            full.header.contains("UTokenBalanceOfAsyncAction"),
            "{}",
            full.header
        );
        assert!(
            full.source.contains("atg_Token_atg_balanceOf_encode"),
            "{}",
            full.source
        );
        assert!(
            full.source
                .contains("matrix(): tuples and arrays are native-C-only"),
            "{}",
            full.source
        );
        assert!(
            full.source
                .contains("mint(address,uint256): write signing/submission belongs"),
            "{}",
            full.source
        );
        let metadata = render_unreal_artifacts(&ir, false, "HOST_API");
        assert!(!metadata.header.contains("UTokenBalanceOfAsyncAction"));
        assert!(metadata.header.contains("UTokenUnrealMetadata"));
    }

    #[test]
    fn read_nodes_have_valid_parameters_and_module_exports() {
        let ir = parse_artifact("Token", r#"{"abi":[{"type":"function","name":"balanceOf","inputs":[{"name":"owner","type":"address"}],"outputs":[{"name":"balance","type":"uint256"}],"stateMutability":"view"}]}"#).expect("fixture");
        let output = render_unreal_artifacts(&ir, true, "ABITYPEGENUNREALTESTHOST_API");
        assert!(
            output.header.contains("FAbiTypegenAddress Owner"),
            "{}",
            output.header
        );
        assert!(!output.header.contains("FAbiTypegenAddress, Owner"));
        assert!(
            output
                .header
                .contains("struct ABITYPEGENUNREALTESTHOST_API FTokenBalanceOfResult")
        );
        assert!(
            output
                .header
                .contains("class ABITYPEGENUNREALTESTHOST_API UTokenBalanceOfAsyncAction")
        );
        assert!(
            output
                .header
                .contains("class ABITYPEGENUNREALTESTHOST_API UTokenUnrealMetadata")
        );
        assert!(output.header.contains("#include \"Generated/atg_Token.h\""));
        assert!(
            output
                .source
                .contains("#include \"Generated/TokenUnreal.h\"")
        );
        assert!(
            output
                .source
                .contains("#include \"Containers/StringConv.h\"")
        );
    }

    #[test]
    fn generated_parameters_do_not_shadow_factory_or_activation_locals() {
        let ir = parse_artifact("Token", r#"{"abi":[{"type":"function","name":"lookup","inputs":[{"name":"rpcUrl","type":"string"},{"name":"params","type":"uint256"},{"name":"error","type":"bool"},{"name":"contractAddress","type":"address"}],"outputs":[{"name":"","type":"uint256"}],"stateMutability":"view"}]}"#).expect("fixture");
        let output = render_unreal_artifacts(&ir, true, "HOST_API");
        assert!(
            output.header.contains("FString RpcUrl2"),
            "{}",
            output.header
        );
        assert!(output.header.contains("FAbiTypegenWord256 Params2"));
        assert!(output.header.contains("bool Error2"));
        assert!(
            output
                .header
                .contains("FAbiTypegenAddress ContractAddress2")
        );
    }

    #[test]
    fn string_converter_does_not_shadow_another_input_member() {
        let ir = parse_artifact("Token", r#"{"abi":[{"type":"function","name":"lookup","inputs":[{"name":"x","type":"string"},{"name":"xUtf8","type":"uint256"}],"outputs":[{"name":"","type":"bool"}],"stateMutability":"view"}]}"#).expect("fixture");
        let output = render_unreal_artifacts(&ir, true, "HOST_API");
        assert!(
            output.source.contains("FTCHARToUTF8 AtgUtf80(*this->X);"),
            "{}",
            output.source
        );
        assert!(
            output
                .source
                .contains("this->XUtf8.TryToWord(Params.atg_xUtf8, Error)"),
            "{}",
            output.source
        );
    }

    #[test]
    fn inputs_do_not_shadow_generated_or_base_action_members() {
        let ir = parse_artifact("Token", r#"{"abi":[{"type":"function","name":"lookup","inputs":[{"name":"onFailure","type":"bool"},{"name":"activate","type":"bool"},{"name":"finish","type":"bool"}],"outputs":[],"stateMutability":"view"}]}"#).expect("fixture");
        let output = render_unreal_artifacts(&ir, true, "HOST_API");
        assert!(
            output.header.contains("bool OnFailure2;"),
            "{}",
            output.header
        );
        assert!(
            output.header.contains("bool Activate2;"),
            "{}",
            output.header
        );
        assert!(output.header.contains("bool Finish2;"), "{}", output.header);
    }

    #[test]
    fn reflected_member_claims_ignore_case_like_unreal_names() {
        let ir = parse_artifact("Token", r#"{"abi":[{"type":"function","name":"lookup","inputs":[{"name":"onsuccess","type":"bool"},{"name":"onSuccess","type":"bool"}],"outputs":[],"stateMutability":"view"}]}"#).expect("fixture");
        let output = render_unreal_artifacts(&ir, true, "HOST_API");
        assert!(
            output.header.contains("bool Onsuccess2;"),
            "{}",
            output.header
        );
        assert!(
            output.header.contains("bool OnSuccess3;"),
            "{}",
            output.header
        );
    }
}
