use crate::naming::Scope;
use crate::type_mapper::{
    Target, overload_suffix, safe_param_name, safe_param_names, sol_type_to_ts,
};
use abi_typegen_core::types::{AbiFunction, AbiParam, ContractIr, NatSpec, StateMutability};
use heck::ToUpperCamelCase;
use std::collections::HashMap;

const TARGET: Target = Target::Viem;

/// Generates `<ContractName>.viem.ts` — a viem contract helper + typed param types.
pub fn render_viem_file(ir: &ContractIr) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by abi-typegen. Do not edit manually.\n");
    out.push_str(&format!(
        "import {{ {}Abi }} from './{}.abi.js';\n",
        ir.name, ir.name
    ));
    out.push_str(
        "import { getContract, type Address, type Client, type GetContractReturnType } from 'viem';\n",
    );
    out.push('\n');

    // Contract-level NatSpec
    if let Some(ns) = &ir.natspec {
        out.push_str(&render_jsdoc(ns, &[], &[]));
    }

    // getContract helper. The explicit return type keeps declaration emit from
    // serializing the fully expanded contract type (TS7056 on large ABIs).
    out.push_str(&format!(
        "export function get{0}Contract<TClient extends Client>(\n  address: Address,\n  client: TClient,\n): GetContractReturnType<typeof {0}Abi, TClient> {{\n",
        ir.name
    ));
    out.push_str(&format!(
        "  return getContract({{ address, abi: {}Abi, client }});\n",
        ir.name
    ));
    out.push_str("}\n");

    // Typed parameter types for non-view/non-pure functions that have inputs
    let write_fns: Vec<&AbiFunction> = ir
        .functions
        .iter()
        .filter(|f| {
            !matches!(
                f.state_mutability,
                StateMutability::Pure | StateMutability::View
            ) && !f.inputs.is_empty()
        })
        .collect();

    if !write_fns.is_empty() {
        out.push('\n');
        // Track overloads: count how many times each name appears
        let mut name_counts: HashMap<&str, u32> = HashMap::new();
        for f in &write_fns {
            *name_counts.entry(f.name.as_str()).or_insert(0) += 1;
        }

        let mut scope = Scope::default();
        for f in &write_fns {
            let total = *name_counts.get(f.name.as_str()).unwrap_or(&1);
            let base = if total > 1 {
                format!(
                    "{}{}{}",
                    ir.name,
                    f.name.to_upper_camel_case(),
                    overload_suffix(&f.inputs)
                )
            } else {
                format!("{}{}", ir.name, f.name.to_upper_camel_case())
            };
            let type_name = format!("{}Params", scope.claim_family(&base, &["Params"]));
            out.push_str(&render_params_type(&type_name, f));
            out.push('\n');
        }
    }

    out
}

fn render_params_type(type_name: &str, f: &AbiFunction) -> String {
    let mut out = String::new();
    if let Some(ns) = &f.natspec {
        out.push_str(&render_jsdoc(ns, &f.inputs, &f.outputs));
    }
    out.push_str(&format!("export type {} = {{\n", type_name));
    let names = safe_param_names(f.inputs.iter().map(|p| p.name.as_str()));
    for (i, param) in f.inputs.iter().enumerate() {
        let ts_type = sol_type_to_ts(&param.ty, TARGET);
        let name = &names[i];
        out.push_str(&format!("  {}: {};\n", name, ts_type));
    }
    out.push_str("};\n");
    out
}

fn render_jsdoc(ns: &NatSpec, params: &[AbiParam], outputs: &[AbiParam]) -> String {
    let mut lines = Vec::new();
    if let Some(notice) = &ns.notice {
        lines.push(format!(" * {}", notice));
    }
    if let Some(dev) = &ns.dev {
        lines.push(format!(" * @dev {}", dev));
    }
    for (i, param) in params.iter().enumerate() {
        if let Some(desc) = ns.params.get(&param.name) {
            let name = safe_param_name(&param.name, i);
            lines.push(format!(" * @param {} {}", name, desc));
        }
    }
    // Follow ABI output order; solc keys unnamed outputs as `_0`, `_1`, ...
    for (i, output) in outputs.iter().enumerate() {
        let key = if output.name.is_empty() {
            format!("_{i}")
        } else {
            output.name.clone()
        };
        if let Some(desc) = ns.returns.get(&key) {
            lines.push(format!(" * @returns {} {}", key, desc));
        }
    }
    if lines.is_empty() {
        return String::new();
    }
    format!("/**\n{}\n */\n", lines.join("\n"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;

    fn erc20() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/erc20.json"),
        )
        .unwrap();
        parse_artifact("ERC20", &json).unwrap()
    }

    fn vault() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/vault.json"),
        )
        .unwrap();
        parse_artifact("Vault", &json).unwrap()
    }

    #[test]
    fn contains_header_and_imports() {
        let out = render_viem_file(&erc20());
        assert!(out.contains("// Auto-generated by abi-typegen."));
        assert!(out.contains("import { ERC20Abi } from './ERC20.abi.js'"));
        assert!(out.contains("import { getContract"));
    }

    #[test]
    fn exports_get_contract_fn() {
        let out = render_viem_file(&erc20());
        assert!(out.contains(
            "export function getERC20Contract<TClient extends Client>(\n  address: Address,\n  client: TClient,\n): GetContractReturnType<typeof ERC20Abi, TClient> {"
        ));
        assert!(out.contains("return getContract({ address, abi: ERC20Abi, client });"));
    }

    #[test]
    fn emits_params_types_for_write_fns() {
        let out = render_viem_file(&erc20());
        assert!(out.contains("export type ERC20TransferParams = {"));
        assert!(out.contains("to: `0x${string}`"));
        assert!(out.contains("amount: bigint"));
    }

    #[test]
    fn natspec_becomes_jsdoc() {
        let out = render_viem_file(&erc20());
        assert!(out.contains("* Transfer tokens to a recipient"));
        assert!(out.contains("* @param to Recipient address"));
    }

    #[test]
    fn vault_overloads_get_signature_based_types() {
        let out = render_viem_file(&vault());
        assert!(
            out.contains("export type VaultDepositUint256Params = {"),
            "Expected VaultDepositUint256Params for deposit(uint256), got:\n{out}"
        );
        assert!(
            out.contains("export type VaultDepositUint256AddressParams = {"),
            "Expected VaultDepositUint256AddressParams for deposit(uint256, address), got:\n{out}"
        );
        // Old numbered names should not appear
        assert!(
            !out.contains("VaultDeposit1Params"),
            "Old numbered overload name should not appear, got:\n{out}"
        );
    }

    #[test]
    fn no_params_type_for_view_fns() {
        let out = render_viem_file(&erc20());
        // balanceOf is view — no BalanceOfParams type
        assert!(!out.contains("export type BalanceOfParams"));
    }

    /// Helper: build a minimal ContractIr by hand.
    fn make_ir(name: &str, natspec: Option<NatSpec>, functions: Vec<AbiFunction>) -> ContractIr {
        ContractIr {
            name: name.into(),
            constructor: None,
            functions,
            events: vec![],
            errors: vec![],
            has_fallback: false,
            has_receive: false,
            natspec,
            raw_abi: serde_json::Value::Array(vec![]),
        }
    }

    #[test]
    fn contract_level_natspec_jsdoc() {
        let ns = NatSpec {
            notice: Some("A cool contract".into()),
            ..Default::default()
        };
        let ir = make_ir("Cool", Some(ns), vec![]);
        let out = render_viem_file(&ir);

        // JSDoc block must appear before the export function
        let jsdoc_pos = out.find("/**").expect("JSDoc block missing");
        let notice_pos = out
            .find("A cool contract")
            .expect("notice text missing in JSDoc");
        let export_pos = out
            .find("export function")
            .expect("export function missing");

        assert!(jsdoc_pos < notice_pos);
        assert!(notice_pos < export_pos);
        assert!(out.contains(" */"));
    }

    #[test]
    fn jsdoc_dev_only_no_notice() {
        let ns = NatSpec {
            notice: None,
            dev: Some("Internal helper contract".into()),
            ..Default::default()
        };
        let ir = make_ir("Helper", Some(ns), vec![]);
        let out = render_viem_file(&ir);

        assert!(out.contains("@dev Internal helper contract"));
        // There should be no bare notice line (only @dev)
        assert!(!out.contains("* Internal helper contract\n"));
    }

    #[test]
    fn write_fn_without_inputs_excluded() {
        let f = AbiFunction {
            name: "reset".into(),
            inputs: vec![],
            outputs: vec![],
            state_mutability: StateMutability::NonPayable,
            natspec: None,
        };
        let ir = make_ir("Resettable", None, vec![f]);
        let out = render_viem_file(&ir);

        // No params type should be generated for a write fn with no inputs
        assert!(!out.contains("export type"));
    }

    #[test]
    fn payable_fn_generates_params_type() {
        let f = AbiFunction {
            name: "deposit".into(),
            inputs: vec![AbiParam {
                name: "amount".into(),
                ty: abi_typegen_core::types::SolType::Uint(256),
                internal_type: None,
            }],
            outputs: vec![],
            state_mutability: StateMutability::Payable,
            natspec: None,
        };
        let ir = make_ir("PayableVault", None, vec![f]);
        let out = render_viem_file(&ir);

        assert!(
            out.contains("export type PayableVaultDepositParams = {"),
            "Payable function with inputs should produce a Params type"
        );
        assert!(out.contains("amount: bigint"));
    }

    #[test]
    fn function_natspec_with_returns_does_not_crash() {
        let mut returns = HashMap::new();
        returns.insert("balance".into(), "The user balance".into());

        let ns = NatSpec {
            notice: Some("Get balance".into()),
            dev: None,
            params: HashMap::new(),
            returns,
        };
        let f = AbiFunction {
            name: "withdraw".into(),
            inputs: vec![AbiParam {
                name: "amount".into(),
                ty: abi_typegen_core::types::SolType::Uint(256),
                internal_type: None,
            }],
            outputs: vec![AbiParam {
                name: "balance".into(),
                ty: abi_typegen_core::types::SolType::Uint(256),
                internal_type: None,
            }],
            state_mutability: StateMutability::NonPayable,
            natspec: Some(ns),
        };
        let ir = make_ir("Withdrawable", None, vec![f]);
        let out = render_viem_file(&ir);

        // Should not crash, and should still produce the params type
        assert!(out.contains("export type WithdrawableWithdrawParams = {"));
        // @returns tags are now rendered from NatSpec
        assert!(out.contains("@returns balance The user balance"));
    }

    #[test]
    fn empty_natspec_produces_no_jsdoc() {
        // NatSpec exists but has no notice, no dev, no matching params → empty JSDoc
        let ns = NatSpec {
            notice: None,
            dev: None,
            params: HashMap::new(),
            returns: HashMap::new(),
        };
        let f = AbiFunction {
            name: "send".into(),
            inputs: vec![AbiParam {
                name: "to".into(),
                ty: abi_typegen_core::types::SolType::Address,
                internal_type: None,
            }],
            outputs: vec![],
            state_mutability: StateMutability::NonPayable,
            natspec: Some(ns),
        };
        let ir = make_ir("EmptyNs", None, vec![f]);
        let out = render_viem_file(&ir);

        // Should generate params type but no JSDoc block
        assert!(out.contains("export type EmptyNsSendParams = {"));
        assert!(!out.contains("/**"));
    }

    #[test]
    fn render_viem_file_no_functions() {
        let ir = make_ir("Empty", None, vec![]);
        let out = render_viem_file(&ir);

        // Header present
        assert!(out.contains("// Auto-generated by abi-typegen."));
        // Import present
        assert!(out.contains("import { EmptyAbi }"));
        // getContract helper present
        assert!(out.contains("export function getEmptyContract<TClient extends Client>("));
        // No params section at all
        assert!(!out.contains("export type"));
    }

    #[test]
    fn returns_follow_abi_output_order() {
        let names = ["activated", "hasMore", "zeta", "alpha", "", "middle"];
        let outputs: Vec<AbiParam> = names
            .iter()
            .map(|name| AbiParam {
                name: (*name).into(),
                ty: abi_typegen_core::types::SolType::Bool,
                internal_type: None,
            })
            .collect();
        let returns = names
            .iter()
            .enumerate()
            .map(|(i, name)| {
                let key = if name.is_empty() {
                    format!("_{i}")
                } else {
                    (*name).to_string()
                };
                (key.clone(), format!("{key} doc"))
            })
            .collect();
        let f = AbiFunction {
            name: "triggerSpotStops".into(),
            inputs: vec![AbiParam {
                name: "max".into(),
                ty: abi_typegen_core::types::SolType::Uint(256),
                internal_type: None,
            }],
            outputs,
            state_mutability: StateMutability::NonPayable,
            natspec: Some(NatSpec {
                returns,
                ..Default::default()
            }),
        };
        let out = render_viem_file(&make_ir("Book", None, vec![f]));
        let expected = [
            " * @returns activated activated doc\n",
            " * @returns hasMore hasMore doc\n",
            " * @returns zeta zeta doc\n",
            " * @returns alpha alpha doc\n",
            " * @returns _4 _4 doc\n",
            " * @returns middle middle doc\n",
        ]
        .concat();
        assert!(out.contains(&expected), "{out}");
    }
}
