use crate::type_mapper::{Target, overload_suffix, safe_param_names, sol_type_to_ts};
use abi_typegen_core::types::{AbiFunction, ContractIr, StateMutability};
use heck::ToUpperCamelCase;
use std::collections::{HashMap, HashSet};

const TARGET: Target = Target::Viem;

/// Generates `<ContractName>.wagmi.ts` — wagmi React hooks for reading, writing,
/// and watching events on a contract.
pub fn render_wagmi_file(ir: &ContractIr) -> String {
    let mut out = String::new();

    // ── Header & imports ───────────────────────────────────────────────
    out.push_str("// Auto-generated by abi-typegen. Do not edit manually.\n");
    out.push_str(&format!(
        "import {{ {}Abi }} from './{}.abi.js';\n",
        ir.name, ir.name
    ));

    // Collect which wagmi hooks we actually need
    let has_read = ir.functions.iter().any(is_read);
    let has_write = ir.functions.iter().any(|f| !is_read(f));
    let has_events = !ir.events.is_empty();

    let mut wagmi_imports = Vec::new();
    if has_read {
        wagmi_imports.push("useReadContract");
    }
    if has_write {
        wagmi_imports.push("useWriteContract");
        wagmi_imports.push("type UseWriteContractReturnType");
    }
    if has_events {
        wagmi_imports.push("useWatchContractEvent");
    }

    if !wagmi_imports.is_empty() {
        out.push_str(&format!(
            "import {{ {} }} from 'wagmi';\n",
            wagmi_imports.join(", ")
        ));
    }

    // Always import Address from viem for hook signatures
    out.push_str("import type { Address } from 'viem';\n");

    let (function_hooks, event_hooks) = hook_names(ir);

    // ── Read hooks ─────────────────────────────────────────────────────
    if has_read {
        out.push('\n');
        out.push_str(
            "// ── Read hooks ─────────────────────────────────────────────────────────\n",
        );

        for (f, hook_name) in ir.functions.iter().zip(&function_hooks) {
            if !is_read(f) {
                continue;
            }

            out.push('\n');

            if f.inputs.is_empty() {
                // No args — simple hook
                out.push_str(&format!(
                    "export function {}(address: Address) {{\n",
                    hook_name
                ));
                out.push_str(&format!(
                    "  return useReadContract({{\n    address,\n    abi: {}Abi,\n    functionName: '{}',\n  }});\n",
                    ir.name, f.name
                ));
                out.push_str("}\n");
            } else {
                out.push_str(&format!(
                    "export function {}(address: Address, args: {}) {{\n",
                    hook_name,
                    args_type(f)
                ));
                out.push_str(&format!(
                    "  return useReadContract({{\n    address,\n    abi: {}Abi,\n    functionName: '{}',\n    args: [{}],\n  }});\n",
                    ir.name,
                    f.name,
                    arg_names(f)
                ));
                out.push_str("}\n");
            }
        }
    }

    // ── Write hooks ────────────────────────────────────────────────────
    if has_write {
        out.push('\n');
        out.push_str(
            "// ── Write hooks ────────────────────────────────────────────────────────\n",
        );

        for (f, hook_name) in ir.functions.iter().zip(&function_hooks) {
            if is_read(f) {
                continue;
            }

            let payable = matches!(f.state_mutability, StateMutability::Payable);
            let mut write_params = Vec::new();
            if !f.inputs.is_empty() {
                write_params.push(format!("args: {}", args_type(f)));
            }
            if payable {
                write_params.push("options?: { value?: bigint }".to_string());
            }
            let write_params = write_params.join(", ");

            out.push('\n');
            // The explicit return type keeps declaration emit from naming wagmi
            // internals such as `WriteContractErrorType` (TS2883).
            out.push_str(&format!(
                "export function {}(\n  address: Address,\n): Omit<UseWriteContractReturnType, 'writeContract'> & {{\n  write: ({}) => void;\n}} {{\n",
                hook_name, write_params
            ));
            out.push_str("  const { writeContract, ...rest } = useWriteContract();\n");
            out.push_str("  return {\n    ...rest,\n");
            out.push_str(&format!(
                "    write: ({}) =>\n      writeContract({{\n        address,\n        abi: {}Abi,\n        functionName: '{}',\n",
                write_params, ir.name, f.name
            ));
            if !f.inputs.is_empty() {
                out.push_str(&format!("        args: [{}],\n", arg_names(f)));
            }
            if payable {
                out.push_str("        value: options?.value,\n");
            }
            out.push_str("      }),\n");
            out.push_str("  };\n");
            out.push_str("}\n");
        }
    }

    // ── Event hooks ────────────────────────────────────────────────────
    if has_events {
        out.push('\n');
        out.push_str(
            "// ── Event hooks ────────────────────────────────────────────────────────\n",
        );

        for (ev, hook_name) in ir.events.iter().zip(&event_hooks) {
            // Overloaded events share one hook; later overloads get none.
            let Some(hook_name) = hook_name else {
                continue;
            };

            out.push('\n');
            out.push_str(&format!(
                "export function {}(address: Address, listener: (log: any) => void) {{\n",
                hook_name
            ));
            out.push_str(&format!(
                "  return useWatchContractEvent({{\n    address,\n    abi: {}Abi,\n    eventName: '{}',\n    onLogs: (logs) => logs.forEach(listener),\n  }});\n",
                ir.name, ev.name
            ));
            out.push_str("}\n");
        }
    }

    out
}

fn is_read(f: &AbiFunction) -> bool {
    matches!(
        f.state_mutability,
        StateMutability::Pure | StateMutability::View
    )
}

/// Inline TypeScript object type for a function's inputs.
fn args_type(f: &AbiFunction) -> String {
    let names = safe_param_names(f.inputs.iter().map(|p| p.name.as_str()));
    let fields: Vec<String> = f
        .inputs
        .iter()
        .enumerate()
        .map(|(i, p)| {
            let ts_type = sol_type_to_ts(&p.ty, TARGET);
            let name = &names[i];
            format!("{}: {}", name, ts_type)
        })
        .collect();
    format!("{{ {} }}", fields.join(", "))
}

/// Positional argument list that reads each input from `args`.
fn arg_names(f: &AbiFunction) -> String {
    safe_param_names(f.inputs.iter().map(|p| p.name.as_str()))
        .iter()
        .map(|name| format!("args.{name}"))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Allocates one hook name per function and per distinct event name.
///
/// Read and write hooks share one module namespace, so names are allocated
/// across both. Overloads get a signature suffix. Distinct Solidity names that
/// PascalCase identically (`PREMIUM_PERIOD` and `premiumPeriod`) keep their
/// original spelling instead. Any name still taken gets a numeric suffix.
/// Event entries are `None` for later overloads of an already-named event.
fn hook_names(ir: &ContractIr) -> (Vec<String>, Vec<Option<String>>) {
    let mut name_counts: HashMap<&str, usize> = HashMap::new();
    for f in &ir.functions {
        *name_counts.entry(f.name.as_str()).or_insert(0) += 1;
    }
    let overload = |f: &AbiFunction| {
        if name_counts[f.name.as_str()] > 1 {
            overload_suffix(&f.inputs)
        } else {
            String::new()
        }
    };

    let mut stem_sources: HashMap<String, HashSet<&str>> = HashMap::new();
    for f in &ir.functions {
        stem_sources
            .entry(format!("{}{}", f.name.to_upper_camel_case(), overload(f)))
            .or_default()
            .insert(f.name.as_str());
    }

    let mut used = HashSet::new();
    let mut allocate = |base: String| {
        let mut candidate = base.clone();
        let mut n = 2;
        while !used.insert(candidate.clone()) {
            candidate = format!("{base}_{n}");
            n += 1;
        }
        candidate
    };

    let functions = ir
        .functions
        .iter()
        .map(|f| {
            let camel = format!("{}{}", f.name.to_upper_camel_case(), overload(f));
            let stem = if stem_sources[&camel].len() > 1 {
                format!("{}{}", upper_first(&f.name), overload(f))
            } else {
                camel
            };
            allocate(format!("use{}{}", ir.name, stem))
        })
        .collect();

    let mut seen_events = HashSet::new();
    let events = ir
        .events
        .iter()
        .map(|ev| {
            seen_events.insert(ev.name.as_str()).then(|| {
                allocate(format!(
                    "use{}{}Event",
                    ir.name,
                    ev.name.to_upper_camel_case()
                ))
            })
        })
        .collect();

    (functions, events)
}

fn upper_first(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;
    use abi_typegen_core::types::{
        AbiEvent, AbiFunction, AbiParam, ContractIr, SolType, StateMutability,
    };

    fn erc20() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/erc20.json"),
        )
        .unwrap();
        parse_artifact("ERC20", &json).unwrap()
    }

    fn vault() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/vault.json"),
        )
        .unwrap();
        parse_artifact("Vault", &json).unwrap()
    }

    /// Helper: build a minimal ContractIr by hand.
    fn make_ir(name: &str, functions: Vec<AbiFunction>, events: Vec<AbiEvent>) -> ContractIr {
        ContractIr {
            name: name.into(),
            constructor: None,
            functions,
            events,
            errors: vec![],
            has_fallback: false,
            has_receive: false,
            natspec: None,
            raw_abi: serde_json::Value::Array(vec![]),
        }
    }

    #[test]
    fn wagmi_contains_header_and_imports() {
        let out = render_wagmi_file(&erc20());
        assert!(
            out.contains("// Auto-generated by abi-typegen. Do not edit manually."),
            "Missing auto-generated header"
        );
        assert!(
            out.contains("import { ERC20Abi } from './ERC20.abi.js'"),
            "Missing ABI import"
        );
        assert!(out.contains("from 'wagmi'"), "Missing wagmi import");
        assert!(
            out.contains("import type { Address } from 'viem'"),
            "Missing viem Address import"
        );
    }

    #[test]
    fn wagmi_generates_read_hooks_for_view_fns() {
        let out = render_wagmi_file(&erc20());
        // balanceOf is a view fn with one input
        assert!(
            out.contains("export function useERC20BalanceOf(address: Address, args: { account: `0x${string}` })"),
            "Missing useERC20BalanceOf hook signature. Output:\n{out}"
        );
        assert!(
            out.contains("functionName: 'balanceOf'"),
            "Missing balanceOf functionName"
        );
        assert!(
            out.contains("args: [args.account]"),
            "Missing balanceOf args"
        );
        // totalSupply is a view fn with no inputs
        assert!(
            out.contains("export function useERC20TotalSupply(address: Address)"),
            "Missing useERC20TotalSupply hook"
        );
    }

    #[test]
    fn wagmi_generates_write_hooks_for_mutating_fns() {
        let out = render_wagmi_file(&erc20());
        // transfer is nonpayable with inputs
        assert!(
            out.contains("export function useERC20Transfer(\n  address: Address,\n)"),
            "Missing useERC20Transfer hook"
        );
        assert!(
            out.contains("useWriteContract()"),
            "Missing useWriteContract call"
        );
        assert!(
            out.contains("write: (args: { to: `0x${string}`, amount: bigint })"),
            "Missing write callback with args type. Output:\n{out}"
        );
        assert!(
            out.contains("functionName: 'transfer'"),
            "Missing transfer functionName"
        );
        assert!(
            out.contains("args: [args.to, args.amount]"),
            "Missing transfer args destructuring"
        );
    }

    #[test]
    fn wagmi_generates_event_hooks() {
        let out = render_wagmi_file(&erc20());
        assert!(
            out.contains("export function useERC20TransferEvent(address: Address, listener: (log: any) => void)"),
            "Missing useERC20TransferEvent hook"
        );
        assert!(
            out.contains("useWatchContractEvent"),
            "Missing useWatchContractEvent import/usage"
        );
        assert!(
            out.contains("eventName: 'Transfer'"),
            "Missing Transfer eventName"
        );
        assert!(
            out.contains("onLogs: (logs) => logs.forEach(listener)"),
            "Missing onLogs handler"
        );
        // Approval event
        assert!(
            out.contains("export function useERC20ApprovalEvent("),
            "Missing useERC20ApprovalEvent hook"
        );
    }

    #[test]
    fn wagmi_emits_all_overloads_with_suffix() {
        let out = render_wagmi_file(&vault());
        // deposit is overloaded in vault — both should appear with type suffixes.
        // deposit(uint256) -> useVaultDepositUint256
        // deposit(uint256, address) -> useVaultDepositUint256Address
        assert!(
            out.contains("useVaultDepositUint256("),
            "Expected useVaultDepositUint256 hook for deposit(uint256). Output:\n{out}"
        );
        assert!(
            out.contains("useVaultDepositUint256Address("),
            "Expected useVaultDepositUint256Address hook for deposit(uint256, address). Output:\n{out}"
        );
    }

    #[test]
    fn wagmi_empty_contract_minimal_output() {
        let ir = make_ir("Empty", vec![], vec![]);
        let out = render_wagmi_file(&ir);

        assert!(out.contains("// Auto-generated by abi-typegen."));
        assert!(out.contains("import { EmptyAbi }"));
        assert!(out.contains("import type { Address } from 'viem'"));
        // No wagmi import since there are no hooks
        assert!(!out.contains("from 'wagmi'"));
        // No section headers
        assert!(!out.contains("Read hooks"));
        assert!(!out.contains("Write hooks"));
        assert!(!out.contains("Event hooks"));
    }

    #[test]
    fn wagmi_vault_read_hooks() {
        let out = render_wagmi_file(&vault());
        // getPosition is view with address input
        assert!(
            out.contains("export function useVaultGetPosition(address: Address, args: { user: `0x${string}` })"),
            "Missing useVaultGetPosition hook. Output:\n{out}"
        );
        // getBalances is view with address[] input
        assert!(
            out.contains("useVaultGetBalances"),
            "Missing useVaultGetBalances hook"
        );
        // getMatrix is view with no inputs
        assert!(
            out.contains("export function useVaultGetMatrix(address: Address)"),
            "Missing useVaultGetMatrix hook"
        );
    }

    #[test]
    fn wagmi_write_hook_no_inputs() {
        let f = AbiFunction {
            name: "reset".into(),
            inputs: vec![],
            outputs: vec![],
            state_mutability: StateMutability::NonPayable,
            natspec: None,
        };
        let ir = make_ir("Resettable", vec![f], vec![]);
        let out = render_wagmi_file(&ir);

        assert!(
            out.contains("export function useResettableReset(\n  address: Address,\n)"),
            "Missing useResettableReset hook"
        );
        // The write callback should have no args
        assert!(
            out.contains("write: () =>"),
            "Write hook with no inputs should have no-arg callback"
        );
    }

    #[test]
    fn wagmi_only_imports_needed_hooks() {
        // Only events — should only import useWatchContractEvent
        let ev = AbiEvent {
            name: "Ping".into(),
            inputs: vec![],
            anonymous: false,
            natspec: None,
        };
        let ir = make_ir("Pinger", vec![], vec![ev]);
        let out = render_wagmi_file(&ir);

        assert!(
            out.contains("useWatchContractEvent"),
            "Should import useWatchContractEvent"
        );
        assert!(
            !out.contains("useReadContract"),
            "Should NOT import useReadContract when no read fns"
        );
        assert!(
            !out.contains("useWriteContract"),
            "Should NOT import useWriteContract when no write fns"
        );
    }

    #[test]
    fn wagmi_section_headers() {
        let out = render_wagmi_file(&erc20());
        assert!(out.contains("// ── Read hooks"));
        assert!(out.contains("// ── Write hooks"));
        assert!(out.contains("// ── Event hooks"));
    }

    #[test]
    fn wagmi_reserved_word_params_sanitized() {
        let f = AbiFunction {
            name: "setClass".into(),
            inputs: vec![AbiParam {
                name: "class".into(),
                ty: SolType::Uint(256),
                internal_type: None,
            }],
            outputs: vec![],
            state_mutability: StateMutability::NonPayable,
            natspec: None,
        };
        let ir = make_ir("Contract", vec![f], vec![]);
        let out = render_wagmi_file(&ir);

        assert!(
            out.contains("_class: bigint"),
            "Reserved word 'class' should become '_class'"
        );
        assert!(
            out.contains("args._class"),
            "Args reference should use sanitized name"
        );
    }

    fn function(
        name: &str,
        inputs: Vec<AbiParam>,
        state_mutability: StateMutability,
    ) -> AbiFunction {
        AbiFunction {
            name: name.into(),
            inputs,
            outputs: vec![],
            state_mutability,
            natspec: None,
        }
    }

    fn uint_param(name: &str) -> AbiParam {
        AbiParam {
            name: name.into(),
            ty: SolType::Uint(256),
            internal_type: None,
        }
    }

    #[test]
    fn wagmi_write_hook_has_explicit_return_type() {
        let out = render_wagmi_file(&erc20());
        assert!(
            out.contains("import { useReadContract, useWriteContract, type UseWriteContractReturnType, useWatchContractEvent } from 'wagmi';"),
            "{out}"
        );
        assert!(
            out.contains("): Omit<UseWriteContractReturnType, 'writeContract'> & {\n  write: (args: { to: `0x${string}`, amount: bigint }) => void;\n} {"),
            "{out}"
        );
    }

    #[test]
    fn wagmi_payable_write_hook_forwards_value() {
        let ir = make_ir(
            "Staking",
            vec![
                function(
                    "stake",
                    vec![uint_param("toValidatorId")],
                    StateMutability::Payable,
                ),
                function("deposit", vec![], StateMutability::Payable),
                function(
                    "unstake",
                    vec![uint_param("amount")],
                    StateMutability::NonPayable,
                ),
            ],
            vec![],
        );
        let out = render_wagmi_file(&ir);
        assert!(
            out.contains(
                "write: (args: { toValidatorId: bigint }, options?: { value?: bigint }) =>"
            ),
            "{out}"
        );
        assert!(
            out.contains("write: (options?: { value?: bigint }) =>"),
            "{out}"
        );
        assert_eq!(out.matches("value: options?.value,").count(), 2, "{out}");
        assert!(
            out.contains("write: (args: { amount: bigint }) =>"),
            "{out}"
        );
    }

    #[test]
    fn wagmi_hook_names_are_unique_across_casing_and_mutability() {
        let ir = make_ir(
            "Registrar",
            vec![
                function("PREMIUM_PERIOD", vec![], StateMutability::View),
                function("premiumPeriod", vec![], StateMutability::View),
                function("renew", vec![], StateMutability::View),
                function("renew", vec![uint_param("id")], StateMutability::Payable),
                function("pingEvent", vec![], StateMutability::NonPayable),
            ],
            vec![AbiEvent {
                name: "Ping".into(),
                inputs: vec![],
                anonymous: false,
                natspec: None,
            }],
        );
        let out = render_wagmi_file(&ir);
        for hook in [
            "useRegistrarPREMIUM_PERIOD(",
            "useRegistrarPremiumPeriod(",
            "useRegistrarRenew(",
            "useRegistrarRenewUint256(",
            "useRegistrarPingEvent(",
            "useRegistrarPingEvent_2(",
        ] {
            assert_eq!(
                out.matches(&format!("export function {hook}")).count(),
                1,
                "expected exactly one {hook} in:\n{out}"
            );
        }
    }
}
