use crate::type_mapper::{Target, overload_suffix, safe_param_name, sol_type_to_ts};
use abi_typegen_core::types::{AbiEvent, AbiFunction, ContractIr, SolType, StateMutability};
use heck::ToUpperCamelCase;
use std::collections::HashMap;

const TARGET: Target = Target::Web3;

/// Generates `<ContractName>.web3.ts` — a typed Web3.js v4 contract wrapper.
pub fn render_web3js_file(ir: &ContractIr) -> String {
    let mut out = String::new();

    out.push_str("// Auto-generated by abi-typegen. Do not edit manually.\n");
    // `web3` re-exports `Contract`, so consumers need no direct
    // `web3-eth-contract` dependency (pnpm does not hoist it).
    out.push_str("import { Contract, type Numbers, type Web3 } from 'web3';\n");
    out.push_str(&format!(
        "import {{ {}Abi }} from './{}.abi.js';\n\n",
        ir.name, ir.name
    ));

    // Interface
    out.push_str(&format!("export interface {}Contract {{\n", ir.name));

    // Methods block
    if !ir.functions.is_empty() {
        out.push_str("  methods: {\n");

        // Count overloaded function names.
        let mut name_counts: HashMap<&str, u32> = HashMap::new();
        for f in &ir.functions {
            *name_counts.entry(f.name.as_str()).or_insert(0) += 1;
        }

        for f in &ir.functions {
            let count = *name_counts.get(f.name.as_str()).unwrap_or(&1);
            let overloaded;
            let method_name: &str = if count > 1 {
                overloaded = format!("{}{}", f.name, overload_suffix(&f.inputs));
                &overloaded
            } else {
                &f.name
            };
            out.push_str(&render_method(method_name, f));
        }

        out.push_str("  };\n");
    }

    // Events block
    if !ir.events.is_empty() {
        out.push_str("  events: {\n");
        for event in &ir.events {
            out.push_str(&render_event(event));
        }
        out.push_str("  };\n");
    }

    out.push_str("}\n\n");

    // Factory function — `create<Name>`
    let factory_name = format!("create{}", ir.name.to_upper_camel_case());
    out.push_str(&format!(
        "export function {}(web3: Web3, address: string): {}Contract {{\n",
        factory_name, ir.name
    ));
    out.push_str(&format!(
        "  return new Contract({}Abi as any, address, web3) as unknown as {}Contract;\n",
        ir.name, ir.name
    ));
    out.push_str("}\n");

    out
}

fn render_method(method_name: &str, f: &AbiFunction) -> String {
    let params = f
        .inputs
        .iter()
        .enumerate()
        .map(|(i, p)| {
            format!(
                "{}: {}",
                safe_param_name(&p.name, i),
                sol_type_to_web3_input(&p.ty)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");

    match f.state_mutability {
        StateMutability::Pure | StateMutability::View => {
            let out_types: Vec<String> = f
                .outputs
                .iter()
                .map(|p| sol_type_to_ts(&p.ty, TARGET))
                .collect();
            let return_type = match out_types.len() {
                0 => "void".into(),
                1 => out_types[0].clone(),
                _ => format!("[{}]", out_types.join(", ")),
            };
            format!(
                "    {}({}): {{ call(): Promise<{}>; }};\n",
                method_name, params, return_type
            )
        }
        StateMutability::NonPayable => {
            format!(
                "    {}({}): {{ send(options: {{ from: string }}): Promise<unknown>; }};\n",
                method_name, params
            )
        }
        StateMutability::Payable => {
            format!(
                "    {}({}): {{ send(options: {{ from: string; value?: Numbers }}): Promise<unknown>; }};\n",
                method_name, params
            )
        }
    }
}

/// Maps a Solidity type to the web3.js v4 argument type. Numeric arguments
/// accept any web3 `Numbers` value; return values decode to `bigint`.
fn sol_type_to_web3_input(ty: &SolType) -> String {
    match ty {
        SolType::Uint(_) | SolType::Int(_) => "Numbers".into(),
        SolType::Array(inner) | SolType::FixedArray(inner, _) => {
            format!("{}[]", sol_type_to_web3_input(inner))
        }
        SolType::Tuple(components) => {
            let fields: Vec<String> = components
                .iter()
                .enumerate()
                .map(|(i, c)| {
                    format!(
                        "{}: {}",
                        safe_param_name(&c.name, i),
                        sol_type_to_web3_input(&c.ty)
                    )
                })
                .collect();
            format!("{{ {} }}", fields.join("; "))
        }
        SolType::Bool
        | SolType::Address
        | SolType::Bytes
        | SolType::BytesN(_)
        | SolType::StringType => sol_type_to_ts(ty, TARGET),
    }
}

fn render_event(event: &AbiEvent) -> String {
    let indexed_params: Vec<String> = event
        .inputs
        .iter()
        .enumerate()
        .filter(|(_, p)| p.indexed)
        .map(|(i, p)| {
            format!(
                "{}?: {}",
                safe_param_name(&p.name, i),
                sol_type_to_web3_input(&p.ty)
            )
        })
        .collect();

    let filter_inner = if indexed_params.is_empty() {
        String::new()
    } else {
        format!(" filter?: {{ {} }} ", indexed_params.join("; "))
    };

    format!(
        "    {}: {{ (options?: {{{}}}): unknown; }};\n",
        event.name, filter_inner
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;

    fn erc20() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/erc20.json"),
        )
        .unwrap();
        parse_artifact("ERC20", &json).unwrap()
    }

    fn vault() -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures/vault.json"),
        )
        .unwrap();
        parse_artifact("Vault", &json).unwrap()
    }

    #[test]
    fn web3js_contains_imports() {
        let out = render_web3js_file(&erc20());
        assert!(
            out.contains("import { Contract, type Numbers, type Web3 } from 'web3';"),
            "Missing web3 import in:\n{out}"
        );
        assert!(
            !out.contains("web3-eth-contract"),
            "Wrappers must not import the unhoisted web3-eth-contract package:\n{out}"
        );
        assert!(
            out.contains("import { ERC20Abi } from './ERC20.abi.js';"),
            "Missing ABI import in:\n{out}"
        );
    }

    #[test]
    fn web3js_exports_interface() {
        let out = render_web3js_file(&erc20());
        assert!(
            out.contains("export interface ERC20Contract {"),
            "Missing interface export in:\n{out}"
        );
    }

    #[test]
    fn web3js_view_fn_uses_call() {
        let out = render_web3js_file(&erc20());
        assert!(
            out.contains("balanceOf(account: string): { call(): Promise<bigint>; };"),
            "Expected view fn with .call() returning Promise<bigint>, got:\n{out}"
        );
    }

    #[test]
    fn web3js_write_fn_uses_send() {
        let out = render_web3js_file(&erc20());
        assert!(
            out.contains(
                "transfer(to: string, amount: Numbers): { send(options: { from: string }): Promise<unknown>; };"
            ),
            "Expected write fn with .send(), got:\n{out}"
        );
    }

    #[test]
    fn web3js_events_block() {
        let out = render_web3js_file(&erc20());
        assert!(out.contains("events: {"), "Missing events block in:\n{out}");
        assert!(
            out.contains("Transfer"),
            "Missing Transfer event in:\n{out}"
        );
        assert!(
            out.contains("from?: string"),
            "Missing indexed filter param `from` in:\n{out}"
        );
        assert!(
            out.contains("to?: string"),
            "Missing indexed filter param `to` in:\n{out}"
        );
    }

    #[test]
    fn web3js_factory_fn() {
        let out = render_web3js_file(&erc20());
        assert!(
            out.contains(
                "export function createErc20(web3: Web3, address: string): ERC20Contract {"
            ),
            "Missing or incorrect factory function in:\n{out}"
        );
        assert!(
            out.contains("return new Contract(ERC20Abi as any, address, web3)"),
            "Missing Contract constructor call in:\n{out}"
        );
    }

    #[test]
    fn web3js_vault_overloads() {
        let out = render_web3js_file(&vault());
        assert!(
            out.contains("depositUint256("),
            "Expected depositUint256 for deposit(uint256), got:\n{out}"
        );
        assert!(
            out.contains("depositUint256Address("),
            "Expected depositUint256Address for deposit(uint256, address), got:\n{out}"
        );
        assert!(
            !out.contains("deposit_0("),
            "Old numbered overload name should not appear, got:\n{out}"
        );
    }

    #[test]
    fn web3js_numeric_returns_are_bigint() {
        let out = render_web3js_file(&erc20());
        // web3.js v4 decodes every integer width to bigint by default.
        assert!(
            out.contains("decimals(): { call(): Promise<bigint>; };"),
            "Expected uint8 to map to bigint for Web3, got:\n{out}"
        );
        assert!(
            out.contains("totalSupply(): { call(): Promise<bigint>; };"),
            "Expected uint256 to map to bigint for Web3, got:\n{out}"
        );
    }

    #[test]
    fn web3js_payable_send_accepts_value() {
        let ir = parse_artifact(
            "Staking",
            r#"{"abi":[{"type":"function","name":"stake","stateMutability":"payable",
                "inputs":[{"name":"ids","type":"uint256[]"}],"outputs":[]}]}"#,
        )
        .unwrap();
        let out = render_web3js_file(&ir);
        assert!(
            out.contains(
                "stake(ids: Numbers[]): { send(options: { from: string; value?: Numbers }): Promise<unknown>; };"
            ),
            "{out}"
        );
    }

    // --- Hand-built IR tests below ---

    use abi_typegen_core::types::{AbiEventParam, AbiParam, SolType};

    /// Helper to build a minimal ContractIr with the given functions and events.
    fn make_ir(name: &str, functions: Vec<AbiFunction>, events: Vec<AbiEvent>) -> ContractIr {
        ContractIr {
            name: name.to_string(),
            constructor: None,
            functions,
            events,
            errors: vec![],
            has_fallback: false,
            has_receive: false,
            natspec: None,
            raw_abi: serde_json::Value::Array(vec![]),
        }
    }

    #[test]
    fn web3js_view_fn_returning_void() {
        let ir = make_ir(
            "Minimal",
            vec![AbiFunction {
                name: "ping".to_string(),
                inputs: vec![],
                outputs: vec![],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_web3js_file(&ir);
        assert!(
            out.contains("ping(): { call(): Promise<void>; };"),
            "Expected `Promise<void>` for view fn with no outputs, got:\n{out}"
        );
    }

    #[test]
    fn web3js_no_events_omits_events_block() {
        let ir = make_ir(
            "NoEvents",
            vec![AbiFunction {
                name: "doSomething".to_string(),
                inputs: vec![],
                outputs: vec![],
                state_mutability: StateMutability::NonPayable,
                natspec: None,
            }],
            vec![],
        );
        let out = render_web3js_file(&ir);
        assert!(
            !out.contains("events"),
            "Expected no `events` block when there are no events, got:\n{out}"
        );
    }

    #[test]
    fn web3js_pure_fn_uses_call() {
        let ir = make_ir(
            "MathLib",
            vec![AbiFunction {
                name: "add".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "a".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "b".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Uint(256),
                    internal_type: None,
                }],
                state_mutability: StateMutability::Pure,
                natspec: None,
            }],
            vec![],
        );
        let out = render_web3js_file(&ir);
        assert!(
            out.contains("add(a: Numbers, b: Numbers): { call(): Promise<bigint>; };"),
            "Expected pure fn with .call() returning Promise<bigint>, got:\n{out}"
        );
    }

    #[test]
    fn web3js_event_with_no_indexed_params() {
        let ir = make_ir(
            "LogOnly",
            vec![],
            vec![AbiEvent {
                name: "DataStored".to_string(),
                inputs: vec![
                    AbiEventParam {
                        name: "key".to_string(),
                        ty: SolType::Uint(256),
                        indexed: false,
                        internal_type: None,
                    },
                    AbiEventParam {
                        name: "value".to_string(),
                        ty: SolType::Uint(256),
                        indexed: false,
                        internal_type: None,
                    },
                ],
                anonymous: false,
                natspec: None,
            }],
        );
        let out = render_web3js_file(&ir);
        // No indexed params means empty options
        assert!(
            out.contains("DataStored: { (options?: {}): unknown; };"),
            "Expected event with empty options for non-indexed params, got:\n{out}"
        );
    }

    #[test]
    fn web3js_bool_type_maps_to_boolean() {
        let ir = make_ir(
            "Flags",
            vec![AbiFunction {
                name: "isActive".to_string(),
                inputs: vec![],
                outputs: vec![AbiParam {
                    name: "".to_string(),
                    ty: SolType::Bool,
                    internal_type: None,
                }],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_web3js_file(&ir);
        assert!(
            out.contains("isActive(): { call(): Promise<boolean>; };"),
            "Expected bool to map to boolean, got:\n{out}"
        );
    }

    #[test]
    fn web3js_factory_uses_upper_camel_case() {
        let ir = make_ir("my_token", vec![], vec![]);
        let out = render_web3js_file(&ir);
        assert!(
            out.contains("export function createMyToken("),
            "Expected createMyToken factory, got:\n{out}"
        );
    }

    #[test]
    fn web3js_multiple_outputs_returns_tuple() {
        let ir = make_ir(
            "Multi",
            vec![AbiFunction {
                name: "getPair".to_string(),
                inputs: vec![],
                outputs: vec![
                    AbiParam {
                        name: "a".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "b".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::View,
                natspec: None,
            }],
            vec![],
        );
        let out = render_web3js_file(&ir);
        assert!(
            out.contains("getPair(): { call(): Promise<[string, bigint]>; };"),
            "Expected tuple return type [string, bigint], got:\n{out}"
        );
    }
}
