use super::ethers_common::function_signature;
use crate::type_mapper::{Target, safe_param_name, sol_type_to_ts};
use abi_typegen_core::types::{AbiFunction, AbiParam, ContractIr, SolType, StateMutability};
use heck::ToUpperCamelCase;
use std::collections::HashMap;

const TARGET: Target = Target::Web3;

/// Generates `<ContractName>.web3.ts` — a typed Web3.js v4 contract wrapper.
///
/// The contract type is web3's own `Contract<typeof Abi>`, so events, options,
/// `encodeABI()`, `estimateGas()`, and `send()` keep web3's types. Only
/// `methods` is replaced, to give arguments and `call()` results precise types.
pub fn render_web3js_file(ir: &ContractIr) -> String {
    let name = &ir.name;
    let mut out = String::new();

    out.push_str("// Auto-generated by abi-typegen. Do not edit manually.\n");
    // `web3` re-exports `Contract`, so consumers need no direct
    // `web3-eth-contract` dependency (pnpm does not hoist it).
    out.push_str("import { Contract, type Numbers, type Web3 } from 'web3';\n");
    out.push_str(&format!(
        "import {{ {name}Abi }} from './{name}.abi.js';\n\n"
    ));

    // web3 does not export its method object types from `web3`, and it merges
    // overloads into one loosely typed entry. Derive its payable and
    // nonpayable method objects from one-function ABIs instead, and narrow
    // only the `call()` result.
    out.push_str(&format!(
        "type {name}MethodObject<Mutability extends 'payable' | 'nonpayable'> = ReturnType<\n  Contract<\n    readonly [\n      {{\n        readonly type: 'function';\n        readonly name: 'm';\n        readonly stateMutability: Mutability;\n        readonly inputs: readonly [];\n        readonly outputs: readonly [];\n      }},\n    ]\n  >['methods']['m']\n>;\n"
    ));
    out.push_str(&format!(
        "type {name}Method<Mutability extends 'payable' | 'nonpayable', Output> = Omit<\n  {name}MethodObject<Mutability>,\n  'call'\n> & {{\n  call(...args: Parameters<{name}MethodObject<Mutability>['call']>): Promise<Output>;\n}};\n\n"
    ));

    let mut name_counts: HashMap<&str, usize> = HashMap::new();
    for f in &ir.functions {
        *name_counts.entry(f.name.as_str()).or_insert(0) += 1;
    }

    out.push_str(&format!("export interface {name}Methods {{\n"));
    for f in &ir.functions {
        // web3 registers each method under its name, which dispatches overloads
        // by argument count, and under its canonical signature.
        out.push_str(&render_method(name, &f.name, f));
        if name_counts[f.name.as_str()] > 1 {
            let key = serde_json::to_string(&function_signature(f))
                .expect("function signatures serialize as JSON strings");
            out.push_str(&render_method(name, &key, f));
        }
    }
    out.push_str("}\n\n");

    out.push_str(&format!(
        "export type {name}Contract = Omit<Contract<typeof {name}Abi>, 'methods'> & {{\n  readonly methods: {name}Methods;\n}};\n\n"
    ));

    // Factory function — `create<Name>`
    out.push_str(&format!(
        "export function create{}(web3: Web3, address: string): {name}Contract {{\n",
        name.to_upper_camel_case()
    ));
    out.push_str(&format!(
        "  return new Contract({name}Abi, address, web3) as unknown as {name}Contract;\n"
    ));
    out.push_str("}\n");

    out
}

fn render_method(contract: &str, key: &str, f: &AbiFunction) -> String {
    let params = f
        .inputs
        .iter()
        .enumerate()
        .map(|(i, p)| {
            format!(
                "{}: {}",
                safe_param_name(&p.name, i),
                sol_type_to_web3_input(&p.ty)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    let mutability = match f.state_mutability {
        StateMutability::Payable => "payable",
        StateMutability::Pure | StateMutability::View | StateMutability::NonPayable => "nonpayable",
    };
    format!(
        "  {key}({params}): {contract}Method<'{mutability}', {}>;\n",
        render_output_type(&f.outputs)
    )
}

/// web3 returns a single output directly and several outputs as an object
/// keyed by position and by name, with a `__length__` count.
fn render_output_type(outputs: &[AbiParam]) -> String {
    match outputs {
        [] => "void".into(),
        [only] => sol_type_to_ts(&only.ty, TARGET),
        _ => {
            let mut fields: Vec<String> = outputs
                .iter()
                .enumerate()
                .map(|(i, p)| format!("{i}: {}", sol_type_to_ts(&p.ty, TARGET)))
                .collect();
            fields.extend(
                outputs
                    .iter()
                    .filter(|p| !p.name.is_empty() && p.name != "__length__")
                    .map(|p| format!("{}: {}", p.name, sol_type_to_ts(&p.ty, TARGET))),
            );
            fields.push("__length__: number".into());
            format!("{{ {} }}", fields.join("; "))
        }
    }
}

/// Maps a Solidity type to the web3.js v4 argument type. Numeric arguments
/// accept any web3 `Numbers` value; return values decode to `bigint`.
fn sol_type_to_web3_input(ty: &SolType) -> String {
    match ty {
        SolType::Uint(_) | SolType::Int(_) => "Numbers".into(),
        SolType::Array(inner) | SolType::FixedArray(inner, _) => {
            format!("{}[]", sol_type_to_web3_input(inner))
        }
        SolType::Tuple(components) => {
            let fields: Vec<String> = components
                .iter()
                .enumerate()
                .map(|(i, c)| {
                    format!(
                        "{}: {}",
                        safe_param_name(&c.name, i),
                        sol_type_to_web3_input(&c.ty)
                    )
                })
                .collect();
            format!("{{ {} }}", fields.join("; "))
        }
        SolType::Bool
        | SolType::Address
        | SolType::Bytes
        | SolType::BytesN(_)
        | SolType::StringType => sol_type_to_ts(ty, TARGET),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;

    fn fixture(name: &str, file: &str) -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures")
                .join(file),
        )
        .unwrap();
        parse_artifact(name, &json).unwrap()
    }

    fn inline(name: &str, abi: &str) -> String {
        let ir = parse_artifact(name, &format!(r#"{{"abi":{abi}}}"#)).unwrap();
        render_web3js_file(&ir)
    }

    #[test]
    fn imports_everything_from_web3() {
        let out = render_web3js_file(&fixture("ERC20", "erc20.json"));
        assert!(
            out.contains("import { Contract, type Numbers, type Web3 } from 'web3';"),
            "{out}"
        );
        assert!(
            out.contains("import { ERC20Abi } from './ERC20.abi.js';"),
            "{out}"
        );
        assert!(!out.contains("web3-eth-contract"), "{out}");
    }

    #[test]
    fn contract_type_builds_on_web3_contract() {
        let out = render_web3js_file(&fixture("ERC20", "erc20.json"));
        assert!(
            out.contains(
                "export type ERC20Contract = Omit<Contract<typeof ERC20Abi>, 'methods'> & {\n  readonly methods: ERC20Methods;\n};"
            ),
            "{out}"
        );
        assert!(
            out.contains(
                "export function createErc20(web3: Web3, address: string): ERC20Contract {"
            ),
            "{out}"
        );
        assert!(
            out.contains(
                "  return new Contract(ERC20Abi, address, web3) as unknown as ERC20Contract;"
            ),
            "{out}"
        );
        assert!(!out.contains("as any"), "{out}");
    }

    #[test]
    fn methods_type_arguments_and_call_results() {
        let out = render_web3js_file(&fixture("ERC20", "erc20.json"));
        assert!(
            out.contains("  balanceOf(account: string): ERC20Method<'nonpayable', bigint>;"),
            "{out}"
        );
        assert!(
            out.contains("  decimals(): ERC20Method<'nonpayable', bigint>;"),
            "{out}"
        );
        assert!(
            out.contains(
                "  transfer(to: string, amount: Numbers): ERC20Method<'nonpayable', boolean>;"
            ),
            "{out}"
        );
    }

    #[test]
    fn method_objects_come_from_web3_by_mutability() {
        let out = inline(
            "Staking",
            r#"[
            {"type":"function","name":"stake","stateMutability":"payable","inputs":[{"name":"ids","type":"uint256[]"}],"outputs":[]},
            {"type":"function","name":"sum","stateMutability":"pure","inputs":[{"name":"a","type":"uint8"}],"outputs":[{"name":"","type":"uint8"}]},
            {"type":"function","name":"ping","stateMutability":"view","inputs":[],"outputs":[]}
        ]"#,
        );
        assert!(
            out.contains("  stake(ids: Numbers[]): StakingMethod<'payable', void>;"),
            "{out}"
        );
        assert!(
            out.contains("  sum(a: Numbers): StakingMethod<'nonpayable', bigint>;"),
            "{out}"
        );
        assert!(
            out.contains("  ping(): StakingMethod<'nonpayable', void>;"),
            "{out}"
        );
        assert!(
            out.contains("type StakingMethodObject<Mutability extends 'payable' | 'nonpayable'> = ReturnType<"),
            "{out}"
        );
        assert!(
            out.contains("  call(...args: Parameters<StakingMethodObject<Mutability>['call']>): Promise<Output>;"),
            "{out}"
        );
    }

    #[test]
    fn overloads_use_runtime_keys() {
        let out = render_web3js_file(&fixture("Vault", "vault.json"));
        for key in [
            "  deposit(amount: Numbers): VaultMethod<",
            "  \"deposit(uint256)\"(amount: Numbers): VaultMethod<",
            "  \"deposit(uint256,address)\"(",
        ] {
            assert!(out.contains(key), "missing {key:?} in:\n{out}");
        }
        assert!(!out.contains("depositUint256"), "{out}");
    }

    #[test]
    fn multiple_outputs_are_keyed_by_position_and_name() {
        let out = inline(
            "Pair",
            r#"[{"type":"function","name":"getPair","stateMutability":"view","inputs":[],
            "outputs":[{"name":"owner","type":"address"},{"name":"","type":"uint256"},{"name":"ok","type":"bool"}]}]"#,
        );
        assert!(
            out.contains("getPair(): PairMethod<'nonpayable', { 0: string; 1: bigint; 2: boolean; owner: string; ok: boolean; __length__: number }>;"),
            "{out}"
        );
    }

    #[test]
    fn reserved_and_unnamed_params_are_sanitized() {
        let out = inline(
            "Names",
            r#"[{"type":"function","name":"set","stateMutability":"nonpayable",
            "inputs":[{"name":"class","type":"uint256"},{"name":"","type":"bytes32"}],"outputs":[]}]"#,
        );
        assert!(
            out.contains("set(_class: Numbers, arg1: string): NamesMethod<'nonpayable', void>;"),
            "{out}"
        );
    }

    #[test]
    fn contract_without_functions_still_has_contract_type() {
        let out = inline("Empty", "[]");
        assert!(out.contains("export interface EmptyMethods {\n}"), "{out}");
        assert!(out.contains("export type EmptyContract ="), "{out}");
    }
}
