use crate::type_mapper::{overload_suffix, overload_suffix_from_sol_types, safe_param_name};
use abi_typegen_core::types::{
    AbiConstructor, AbiError, AbiEvent, AbiEventParam, AbiFunction, AbiParam, ContractIr, NatSpec,
    SolType, TupleComponent,
};
use heck::ToUpperCamelCase;
use std::collections::HashMap;

/// Generates `<ContractName>.zod.ts` containing Zod validation schemas.
pub fn render_zod_file(ir: &ContractIr) -> String {
    let mut out = String::new();
    out.push_str("// Auto-generated by abi-typegen. Do not edit manually.\n");
    out.push_str("import * as z from 'zod';\n");
    let mut has_sections = false;

    if let Some(constructor) = &ir.constructor
        && !constructor.inputs.is_empty()
    {
        append_section(
            &mut out,
            &mut has_sections,
            render_constructor_schema(&ir.name, constructor),
        );
    }

    let function_counts =
        item_name_counts(ir.functions.iter().map(|function| function.name.as_str()));
    for function in &ir.functions {
        append_function_schemas(
            &mut out,
            &mut has_sections,
            &ir.name,
            function,
            &function_counts,
        );
    }

    let event_counts = item_name_counts(ir.events.iter().map(|event| event.name.as_str()));
    for event in &ir.events {
        if !event.inputs.is_empty() {
            append_section(
                &mut out,
                &mut has_sections,
                render_event_schema(&ir.name, event, &event_counts),
            );
        }
    }

    let error_counts = item_name_counts(ir.errors.iter().map(|error| error.name.as_str()));
    for error in &ir.errors {
        if !error.inputs.is_empty() {
            append_section(
                &mut out,
                &mut has_sections,
                render_error_schema(&ir.name, error, &error_counts),
            );
        }
    }

    if has_sections {
        out.push('\n');
    }

    out
}

fn append_section(out: &mut String, has_sections: &mut bool, section: String) {
    if *has_sections {
        out.push_str("\n\n");
    } else {
        out.push('\n');
        *has_sections = true;
    }
    out.push_str(&section);
}

fn item_name_counts<'a>(names: impl Iterator<Item = &'a str>) -> HashMap<&'a str, usize> {
    let mut counts = HashMap::new();
    for name in names {
        *counts.entry(name).or_insert(0) += 1;
    }
    counts
}

fn render_constructor_schema(contract_name: &str, constructor: &AbiConstructor) -> String {
    let type_name = format!("{}ConstructorParams", contract_name);
    render_schema_export(
        &format!("{}Schema", type_name),
        &type_name,
        &render_param_object_schema(&constructor.inputs),
        None,
    )
}

fn append_function_schemas(
    out: &mut String,
    has_sections: &mut bool,
    contract_name: &str,
    function: &AbiFunction,
    function_counts: &HashMap<&str, usize>,
) {
    let base_name = function_base_name(contract_name, function, function_counts);

    if !function.inputs.is_empty() {
        let type_name = format!("{}Params", base_name);
        append_section(
            out,
            has_sections,
            render_schema_export(
                &format!("{}Schema", type_name),
                &type_name,
                &render_param_object_schema(&function.inputs),
                function
                    .natspec
                    .as_ref()
                    .map(|natspec| render_jsdoc_for_inputs(natspec, &function.inputs)),
            ),
        );
    }

    if !function.outputs.is_empty() {
        let type_name = format!("{}Result", base_name);
        append_section(
            out,
            has_sections,
            render_schema_export(
                &format!("{}Schema", type_name),
                &type_name,
                &render_output_schema(&function.outputs),
                function
                    .natspec
                    .as_ref()
                    .map(|natspec| render_jsdoc_for_outputs(natspec, &function.outputs)),
            ),
        );
    }
}

fn render_event_schema(
    contract_name: &str,
    event: &AbiEvent,
    event_counts: &HashMap<&str, usize>,
) -> String {
    let type_name = format!(
        "{}Event",
        event_base_name(contract_name, event, event_counts)
    );
    render_schema_export(
        &format!("{}Schema", type_name),
        &type_name,
        &render_event_param_object_schema(&event.inputs),
        event
            .natspec
            .as_ref()
            .map(|natspec| render_jsdoc_for_event_inputs(natspec, &event.inputs)),
    )
}

fn render_error_schema(
    contract_name: &str,
    error: &AbiError,
    error_counts: &HashMap<&str, usize>,
) -> String {
    let type_name = format!(
        "{}Error",
        error_base_name(contract_name, error, error_counts)
    );
    render_schema_export(
        &format!("{}Schema", type_name),
        &type_name,
        &render_param_object_schema(&error.inputs),
        error
            .natspec
            .as_ref()
            .map(|natspec| render_jsdoc_for_inputs(natspec, &error.inputs)),
    )
}

fn function_base_name(
    contract_name: &str,
    function: &AbiFunction,
    function_counts: &HashMap<&str, usize>,
) -> String {
    let mut base_name = format!("{}{}", contract_name, function.name.to_upper_camel_case());
    if function_counts
        .get(function.name.as_str())
        .copied()
        .unwrap_or(0)
        > 1
    {
        base_name.push_str(&overload_suffix(&function.inputs));
    }
    base_name
}

fn event_base_name(
    contract_name: &str,
    event: &AbiEvent,
    event_counts: &HashMap<&str, usize>,
) -> String {
    let mut base_name = format!("{}{}", contract_name, event.name.to_upper_camel_case());
    if event_counts.get(event.name.as_str()).copied().unwrap_or(0) > 1 {
        base_name.push_str(&overload_suffix_from_sol_types(
            event.inputs.iter().map(|input| &input.ty),
        ));
    }
    base_name
}

fn error_base_name(
    contract_name: &str,
    error: &AbiError,
    error_counts: &HashMap<&str, usize>,
) -> String {
    let mut base_name = format!("{}{}", contract_name, error.name.to_upper_camel_case());
    if error_counts.get(error.name.as_str()).copied().unwrap_or(0) > 1 {
        base_name.push_str(&overload_suffix(&error.inputs));
    }
    base_name
}

fn render_schema_export(
    schema_name: &str,
    type_name: &str,
    schema_expr: &str,
    jsdoc: Option<String>,
) -> String {
    let mut out = String::new();
    if let Some(jsdoc) = jsdoc.filter(|docs| !docs.is_empty()) {
        out.push_str(&jsdoc);
    }
    out.push_str(&format!(
        "export const {} = {};\n",
        schema_name, schema_expr
    ));
    out.push_str(&format!(
        "export type {} = z.infer<typeof {}>;\n",
        type_name, schema_name
    ));
    out
}

fn render_param_object_schema(inputs: &[AbiParam]) -> String {
    render_named_fields_schema(inputs.iter().enumerate().map(|(index, input)| {
        (
            safe_param_name(&input.name, index),
            render_sol_type_schema(&input.ty),
        )
    }))
}

fn render_event_param_object_schema(inputs: &[AbiEventParam]) -> String {
    render_named_fields_schema(inputs.iter().enumerate().map(|(index, input)| {
        (
            safe_param_name(&input.name, index),
            render_sol_type_schema(&input.ty),
        )
    }))
}

fn render_output_schema(outputs: &[AbiParam]) -> String {
    if outputs.len() == 1 {
        return render_sol_type_schema(&outputs[0].ty);
    }

    render_named_fields_schema(outputs.iter().enumerate().map(|(index, output)| {
        (
            safe_param_name(&output.name, index),
            render_sol_type_schema(&output.ty),
        )
    }))
}

fn render_named_fields_schema(fields: impl IntoIterator<Item = (String, String)>) -> String {
    let mut fields = fields.into_iter();
    let Some((first_name, first_schema)) = fields.next() else {
        return "z.object({})".to_string();
    };

    let mut out = String::from("z.object({\n");
    out.push_str(&format!("  {}: {},\n", first_name, first_schema));
    for (name, schema) in fields {
        out.push_str(&format!("  {}: {},\n", name, schema));
    }
    out.push_str("})");
    out
}

fn render_sol_type_schema(ty: &SolType) -> String {
    match ty {
        SolType::Uint(bits) => render_uint_schema(*bits),
        SolType::Int(bits) => render_int_schema(*bits),
        SolType::Bool => "z.boolean()".to_string(),
        SolType::Address => "z.string().regex(/^0x[a-fA-F0-9]{40}$/)".to_string(),
        SolType::Bytes => "z.string().regex(/^0x(?:[a-fA-F0-9]{2})*$/)".to_string(),
        SolType::BytesN(size) => {
            format!(
                "z.string().regex(/^0x[a-fA-F0-9]{{{}}}$/)",
                usize::from(*size) * 2
            )
        }
        SolType::StringType => "z.string()".to_string(),
        SolType::Array(inner) => format!("z.array({})", render_sol_type_schema(inner)),
        SolType::FixedArray(inner, size) => {
            let inner_schema = render_sol_type_schema(inner);
            let items = std::iter::repeat_n(inner_schema.as_str(), *size)
                .collect::<Vec<_>>()
                .join(", ");
            format!("z.tuple([{}])", items)
        }
        SolType::Tuple(components) => render_tuple_schema(components),
    }
}

fn render_uint_schema(bits: u16) -> String {
    if bits <= 48 {
        let max = (1u128 << bits) - 1;
        return format!("z.number().int().min(0).max({})", max);
    }

    format!(
        "z.bigint().refine((value) => value >= 0n && value <= (1n << {}n) - 1n, {{ message: 'Expected uint{}' }})",
        bits, bits
    )
}

fn render_int_schema(bits: u16) -> String {
    if bits <= 48 {
        let max = (1i128 << (bits - 1)) - 1;
        let min = -(1i128 << (bits - 1));
        return format!("z.number().int().min({}).max({})", min, max);
    }

    format!(
        "z.bigint().refine((value) => value >= -(1n << {}n) && value <= (1n << {}n) - 1n, {{ message: 'Expected int{}' }})",
        bits - 1,
        bits - 1,
        bits
    )
}

fn render_tuple_schema(components: &[TupleComponent]) -> String {
    let mut components = components.iter().enumerate();
    let Some((index, component)) = components.next() else {
        return "z.object({})".to_string();
    };

    let mut out = String::from("z.object({ ");
    out.push_str(&format!(
        "{}: {}",
        safe_param_name(&component.name, index),
        render_sol_type_schema(&component.ty)
    ));
    for (index, component) in components {
        out.push_str(", ");
        out.push_str(&format!(
            "{}: {}",
            safe_param_name(&component.name, index),
            render_sol_type_schema(&component.ty)
        ));
    }
    out.push_str(" })");
    out
}

fn render_jsdoc_for_inputs(natspec: &NatSpec, inputs: &[AbiParam]) -> String {
    render_jsdoc(
        natspec,
        inputs
            .iter()
            .enumerate()
            .map(|(index, input)| (input.name.as_str(), safe_param_name(&input.name, index))),
        std::iter::empty(),
    )
}

fn render_jsdoc_for_outputs(natspec: &NatSpec, outputs: &[AbiParam]) -> String {
    render_jsdoc(
        natspec,
        std::iter::empty(),
        outputs
            .iter()
            .enumerate()
            .map(|(index, output)| (output.name.as_str(), safe_param_name(&output.name, index))),
    )
}

fn render_jsdoc_for_event_inputs(natspec: &NatSpec, inputs: &[AbiEventParam]) -> String {
    render_jsdoc(
        natspec,
        inputs
            .iter()
            .enumerate()
            .map(|(index, input)| (input.name.as_str(), safe_param_name(&input.name, index))),
        std::iter::empty(),
    )
}

fn render_jsdoc<'a, P, R>(natspec: &NatSpec, params: P, returns: R) -> String
where
    P: IntoIterator<Item = (&'a str, String)>,
    R: IntoIterator<Item = (&'a str, String)>,
{
    let mut lines = Vec::new();
    if let Some(notice) = &natspec.notice {
        lines.push(format!(" * {}", notice));
    }
    if let Some(dev) = &natspec.dev {
        lines.push(format!(" * @dev {}", dev));
    }
    for (original_name, safe_name) in params {
        if let Some(description) = natspec.params.get(original_name) {
            lines.push(format!(" * @param {} {}", safe_name, description));
        }
    }
    for (original_name, safe_name) in returns {
        if let Some(description) = natspec.returns.get(original_name) {
            lines.push(format!(" * @returns {} {}", safe_name, description));
        }
    }
    if lines.is_empty() {
        return String::new();
    }

    format!("/**\n{}\n */\n", lines.join("\n"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use abi_typegen_core::parser::parse_artifact;
    use abi_typegen_core::types::StateMutability;
    use std::collections::HashMap;

    fn fixture(contract_name: &str, file_name: &str) -> ContractIr {
        let json = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../tests/fixtures")
                .join(file_name),
        )
        .unwrap();
        parse_artifact(contract_name, &json).unwrap()
    }

    #[test]
    fn contains_header_and_zod_import() {
        let out = render_zod_file(&fixture("ERC20", "erc20.json"));
        assert!(out.contains("// Auto-generated by abi-typegen."));
        assert!(out.contains("import * as z from 'zod';"));
    }

    #[test]
    fn emits_function_param_and_result_schemas() {
        let out = render_zod_file(&fixture("ERC20", "erc20.json"));
        assert!(out.contains("export const ERC20TransferParamsSchema = z.object({"));
        assert!(out.contains(
            "export type ERC20TransferParams = z.infer<typeof ERC20TransferParamsSchema>;"
        ));
        assert!(out.contains("export const ERC20BalanceOfResultSchema = z.bigint().refine("));
    }

    #[test]
    fn overloads_use_signature_based_names() {
        let out = render_zod_file(&fixture("Vault", "vault.json"));
        assert!(out.contains("export const VaultDepositUint256ParamsSchema = z.object({"));
        assert!(out.contains("export const VaultDepositUint256AddressParamsSchema = z.object({"));
    }

    #[test]
    fn tuple_outputs_become_object_schemas() {
        let out = render_zod_file(&fixture("Vault", "vault.json"));
        assert!(out.contains(
            "export const VaultGetPositionResultSchema = z.object({ shares: z.bigint().refine("
        ));
    }

    #[test]
    fn constructor_events_errors_and_complex_types_are_rendered() {
        let ir = ContractIr {
            name: "Complex".to_string(),
            constructor: Some(AbiConstructor {
                inputs: vec![AbiParam {
                    name: "owner".to_string(),
                    ty: SolType::Address,
                    internal_type: None,
                }],
                state_mutability: StateMutability::NonPayable,
            }),
            functions: vec![AbiFunction {
                name: "configure".to_string(),
                inputs: vec![
                    AbiParam {
                        name: "salt".to_string(),
                        ty: SolType::BytesN(4),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "limits".to_string(),
                        ty: SolType::FixedArray(Box::new(SolType::Uint(16)), 2),
                        internal_type: None,
                    },
                    AbiParam {
                        name: "metadata".to_string(),
                        ty: SolType::Tuple(vec![
                            TupleComponent {
                                name: "name".to_string(),
                                ty: SolType::StringType,
                                internal_type: None,
                            },
                            TupleComponent {
                                name: "".to_string(),
                                ty: SolType::Bytes,
                                internal_type: None,
                            },
                        ]),
                        internal_type: None,
                    },
                ],
                outputs: vec![
                    AbiParam {
                        name: "ok".to_string(),
                        ty: SolType::Bool,
                        internal_type: None,
                    },
                    AbiParam {
                        name: "".to_string(),
                        ty: SolType::Int(32),
                        internal_type: None,
                    },
                ],
                state_mutability: StateMutability::NonPayable,
                natspec: Some(NatSpec {
                    notice: Some("Configure contract".to_string()),
                    dev: Some("Only owner".to_string()),
                    params: HashMap::from([
                        ("salt".to_string(), "configuration salt".to_string()),
                        ("limits".to_string(), "two limits".to_string()),
                    ]),
                    returns: HashMap::from([
                        ("ok".to_string(), "whether it worked".to_string()),
                        ("".to_string(), "signed status code".to_string()),
                    ]),
                }),
            }],
            events: vec![AbiEvent {
                name: "Configured".to_string(),
                inputs: vec![AbiEventParam {
                    name: "owner".to_string(),
                    ty: SolType::Address,
                    indexed: true,
                    internal_type: None,
                }],
                anonymous: false,
                natspec: Some(NatSpec {
                    notice: Some("Configuration changed".to_string()),
                    dev: None,
                    params: HashMap::from([("owner".to_string(), "new owner".to_string())]),
                    returns: HashMap::new(),
                }),
            }],
            errors: vec![AbiError {
                name: "BadConfig".to_string(),
                inputs: vec![AbiParam {
                    name: "code".to_string(),
                    ty: SolType::Uint(8),
                    internal_type: None,
                }],
                natspec: Some(NatSpec {
                    notice: Some("Invalid configuration".to_string()),
                    dev: None,
                    params: HashMap::from([("code".to_string(), "failure code".to_string())]),
                    returns: HashMap::new(),
                }),
            }],
            has_fallback: false,
            has_receive: false,
            natspec: None,
            raw_abi: serde_json::Value::Array(vec![]),
        };

        let out = render_zod_file(&ir);

        assert!(out.contains("export const ComplexConstructorParamsSchema = z.object({"));
        assert!(out.contains("owner: z.string().regex(/^0x[a-fA-F0-9]{40}$/)"));
        assert!(out.contains("salt: z.string().regex(/^0x[a-fA-F0-9]{8}$/)"));
        assert!(out.contains("limits: z.tuple([z.number().int().min(0).max(65535), z.number().int().min(0).max(65535)])"));
        assert!(out.contains("metadata: z.object({ name: z.string(), arg1: z.string().regex(/^0x(?:[a-fA-F0-9]{2})*$/) })"));
        assert!(out.contains("export const ComplexConfigureResultSchema = z.object({"));
        assert!(out.contains("arg1: z.number().int().min(-2147483648).max(2147483647)"));
        assert!(out.contains("export const ComplexConfiguredEventSchema = z.object({"));
        assert!(out.contains("export const ComplexBadConfigErrorSchema = z.object({"));
        assert!(out.contains(" * Configure contract"));
        assert!(out.contains(" * @dev Only owner"));
        assert!(out.contains(" * @param salt configuration salt"));
        assert!(out.contains(" * @returns ok whether it worked"));
        assert!(out.contains(" * @param owner new owner"));
    }

    #[test]
    fn overloaded_events_and_errors_use_signature_based_names() {
        let ir = ContractIr {
            name: "Vault".to_string(),
            constructor: None,
            functions: vec![],
            events: vec![
                AbiEvent {
                    name: "Moved".to_string(),
                    inputs: vec![AbiEventParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        indexed: false,
                        internal_type: None,
                    }],
                    anonymous: false,
                    natspec: None,
                },
                AbiEvent {
                    name: "Moved".to_string(),
                    inputs: vec![AbiEventParam {
                        name: "account".to_string(),
                        ty: SolType::Address,
                        indexed: true,
                        internal_type: None,
                    }],
                    anonymous: false,
                    natspec: None,
                },
            ],
            errors: vec![
                AbiError {
                    name: "Rejected".to_string(),
                    inputs: vec![AbiParam {
                        name: "amount".to_string(),
                        ty: SolType::Uint(256),
                        internal_type: None,
                    }],
                    natspec: None,
                },
                AbiError {
                    name: "Rejected".to_string(),
                    inputs: vec![AbiParam {
                        name: "account".to_string(),
                        ty: SolType::Address,
                        internal_type: None,
                    }],
                    natspec: None,
                },
            ],
            has_fallback: false,
            has_receive: false,
            natspec: None,
            raw_abi: serde_json::Value::Array(vec![]),
        };

        let out = render_zod_file(&ir);

        assert!(out.contains("export const VaultMovedUint256EventSchema = z.object({"));
        assert!(out.contains("export const VaultMovedAddressEventSchema = z.object({"));
        assert!(out.contains("export const VaultRejectedUint256ErrorSchema = z.object({"));
        assert!(out.contains("export const VaultRejectedAddressErrorSchema = z.object({"));
    }
}
